package dev.projecteclipse.eclipse.backrooms;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.buffs.TimedBuffApi;
import dev.projecteclipse.eclipse.core.state.EclipseWorldState;
import dev.projecteclipse.eclipse.entity.EclipseEntities;
import dev.projecteclipse.eclipse.entity.TheOtherEntity;
import dev.projecteclipse.eclipse.lang.ServerLang;
import dev.projecteclipse.eclipse.network.fx.S2CCaptionPayload;
import dev.projecteclipse.eclipse.registry.EclipseItems;
import dev.projecteclipse.eclipse.registry.EclipseSounds;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.HoverEvent;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.network.chat.Style;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerBossEvent;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.BossEvent;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.Heightmap;
import net.neoforged.bus.api.EventPriority;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.entity.living.LivingDeathEvent;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import net.neoforged.neoforge.event.server.ServerStoppedEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;

/**
 * The Backrooms event state machine (plans_v5 PLAN-C C18, IDEAS-backrooms_finale §A —
 * the {@code XboxEventService} skeleton): dev-triggered lifecycle
 * {@code IDLE → ANNOUNCED → OPEN → CLOSING → IDLE} persisted in {@link BackroomsState}.
 *
 * <ul>
 *   <li><b>The maze is TERRAIN now</b> (user decree): the {@code eclipse:backrooms}
 *       dimension is generated by {@link BackroomsChunkGenerator} — FIVE stacked
 *       procedural layers ({@link BackroomsLayers}: Yellow Rooms / Poolrooms /
 *       Warehouse / Flooded Halls / The Hollow), infinite in X/Z, produced as chunks
 *       load. There is NO stamp phase any more: ANNOUNCED just places the portal and
 *       flips OPEN on the next tick. Loot barrels are placed empty by the generator and
 *       filled lazily once per instance ({@code BackroomsState.markLootFilled}) as
 *       players approach.</li>
 *   <li><b>Portal entries</b> mirror the xbox event: frameless star-rift
 *       ({@link BackroomsPortal}), collision entry, return anchors, per-instance
 *       voluntary-exit lockouts, {@code /backroomsleave} click-confirm.</li>
 *   <li><b>Protected deaths</b>: the HIGHEST-priority {@link LivingDeathEvent} cancel —
 *       no drops, no Eclipse life loss, no lockout ("you no-clipped back out"; the horror
 *       dimension must be safe to be scary, IDEAS §A5).</li>
 *   <li><b>Flicker</b> (IDEAS §A2): every {@value #FLICKER_INTERVAL_TICKS} t, faulty
 *       panels within {@value #FLICKER_PLAYER_RANGE} blocks of a player swap
 *       {@code ochre_froglight ↔ yellow_stained_glass} on their hashed schedule
 *       (photosensitivity-safe: one dark window per 120–279 t period).</li>
 *   <li><b>Mob budget</b> (IDEAS §A3): Wanderers capped at {@value #WANDERER_CAP},
 *       spawned on the LAYER a player is exploring (never over a drop shaft or drain),
 *       ≥{@value #WANDERER_MIN_PLAYER_DISTANCE} blocks from players, never on the spawn
 *       highway cross; 1–2 {@code TheOtherEntity} cameo
 *       ≥{@value #THE_OTHER_MIN_SPAWN_DISTANCE} blocks from the spawn cell
 *       (fixed_time midnight disarms its dawn despawn — zero entity changes).</li>
 *   <li><b>Jumpscare</b>: {@link BackroomsScare#tick} every 10 t while OPEN.</li>
 *   <li><b>Dread</b> (F-042): {@link BackroomsDread#tick} every 10 t while OPEN — the
 *       pursuit heartbeat/scrape audio, the client-side light-flicker blackout and the
 *       far footsteps, all per-player and cooldown-gated.</li>
 *   <li><b>T-5:00 exit portal</b> (IDEAS §A5, moved to level 5 by F-043): "an EXIT sign
 *       hums to life" — a second star-rift deep in The Hollow, ringed with the only
 *       lanterns on that level and audible by {@link BackroomsDread#tickExitBeacon};
 *       walking out through it upgrades the
 *       walker's reward share ({@value #REWARD_SHARDS_UPGRADED} vs
 *       {@value #REWARD_SHARDS_BASE} umbral shards, direct-to-inventory at close, plus
 *       the Almond Water). CLOSING also starts the {@code TimedBuffApi} participation
 *       buff {@value #REWARD_BUFF_ID}.</li>
 * </ul>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID)
public final class BackroomsEventService {

    public static final int DEFAULT_MINUTES = 30;

    /** T-5:00 — the EXIT-portal spawn threshold (the old chat warning is gone, C-quiet). */
    private static final long WARN_5M_MILLIS = 5L * 60L * 1000L;
    private static final long LEAVE_CONFIRM_WINDOW_MILLIS = 15_000L;
    private static final long BOUNCE_MESSAGE_THROTTLE_MILLIS = 3_000L;
    private static final long GRACEFUL_STOP_MILLIS = 10_000L;

    /** Flicker pass cadence (2 t resolves the 3–6 t dark windows crisply). */
    private static final int FLICKER_INTERVAL_TICKS = 2;
    private static final double FLICKER_PLAYER_RANGE = 32.0D;

    /** Spawner pass cadence (the {@code EclipseSpawner} 5 s discipline). */
    private static final int SPAWNER_CADENCE_TICKS = 100;
    /** IDEAS §A3.1: 1 per ~40×40 blocks of the 192×192 maze, cap 6. */
    private static final int WANDERER_CAP = 6;
    private static final double WANDERER_MIN_PLAYER_DISTANCE = 24.0D;
    private static final int THE_OTHER_CAP = 2;
    private static final double THE_OTHER_MIN_SPAWN_DISTANCE = 64.0D;

    /** Participation buff started at CLOSING (the xbox default reward id). */
    private static final String REWARD_BUFF_ID = "double_skill_xp";
    private static final int REWARD_BUFF_MINUTES = 30;
    /** Umbral shards direct-to-inventory at close; EXIT-portal walkers get the upgrade. */
    private static final int REWARD_SHARDS_BASE = 2;
    private static final int REWARD_SHARDS_UPGRADED = 4;

    /** F-043: the EXIT spawns this far out on The Hollow's walk plane (blocks from origin). */
    private static final int EXIT_MIN_RADIUS = 96;
    private static final int EXIT_MAX_RADIUS = 192;
    /** How far {@code /dev backrooms tp} may search outward for a standable cell. */
    private static final int DEV_TP_SEARCH_RINGS = 3;

    /** Whisper caption odds per 10 t check after 3 min inside (≈ once per ~5 min). */
    private static final int WHISPER_ODDS = 600;
    private static final long WHISPER_MIN_INSIDE_MILLIS = 3L * 60L * 1000L;

    // ---- transient per-run state (cleared on ServerStoppedEvent; SavedData is per-save) ----
    @Nullable
    private static ServerBossEvent bossBar;
    private static final Map<UUID, Long> PENDING_LEAVE_CONFIRMS = new HashMap<>();
    private static final Map<UUID, Long> LAST_BOUNCE_MESSAGE = new HashMap<>();
    private static long totalWindowMillisHint;
    /** One-shot warn latch for the "no portal spot near spawn" ANNOUNCED retry loop. */
    private static boolean portalSpotWarned;

    private BackroomsEventService() {}

    /** Exit paths — pick the right player-facing message. */
    public enum ExitReason { DEATH, LEFT, TIME_UP, CLOSED, EXIT_PORTAL }

    // ================================================================== lifecycle

    /** Crash resume (xbox §2.13.6 law): expired windows close on boot. */
    @SubscribeEvent
    public static void onServerStarted(ServerStartedEvent event) {
        resumeOnBoot(event.getServer());
    }

    /** Boot-resume logic, callable from gametests. */
    public static void resumeOnBoot(MinecraftServer server) {
        BackroomsState state = BackroomsState.get(server);
        long now = System.currentTimeMillis();
        switch (state.phase()) {
            case OPEN, ANNOUNCED -> {
                if (state.endsAtEpochMillis() <= now) {
                    EclipseMod.LOGGER.info("Backrooms event expired while server was down — closing now");
                    beginClosing(server, state, ExitReason.CLOSED);
                } else {
                    totalWindowMillisHint = Math.max(state.endsAtEpochMillis() - now,
                            DEFAULT_MINUTES * 60_000L);
                    EclipseMod.LOGGER.info("Backrooms event resumes: {} remaining",
                            mmss(state.endsAtEpochMillis() - now));
                }
            }
            case CLOSING -> beginClosing(server, state, ExitReason.CLOSED);
            case IDLE -> { /* nothing */ }
        }
    }

    @SubscribeEvent
    public static void onServerStopped(ServerStoppedEvent event) {
        bossBar = null;
        PENDING_LEAVE_CONFIRMS.clear();
        LAST_BOUNCE_MESSAGE.clear();
        totalWindowMillisHint = 0L;
        portalSpotWarned = false;
        BackroomsScare.reset();
        BackroomsDread.reset();
    }

    @SubscribeEvent
    public static void onServerTick(ServerTickEvent.Post event) {
        MinecraftServer server = event.getServer();
        BackroomsState state = BackroomsState.get(server);
        if (state.phase() != BackroomsState.Phase.OPEN
                && state.phase() != BackroomsState.Phase.ANNOUNCED) {
            return;
        }

        // ANNOUNCED = portal placement (the maze is terrain — nothing to build). Retries
        // once a second when no valid spot exists near spawn (operator can also place).
        if (state.phase() == BackroomsState.Phase.ANNOUNCED) {
            if (server.getTickCount() % 20 == 0) {
                openEvent(server, state);
            }
            if (state.phase() != BackroomsState.Phase.OPEN) {
                return;
            }
        }

        int tickCount = server.getTickCount();
        if (state.phase() == BackroomsState.Phase.OPEN && tickCount % FLICKER_INTERVAL_TICKS == 0) {
            tickFlicker(server, state);
        }
        if (tickCount % 10 != 0) {
            return;
        }

        long now = System.currentTimeMillis();
        long remaining = state.endsAtEpochMillis() - now;
        if (remaining <= 0L) {
            beginClosing(server, state, ExitReason.TIME_UP);
            return;
        }

        if (state.phase() == BackroomsState.Phase.OPEN) {
            tickEntryPortal(server, state);
            tickInside(server, state, remaining);
            if (tickCount % SPAWNER_CADENCE_TICKS == 0) {
                tickSpawner(server, state);
            }
        }
    }

    // ================================================================== start / stop

    /** Outcome of {@link #start}: {@code started=false} → {@code message} is the error. */
    public record StartResult(boolean started, @Nullable Component message) {}

    /**
     * Starts the event: validates the dimension, begins the instance (which reseeds the
     * loot) and enters ANNOUNCED — the portal spawns + OPEN flips from
     * {@link #openEvent} on the next tick (the maze is terrain; there is nothing to
     * build).
     */
    public static StartResult start(MinecraftServer server, int minutes, String operatorName) {
        BackroomsState state = BackroomsState.get(server);
        if (state.phase() == BackroomsState.Phase.OPEN
                || state.phase() == BackroomsState.Phase.ANNOUNCED) {
            return new StartResult(false, Component.translatable("dev.eclipse.backrooms.start.already",
                    mmss(state.endsAtEpochMillis() - System.currentTimeMillis())));
        }
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null) {
            return new StartResult(false, Component.translatable("dev.eclipse.backrooms.start.no_level",
                    BackroomsDimension.BACKROOMS.location().toString()));
        }

        int effectiveMinutes = minutes > 0 ? minutes : DEFAULT_MINUTES;
        long now = System.currentTimeMillis();
        state.beginInstance(now + effectiveMinutes * 60_000L);
        totalWindowMillisHint = effectiveMinutes * 60_000L;
        portalSpotWarned = false;
        BackroomsScare.reset();
        BackroomsDread.reset();

        // User decree: NO start announcement — the single portal line lands at OPEN.
        EclipseMod.LOGGER.info("Backrooms event started by {}: minutes={}, instance={}, lootSeed={}",
                operatorName, effectiveMinutes, state.instanceId(), Long.toHexString(state.mazeSeed()));
        return new StartResult(true, null);
    }

    /** Flips ANNOUNCED → OPEN by placing the entry portal (the maze is generated terrain). */
    private static void openEvent(MinecraftServer server, BackroomsState state) {
        ServerLevel overworld = server.overworld();
        BlockPos spot = BackroomsPortal.findSpotNearSpawn(overworld);
        if (spot == null) {
            if (!portalSpotWarned) {
                portalSpotWarned = true;
                EclipseMod.LOGGER.warn("Backrooms event: no portal spot near spawn — stays ANNOUNCED; "
                        + "use /dev backrooms portal here");
            }
            return;
        }
        BackroomsPortal.place(overworld, spot);
        state.setPortal(overworld.dimension(), spot);
        state.setPhase(BackroomsState.Phase.OPEN);
        announcePortal(server);
        EclipseMod.LOGGER.info("Backrooms event open (instance {}, terrain-generated layers)",
                state.instanceId());
    }

    /** {@code /dev backrooms portal here|remove} backing (xbox semantics). */
    @Nullable
    public static Component portalHere(MinecraftServer server, ServerPlayer operator) {
        if (BackroomsDimension.isInBackrooms(operator)) {
            return Component.translatable("dev.eclipse.backrooms.portal.inside");
        }
        BackroomsState state = BackroomsState.get(server);
        if (state.phase() != BackroomsState.Phase.OPEN
                && state.phase() != BackroomsState.Phase.ANNOUNCED) {
            return Component.translatable("dev.eclipse.backrooms.stop.idle");
        }
        removeEntryPortal(server, state);
        ServerLevel level = (ServerLevel) operator.level();
        BlockPos base = operator.blockPosition();
        BackroomsPortal.place(level, base);
        state.setPortal(level.dimension(), base);
        if (state.phase() == BackroomsState.Phase.ANNOUNCED) {
            state.setPhase(BackroomsState.Phase.OPEN);
            announcePortal(server); // first opening only — relocations stay silent
        }
        return null;
    }

    @Nullable
    public static Component portalRemove(MinecraftServer server) {
        BackroomsState state = BackroomsState.get(server);
        if (state.portalPos() == null) {
            return Component.translatable("dev.eclipse.backrooms.portal.none");
        }
        removeEntryPortal(server, state);
        return null;
    }

    /** Graceful stop = short grace window; {@code immediate} closes this tick. */
    @Nullable
    public static Component stop(MinecraftServer server, boolean immediate) {
        BackroomsState state = BackroomsState.get(server);
        if (state.phase() != BackroomsState.Phase.OPEN
                && state.phase() != BackroomsState.Phase.ANNOUNCED) {
            return Component.translatable("dev.eclipse.backrooms.stop.idle");
        }
        if (immediate) {
            beginClosing(server, state, ExitReason.CLOSED);
            return null;
        }
        long now = System.currentTimeMillis();
        long graceEnd = now + GRACEFUL_STOP_MILLIS;
        if (state.endsAtEpochMillis() > graceEnd) {
            state.setEndsAtEpochMillis(graceEnd); // quiet grace window (no chat, user decree)
        }
        return null;
    }

    /** {@code /dev backrooms time add|sub|set} — mutates {@code endsAt}, clamped ≥ now. */
    @Nullable
    public static Component timeMutate(MinecraftServer server, char mode, long durationMillis) {
        BackroomsState state = BackroomsState.get(server);
        if (state.phase() != BackroomsState.Phase.OPEN
                && state.phase() != BackroomsState.Phase.ANNOUNCED) {
            return null;
        }
        long now = System.currentTimeMillis();
        long oldRemaining = Math.max(0L, state.endsAtEpochMillis() - now);
        long newEndsAt = switch (mode) {
            case '+' -> state.endsAtEpochMillis() + durationMillis;
            case '-' -> state.endsAtEpochMillis() - durationMillis;
            default -> now + durationMillis;
        };
        state.setEndsAtEpochMillis(Math.max(now, newEndsAt));
        long newRemaining = Math.max(0L, state.endsAtEpochMillis() - now);
        totalWindowMillisHint = Math.max(totalWindowMillisHint, newRemaining);
        return Component.translatable("dev.eclipse.backrooms.time.changed",
                mmss(newRemaining), mmss(oldRemaining));
    }

    // ================================================================== closing

    /**
     * CLOSING (xbox choreography): everyone exits with full inventory, per-player shard +
     * Almond Water rewards land direct-to-inventory (EXIT-portal walkers upgraded), the
     * participation buff starts once, portals despawn, event mobs dissolve. The maze
     * itself stays — the next instance's stamp self-cleans over it.
     */
    private static void beginClosing(MinecraftServer server, BackroomsState state, ExitReason reason) {
        state.setPhase(BackroomsState.Phase.CLOSING);

        for (ServerPlayer player : insidePlayers(server)) {
            exitToAnchor(server, state, player, reason == ExitReason.CLOSED
                    ? ExitReason.CLOSED : ExitReason.TIME_UP);
        }

        Set<UUID> participants = state.participantsSnapshot();
        if (!participants.isEmpty() && state.markRewardGranted()) {
            grantRewards(server, state, participants);
        }

        removeEntryPortal(server, state);
        removeExitPortal(server, state);
        despawnEventMobs(server);

        removeBossBar();
        PENDING_LEAVE_CONFIRMS.clear();
        LAST_BOUNCE_MESSAGE.clear();
        BackroomsDread.reset();
        state.setPhase(BackroomsState.Phase.IDLE);
        EclipseMod.LOGGER.info("Backrooms event closed (instance {}, {} participants)",
                state.instanceId(), participants.size());
    }

    private static void grantRewards(MinecraftServer server, BackroomsState state, Set<UUID> participants) {
        for (UUID uuid : participants) {
            ServerPlayer player = server.getPlayerList().getPlayer(uuid);
            if (player == null) {
                continue; // offline: items only land for online participants (xbox law)
            }
            boolean upgraded = state.isExitUpgraded(uuid);
            int shards = upgraded ? REWARD_SHARDS_UPGRADED : REWARD_SHARDS_BASE;
            giveOrDrop(player, new ItemStack(EclipseItems.UMBRAL_SHARD.get(), shards));
            giveOrDrop(player, BackroomsMaze.almondWater());
        }
        boolean started = TimedBuffApi.Holder.get().start(server, REWARD_BUFF_ID, REWARD_BUFF_MINUTES);
        if (!started) {
            EclipseMod.LOGGER.warn("Backrooms participation reward '{}' ({} min) was refused "
                    + "or TimedBuffApi is not installed", REWARD_BUFF_ID, REWARD_BUFF_MINUTES);
        }
    }

    private static void giveOrDrop(ServerPlayer player, ItemStack stack) {
        if (!player.getInventory().add(stack)) {
            player.drop(stack, false);
        }
    }

    private static void removeEntryPortal(MinecraftServer server, BackroomsState state) {
        BlockPos portalPos = state.portalPos();
        ResourceKey<Level> portalDim = state.portalDimension();
        if (portalPos == null || portalDim == null) {
            return;
        }
        ServerLevel level = server.getLevel(portalDim);
        if (level != null) {
            BackroomsPortal.remove(level, portalPos);
        }
        state.setPortal(null, null);
    }

    private static void removeExitPortal(MinecraftServer server, BackroomsState state) {
        BlockPos exitPos = state.exitPortalPos();
        if (exitPos == null) {
            return;
        }
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level != null) {
            BackroomsPortal.remove(level, exitPos);
        }
        state.setExitPortalPos(null);
    }

    /** Dissolves Wanderers + cameo Others left in the dimension (no drops, quiet poof). */
    private static void despawnEventMobs(MinecraftServer server) {
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null) {
            return;
        }
        List<Entity> doomed = new java.util.ArrayList<>();
        for (Entity entity : level.getAllEntities()) {
            if ((entity instanceof GlitchedWandererEntity || entity instanceof TheOtherEntity)
                    && entity.isAlive()) {
                doomed.add(entity);
            }
        }
        for (Entity entity : doomed) {
            level.sendParticles(ParticleTypes.REVERSE_PORTAL,
                    entity.getX(), entity.getY() + 1.0D, entity.getZ(),
                    10, 0.3D, 0.5D, 0.3D, 0.02D);
            entity.discard();
        }
    }

    // ================================================================== portals & entries

    private static void tickEntryPortal(MinecraftServer server, BackroomsState state) {
        BlockPos portalPos = state.portalPos();
        ResourceKey<Level> portalDim = state.portalDimension();
        if (portalPos == null || portalDim == null) {
            return;
        }
        ServerLevel level = server.getLevel(portalDim);
        if (level == null) {
            return;
        }
        BackroomsPortal.ambientTick(level, portalPos, level.getGameTime());
        var box = BackroomsPortal.collisionBox(portalPos);
        for (ServerPlayer player : List.copyOf(level.players())) {
            if (!player.isSpectator() && player.isAlive() && box.intersects(player.getBoundingBox())) {
                tryEnter(server, state, player);
            }
        }
    }

    private static void tryEnter(MinecraftServer server, BackroomsState state, ServerPlayer player) {
        if (state.phase() != BackroomsState.Phase.OPEN) {
            return;
        }
        UUID uuid = player.getUUID();
        if (state.isLockedOut(uuid)) {
            long now = System.currentTimeMillis();
            long last = LAST_BOUNCE_MESSAGE.getOrDefault(uuid, 0L);
            if (now - last >= BOUNCE_MESSAGE_THROTTLE_MILLIS) {
                LAST_BOUNCE_MESSAGE.put(uuid, now);
                // Quiet bounce (user decree: no chat) — the refusal sound carries the read.
                player.playNotifySound(SoundEvents.VILLAGER_NO, SoundSource.PLAYERS, 0.8F, 1.0F);
            }
            return;
        }
        enter(server, state, player);
    }

    /** Entry sequence: anchor → no-clip transition → teleport to the spawn cross (quiet). */
    private static void enter(MinecraftServer server, BackroomsState state, ServerPlayer player) {
        ServerLevel target = server.getLevel(BackroomsDimension.BACKROOMS);
        if (target == null) {
            return;
        }
        state.putReturnAnchor(player.getUUID(), new BackroomsState.ReturnAnchor(
                player.level().dimension(), player.getX(), player.getY(), player.getZ(),
                player.getYRot(), player.getXRot()));

        BackroomsPayloads.sendPortalTransition(player);

        BlockPos spawn = BackroomsMaze.cellCenter(BackroomsMaze.SPAWN_CELL, BackroomsMaze.SPAWN_CELL);
        player.teleportTo(target, spawn.getX() + 0.5D, spawn.getY(), spawn.getZ() + 0.5D,
                player.getYRot(), 0.0F);
        player.fallDistance = 0.0F;

        state.addParticipant(player.getUUID());
        state.recordEntry(player.getUUID(), System.currentTimeMillis());

        // User decree: no title/subtitle, no leave-hint chat — only the glitch sting.
        player.playNotifySound(EclipseSounds.UI_ERROR_GLITCH.get(), SoundSource.PLAYERS, 0.7F, 0.8F);
        EclipseMod.LOGGER.info("{} no-clipped into the backrooms (instance {})",
                player.getScoreboardName(), state.instanceId());
    }

    /**
     * Exit sequence: transition cover → teleport to the SANCTUM ALTAR (user decree — never
     * back to the portal). Pre-sanctum saves fall back to the captured anchor, then world
     * spawn. Quiet: no exit chat line ({@code reason} kept for the log/lockout call sites).
     */
    private static void exitToAnchor(MinecraftServer server, BackroomsState state,
            ServerPlayer player, ExitReason reason) {
        BackroomsPayloads.sendPortalTransition(player);

        ServerLevel overworld = server.overworld();
        BlockPos altar = EclipseWorldState.get(server).getSanctumAltarPos();
        boolean landedAtAltar = false;
        if (altar != null) {
            // Land on the plaza surface diagonally beside the altar (clear of the pillars).
            int x = altar.getX() + 2;
            int z = altar.getZ() + 2;
            int y = overworld.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, x, z);
            // EVAL2-C P-2 (the F-109 / W5-B6 void class): on an unloaded chunk getHeight()
            // returns the min build height — teleporting there is the void-column death
            // loop. Today the altar sits in the always-loaded spawn chunks, but that
            // implicit cover breaks with spawnChunkRadius=0 or a relocated altar, so the
            // sentinel gate is explicit; invalid Y falls through to anchor/world spawn.
            if (y > overworld.getMinBuildHeight()) {
                float yaw = (float) (Math.toDegrees(Math.atan2(
                        altar.getZ() + 0.5D - (z + 0.5D), altar.getX() + 0.5D - (x + 0.5D))) - 90.0D);
                player.teleportTo(overworld, x + 0.5D, y, z + 0.5D, yaw, 0.0F);
                landedAtAltar = true;
            } else {
                EclipseMod.LOGGER.warn(
                        "Backrooms exit: altar plaza at ({}, {}) has no loaded surface (heightmap {}), "
                                + "falling back to return anchor / world spawn for {}",
                        x, z, y, player.getScoreboardName());
            }
        }
        if (!landedAtAltar) {
            BackroomsState.ReturnAnchor anchor = state.returnAnchor(player.getUUID());
            ServerLevel target = anchor == null ? null : server.getLevel(anchor.dimension());
            if (target != null) {
                player.teleportTo(target, anchor.x(), anchor.y(), anchor.z(),
                        anchor.yaw(), anchor.pitch());
            } else {
                BlockPos spawn = overworld.getSharedSpawnPos();
                player.teleportTo(overworld, spawn.getX() + 0.5D, spawn.getY(), spawn.getZ() + 0.5D,
                        overworld.getSharedSpawnAngle(), 0.0F);
            }
        }
        player.fallDistance = 0.0F;
        state.removeReturnAnchor(player.getUUID());
        PENDING_LEAVE_CONFIRMS.remove(player.getUUID());
        BackroomsDread.forget(player.getUUID()); // the pursuit audio must not follow you out
        removeFromBossBar(player);
    }

    // ================================================================== inside tick

    /** 10 t housekeeping for the open maze: exit portal, bossbar, ambience, whispers. */
    private static void tickInside(MinecraftServer server, BackroomsState state, long remaining) {
        updateBossBar(server, state, remaining);
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null) {
            return;
        }

        // T-5:00: the EXIT sign hums to life (IDEAS §A5) — idempotent (pos persisted).
        if (remaining <= WARN_5M_MILLIS && state.exitPortalPos() == null) {
            spawnExitPortal(server, state, level);
        }

        BlockPos exitPos = state.exitPortalPos();
        if (exitPos != null) {
            BackroomsPortal.ambientTick(level, exitPos, level.getGameTime());
            BackroomsDread.tickExitBeacon(level, exitPos, level.getGameTime());
            var box = BackroomsPortal.collisionBox(exitPos);
            for (ServerPlayer player : List.copyOf(level.players())) {
                if (!player.isSpectator() && player.isAlive()
                        && box.intersects(player.getBoundingBox())) {
                    state.markExitUpgraded(player.getUUID());
                    exitToAnchor(server, state, player, ExitReason.EXIT_PORTAL);
                }
            }
        }

        BackroomsScare.tick(server, state, level);
        BackroomsDread.tick(level);
        tickAmbience(server, state, level);
    }

    /**
     * The EXIT sits on LEVEL 5 — deep in The Hollow (F-043). The Hollow is one wall-less
     * hall, so instead of a cell walk the pick is a hashed bearing/radius around the
     * origin, salted per instance ({@value #EXIT_MIN_RADIUS}–{@value #EXIT_MAX_RADIUS}
     * blocks out) and snapped clear of the pillar raster. Because that level is nearly
     * lightless, the portal gets the one thing the generator never gives it — a small
     * lantern ring — plus {@link BackroomsDread#tickExitBeacon}'s directional hum.
     */
    private static void spawnExitPortal(MinecraftServer server, BackroomsState state, ServerLevel level) {
        BlockPos best = findHollowExitSpot(state.mazeSeed());
        BackroomsPortal.place(level, best);
        lightExitPad(level, best);
        state.setExitPortalPos(best);
        // No chat (user decree) — the whisper caption overlay alone carries the EXIT cue.
        for (ServerPlayer player : insidePlayers(server)) {
            PacketDistributor.sendToPlayer(player, new S2CCaptionPayload(
                    "eclipse.backrooms.caption.exit", 80, S2CCaptionPayload.STYLE_WHISPER));
        }
    }

    /** Hashed point on The Hollow's walk plane, nudged out of the Säulenraster. */
    static BlockPos findHollowExitSpot(long pickSalt) {
        long hash = Long.rotateLeft(pickSalt ^ 0x0E217C0DEL, 17);
        double angle = Math.floorMod(hash, 3600L) / 3600.0D * Math.PI * 2.0D;
        double radius = EXIT_MIN_RADIUS
                + Math.floorMod(hash >>> 20, (long) (EXIT_MAX_RADIUS - EXIT_MIN_RADIUS) + 1L);
        int rawX = (int) Math.round(Math.cos(angle) * radius);
        int rawZ = (int) Math.round(Math.sin(angle) * radius);
        // Snap to the middle of a pillar bay — the raster occupies the first 2 of every 12.
        int spacing = BackroomsLayers.HOLLOW_PILLAR_SPACING;
        int x = Math.floorDiv(rawX, spacing) * spacing + spacing / 2;
        int z = Math.floorDiv(rawZ, spacing) * spacing + spacing / 2;
        return new BlockPos(x, BackroomsLayers.H_WALK_Y, z);
    }

    /**
     * The only guaranteed light on level 5: a four-lantern ring recessed into the floor
     * around the exit. ONE bounded write of four blocks at spawn time — never a sweep,
     * never per tick.
     */
    private static void lightExitPad(ServerLevel level, BlockPos base) {
        int floor = BackroomsLayers.H_BASE_TOP;
        int[][] offsets = {{3, 0}, {-3, 0}, {0, 3}, {0, -3}};
        for (int[] offset : offsets) {
            level.setBlock(new BlockPos(base.getX() + offset[0], floor, base.getZ() + offset[1]),
                    Blocks.SEA_LANTERN.defaultBlockState(), 3);
        }
    }

    /**
     * Layer-aware ambience — WET_ROOM / Poolrooms / Flooded Halls drips, The Hollow's
     * empty-cathedral rumble, the distant ballast clunk and the once-per-instance whisper
     * (IDEAS §A6) — plus the lazy per-instance loot fill of LOOT_ALCOVE barrels the player
     * walks near (the generator places them empty).
     */
    private static void tickAmbience(MinecraftServer server, BackroomsState state, ServerLevel level) {
        long now = System.currentTimeMillis();
        long seed = BackroomsMaze.worldSeed();
        for (ServerPlayer player : List.copyOf(level.players())) {
            BackroomsLayers.Layer layer = BackroomsLayers.layerOf(player.getBlockY());
            if (layer == BackroomsLayers.Layer.YELLOW_ROOMS) {
                int[] cell = BackroomsMaze.cellOf(player.blockPosition());
                if (BackroomsMaze.prefab(seed, cell[0], cell[1]) == BackroomsMaze.Prefab.WET_ROOM) {
                    BlockPos min = BackroomsMaze.cellMin(cell[0], cell[1]);
                    level.sendParticles(ParticleTypes.DRIPPING_WATER,
                            min.getX() + 1 + level.random.nextInt(6), BackroomsLayers.Y_CEIL - 0.2D,
                            min.getZ() + 1 + level.random.nextInt(6), 2, 0.4D, 0.0D, 0.4D, 0.0D);
                }
                fillNearbyLoot(level, state, seed, cell);
            } else if (layer == BackroomsLayers.Layer.POOLROOMS) {
                // The Poolrooms drip everywhere — the whole level is wet.
                level.sendParticles(ParticleTypes.DRIPPING_WATER,
                        player.getX() + level.random.nextInt(9) - 4, BackroomsLayers.P_CEIL - 0.2D,
                        player.getZ() + level.random.nextInt(9) - 4, 2, 0.4D, 0.0D, 0.4D, 0.0D);
            } else if (layer == BackroomsLayers.Layer.FLOODED_HALLS) {
                // Level 4 is defined by its dripping: heavier than the pool, and audible.
                level.sendParticles(ParticleTypes.DRIPPING_WATER,
                        player.getX() + level.random.nextInt(11) - 5, BackroomsLayers.F_CEIL - 0.2D,
                        player.getZ() + level.random.nextInt(11) - 5, 4, 0.5D, 0.0D, 0.5D, 0.0D);
                if (level.random.nextInt(4) == 0) {
                    player.playNotifySound(SoundEvents.POINTED_DRIPSTONE_DRIP_WATER,
                            SoundSource.AMBIENT, 0.5F, 0.7F + level.random.nextFloat() * 0.5F);
                }
            } else if (layer == BackroomsLayers.Layer.THE_HOLLOW) {
                // Level 5: nothing but the size of the room. A rare, very low swell.
                if (level.random.nextInt(24) == 0) {
                    player.playNotifySound(EclipseSounds.EVENT_ECLIPSE_DRONE.get(),
                            SoundSource.AMBIENT, 0.35F, 0.35F);
                }
            }
            // Distant ballast clunk (§A6.3): ~every 90 s per player, 20–30 blocks away.
            if (level.random.nextInt(180) == 0) {
                double angle = level.random.nextDouble() * Math.PI * 2.0D;
                double distance = 20.0D + level.random.nextDouble() * 10.0D;
                BlockPos clunk = player.blockPosition().offset(
                        (int) (Math.cos(angle) * distance), 0, (int) (Math.sin(angle) * distance));
                level.playSound(null, clunk, EclipseSounds.EVENT_BEAM_HUM.get(),
                        SoundSource.AMBIENT, 0.25F, 0.3F);
            }
            // WHISPER caption (§A6.5): rare, once per instance per player, after 3 min.
            long enteredAt = state.enteredAtEpochMillis(player.getUUID());
            if (enteredAt > 0L && now - enteredAt >= WHISPER_MIN_INSIDE_MILLIS
                    && level.random.nextInt(WHISPER_ODDS) == 0
                    && state.markWhispered(player.getUUID())) {
                PacketDistributor.sendToPlayer(player, new S2CCaptionPayload(
                        "eclipse.backrooms.whisper", 60, S2CCaptionPayload.STYLE_WHISPER));
            }
        }
    }

    /**
     * Fills any LOOT_ALCOVE barrel in the player's 3×3 cell neighborhood — once per
     * instance per cell, rolled with the per-instance loot seed. The generator places
     * the barrels EMPTY; this is the terrain-gen replacement for the stamp-time fill.
     */
    private static void fillNearbyLoot(ServerLevel level, BackroomsState state, long seed, int[] cell) {
        for (int dz = -1; dz <= 1; dz++) {
            for (int dx = -1; dx <= 1; dx++) {
                int cx = cell[0] + dx;
                int cz = cell[1] + dz;
                if (BackroomsMaze.prefab(seed, cx, cz) != BackroomsMaze.Prefab.LOOT_ALCOVE) {
                    continue;
                }
                BlockPos barrel = BackroomsMaze.lootBarrelPos(cx, cz);
                if (!level.getBlockState(barrel).is(Blocks.BARREL)) {
                    continue;
                }
                if (state.markLootFilled(BackroomsMaze.cellKey(cx, cz))) {
                    BackroomsMaze.fillLootBarrel(level, state.mazeSeed(), barrel, cx, cz);
                }
            }
        }
    }

    // ================================================================== flicker

    /**
     * Light-block flicker (IDEAS §A2): faulty froglight panels within
     * {@value #FLICKER_PLAYER_RANGE} blocks of a player swap to yellow glass during their
     * hashed dark window and back — REAL light changes, flag 3 (client relight). The
     * grid is infinite now, so the pass enumerates the cells AROUND each player on the
     * Yellow-Rooms layer instead of a global panel list.
     */
    private static void tickFlicker(MinecraftServer server, BackroomsState state) {
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null || level.players().isEmpty()) {
            return;
        }
        long seed = BackroomsMaze.worldSeed();
        long gameTime = level.getGameTime();
        int cellRange = (int) Math.ceil(FLICKER_PLAYER_RANGE / BackroomsMaze.CELL);
        Set<Long> visited = new java.util.HashSet<>();
        for (ServerPlayer player : level.players()) {
            if (BackroomsLayers.layerOf(player.getBlockY()) != BackroomsLayers.Layer.YELLOW_ROOMS) {
                continue;
            }
            int[] cell = BackroomsMaze.cellOf(player.blockPosition());
            for (int cz = cell[1] - cellRange; cz <= cell[1] + cellRange; cz++) {
                for (int cx = cell[0] - cellRange; cx <= cell[0] + cellRange; cx++) {
                    if (!visited.add(BackroomsMaze.cellKey(cx, cz))) {
                        continue;
                    }
                    for (BackroomsMaze.Panel panel : BackroomsMaze.panelsForCell(seed, cx, cz)) {
                        if (!panel.faulty()) {
                            continue;
                        }
                        boolean lit = BackroomsMaze.panelLitAt(seed, panel, gameTime);
                        var want = lit ? Blocks.OCHRE_FROGLIGHT.defaultBlockState()
                                : Blocks.YELLOW_STAINED_GLASS.defaultBlockState();
                        if (!level.getBlockState(panel.a()).is(want.getBlock())) {
                            level.setBlock(panel.a(), want, 3);
                            level.setBlock(panel.b(), want, 3);
                        }
                    }
                }
            }
        }
    }

    // ================================================================== mob budget

    /** Wanderer cap {@value #WANDERER_CAP} + 1–2 cameo Others (IDEAS §A3), every 5 s. */
    private static void tickSpawner(MinecraftServer server, BackroomsState state) {
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null || level.players().isEmpty() || !BackroomsEntities.GLITCHED_WANDERER.isBound()) {
            return;
        }
        long seed = BackroomsMaze.worldSeed();
        int wanderers = 0;
        int others = 0;
        for (Entity entity : level.getAllEntities()) {
            if (entity instanceof GlitchedWandererEntity) {
                wanderers++;
            } else if (entity instanceof TheOtherEntity) {
                others++;
            }
        }
        if (wanderers < WANDERER_CAP) {
            BlockPos pos = findMazeSpawn(level, seed, WANDERER_MIN_PLAYER_DISTANCE, 0.0D);
            if (pos != null && spawnMob(level, BackroomsEntities.GLITCHED_WANDERER.get(), pos)) {
                EclipseMod.LOGGER.debug("Wanderer {}/{} spawned at {}", wanderers + 1, WANDERER_CAP, pos);
            }
        }
        if (others < THE_OTHER_CAP) {
            BlockPos pos = findMazeSpawn(level, seed, WANDERER_MIN_PLAYER_DISTANCE,
                    THE_OTHER_MIN_SPAWN_DISTANCE);
            if (pos != null && spawnMob(level, EclipseEntities.THE_OTHER.get(), pos)) {
                EclipseMod.LOGGER.debug("The Other cameo spawned at {} (backrooms)", pos);
            }
        }
    }

    /**
     * Random cell center on the LAYER a random player is exploring (the grid is
     * infinite — candidates come from cells around players, always in loaded chunks):
     * ≥ {@code minPlayerDistance} from every player, ≥ {@code minSpawnDistance} from
     * the spawn cross, never ON the spawn cross and never over a drop shaft or drain.
     */
    @Nullable
    private static BlockPos findMazeSpawn(ServerLevel level, long seed,
            double minPlayerDistance, double minSpawnDistance) {
        List<ServerPlayer> players = level.players();
        if (players.isEmpty()) {
            return null;
        }
        BlockPos spawnCenter = BackroomsMaze.cellCenter(BackroomsMaze.SPAWN_CELL, BackroomsMaze.SPAWN_CELL);
        for (int attempt = 0; attempt < 16; attempt++) {
            ServerPlayer around = players.get(level.random.nextInt(players.size()));
            BackroomsLayers.Layer layer = BackroomsLayers.layerOf(around.getBlockY());
            int[] cell = BackroomsLayers.cellOf(layer, around.blockPosition());
            // ±64 blocks on every layer (the cell side differs per layer).
            int range = Math.max(2, 64 / BackroomsLayers.cellSize(layer));
            int cx = cell[0] + level.random.nextInt(range * 2 + 1) - range;
            int cz = cell[1] + level.random.nextInt(range * 2 + 1) - range;
            // Never spawn over a descent opening — the mob would just fall a level.
            // (THE_HOLLOW is one open hall: every bay center is valid.)
            if (isOverDescent(seed, layer, cx, cz)) {
                continue;
            }
            BlockPos center = BackroomsLayers.cellCenter(layer, cx, cz);
            if (minSpawnDistance > 0.0D
                    && center.distSqr(spawnCenter) < minSpawnDistance * minSpawnDistance) {
                continue;
            }
            if (level.getChunkSource().getChunkNow(center.getX() >> 4, center.getZ() >> 4) == null) {
                continue; // unloaded cell — never force a sync chunk load for a spawn
            }
            boolean tooClose = false;
            for (ServerPlayer player : players) {
                if (center.distToCenterSqr(player.getX(), player.getY(), player.getZ())
                        < minPlayerDistance * minPlayerDistance) {
                    tooClose = true;
                    break;
                }
            }
            // Level 4's walk plane IS water (knee-deep) — a water column is spawnable there.
            var standing = level.getBlockState(center);
            if (!tooClose && (standing.isAir() || (layer == BackroomsLayers.Layer.FLOODED_HALLS
                    && !standing.getFluidState().isEmpty()))) {
                return center;
            }
        }
        return null;
    }

    /** Whether the layer cell carries this level's descent opening (pit/drain/hatch/sink). */
    private static boolean isOverDescent(long seed, BackroomsLayers.Layer layer, int cx, int cz) {
        return switch (layer) {
            case YELLOW_ROOMS -> (cx == BackroomsMaze.SPAWN_CELL && cz == BackroomsMaze.SPAWN_CELL)
                    || BackroomsMaze.prefab(seed, cx, cz) == BackroomsMaze.Prefab.DROP_SHAFT;
            case POOLROOMS -> BackroomsLayers.isDrainCell(seed, cx, cz);
            case WAREHOUSE -> BackroomsLayers.isHatchCell(seed, cx, cz);
            case FLOODED_HALLS -> BackroomsLayers.isSinkCell(seed, cx, cz);
            case THE_HOLLOW -> false;
        };
    }

    private static boolean spawnMob(ServerLevel level, EntityType<? extends Mob> type, BlockPos pos) {
        Mob mob = type.create(level);
        if (mob == null) {
            return false;
        }
        mob.moveTo(pos.getX() + 0.5D, pos.getY(), pos.getZ() + 0.5D,
                level.random.nextFloat() * 360.0F, 0.0F);
        mob.setPersistenceRequired(); // event-managed lifecycle; despawned at CLOSING
        // User decree: backrooms mobs detect players within 20 blocks only. The Wanderer's
        // own attributes already carry the cap; the shared TheOtherEntity cameo (owned by
        // entity/) gets its follow range clamped per-spawn instead of a class edit.
        var followRange = mob.getAttribute(
                net.minecraft.world.entity.ai.attributes.Attributes.FOLLOW_RANGE);
        if (followRange != null
                && followRange.getBaseValue() > GlitchedWandererEntity.DETECTION_RANGE) {
            followRange.setBaseValue(GlitchedWandererEntity.DETECTION_RANGE);
        }
        return level.addFreshEntity(mob);
    }

    // ================================================================== death protection

    /**
     * Cancels player deaths inside the backrooms BEFORE the lives pipeline can run
     * (HIGHEST priority — no drops, no Eclipse life loss, no grave, no lockout; IDEAS §A5
     * "death costs nothing: you no-clipped back out").
     */
    @SubscribeEvent(priority = EventPriority.HIGHEST)
    public static void onLivingDeath(LivingDeathEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer player)
                || !BackroomsDimension.isInBackrooms(player)) {
            return;
        }
        event.setCanceled(true);
        player.setHealth(1.0F);
        player.setRemainingFireTicks(0);
        player.removeAllEffects();
        player.fallDistance = 0.0F;

        MinecraftServer server = player.server;
        BackroomsState state = BackroomsState.get(server);
        exitToAnchor(server, state, player, ExitReason.DEATH);
        EclipseMod.LOGGER.info("Protected backrooms death of {} ({}), returned to anchor",
                player.getScoreboardName(), event.getSource().getMsgId());
    }

    // ================================================================== login/logout edges

    /** Logout inside → the exit sequence runs at next login when the event is over. */
    @SubscribeEvent
    public static void onPlayerLoggedIn(PlayerEvent.PlayerLoggedInEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer player)) {
            return;
        }
        MinecraftServer server = player.server;
        BackroomsState state = BackroomsState.get(server);
        if (BackroomsDimension.isInBackrooms(player)) {
            if (state.phase() != BackroomsState.Phase.OPEN) {
                exitToAnchor(server, state, player, ExitReason.CLOSED);
            }
        } else if (state.returnAnchor(player.getUUID()) != null
                && state.phase() == BackroomsState.Phase.IDLE) {
            state.removeReturnAnchor(player.getUUID()); // stale leftover, already outside
        }
    }

    @SubscribeEvent
    public static void onPlayerLoggedOut(PlayerEvent.PlayerLoggedOutEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer player)) {
            return;
        }
        PENDING_LEAVE_CONFIRMS.remove(player.getUUID());
        LAST_BOUNCE_MESSAGE.remove(player.getUUID());
        BackroomsDread.forget(player.getUUID());
        removeFromBossBar(player);
    }

    // ================================================================== /backroomsleave

    /** First {@code /backroomsleave}: confirmation click-through; outside: polite no-op. */
    public static int leaveRequested(ServerPlayer player) {
        if (!BackroomsDimension.isInBackrooms(player)) {
            player.displayClientMessage(ServerLang.tr(player, "eclipse.backrooms.leave.outside")
                    .withStyle(ChatFormatting.GRAY), false);
            return 0;
        }
        PENDING_LEAVE_CONFIRMS.put(player.getUUID(),
                System.currentTimeMillis() + LEAVE_CONFIRM_WINDOW_MILLIS);
        MutableComponent confirm = ServerLang.tr(player, "eclipse.backrooms.leave.confirm")
                .withStyle(ChatFormatting.YELLOW);
        confirm.append(Component.literal(" "));
        confirm.append(ServerLang.tr(player, "eclipse.backrooms.leave.confirmbutton")
                .withStyle(Style.EMPTY.withColor(ChatFormatting.RED).withBold(true).withUnderlined(true)
                        .withClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND,
                                "/backroomsleave confirm"))
                        .withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT,
                                ServerLang.tr(player, "eclipse.backrooms.leave.confirm.hover")))));
        player.displayClientMessage(confirm, false);
        return 1;
    }

    /** {@code /backroomsleave confirm}: voluntary exit + lockout for THIS instance. */
    public static int leaveConfirmed(ServerPlayer player) {
        if (!BackroomsDimension.isInBackrooms(player)) {
            player.displayClientMessage(ServerLang.tr(player, "eclipse.backrooms.leave.outside")
                    .withStyle(ChatFormatting.GRAY), false);
            return 0;
        }
        Long window = PENDING_LEAVE_CONFIRMS.remove(player.getUUID());
        if (window == null || window < System.currentTimeMillis()) {
            return leaveRequested(player); // expired → re-ask instead of surprising the player
        }
        MinecraftServer server = player.server;
        BackroomsState state = BackroomsState.get(server);
        boolean activeEvent = state.phase() == BackroomsState.Phase.OPEN;
        if (activeEvent) {
            state.lockOut(player.getUUID());
        }
        exitToAnchor(server, state, player, ExitReason.LEFT);
        EclipseMod.LOGGER.info("{} voluntarily no-clipped out (locked out: {})",
                player.getScoreboardName(), activeEvent);
        return 1;
    }

    // ================================================================== timer & bossbar

    private static void updateBossBar(MinecraftServer server, BackroomsState state, long remaining) {
        List<ServerPlayer> inside = insidePlayers(server);
        if (inside.isEmpty() && bossBar == null) {
            return;
        }
        if (bossBar == null) {
            bossBar = new ServerBossEvent(Component.empty(),
                    BossEvent.BossBarColor.YELLOW, BossEvent.BossBarOverlay.PROGRESS);
        }
        bossBar.setName(Component.translatable("bossbar.eclipse.backrooms", mmss(remaining)));
        long total = Math.max(totalWindowMillisHint, 1L);
        bossBar.setProgress(Mth.clamp((float) remaining / total, 0.0F, 1.0F));

        for (ServerPlayer player : inside) {
            bossBar.addPlayer(player); // set-backed: no-op when already shown
        }
        for (ServerPlayer shown : List.copyOf(bossBar.getPlayers())) {
            if (!BackroomsDimension.isInBackrooms(shown)) {
                bossBar.removePlayer(shown);
            }
        }
    }

    private static void removeBossBar() {
        if (bossBar != null) {
            bossBar.removeAllPlayers();
            bossBar = null;
        }
    }

    private static void removeFromBossBar(ServerPlayer player) {
        if (bossBar != null) {
            bossBar.removePlayer(player);
        }
    }

    // ================================================================== helpers

    static List<ServerPlayer> insidePlayers(MinecraftServer server) {
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        return level == null ? List.of() : List.copyOf(level.players());
    }

    /**
     * The ONLY chat line the backrooms event may send (user decree): the shared
     * portal-opening announcement, baked per-recipient through {@link ServerLang#resolve}.
     */
    private static void announcePortal(MinecraftServer server) {
        broadcast(server, Component.translatable("eclipse.portal.announce.opening")
                .withStyle(ChatFormatting.GOLD));
    }

    /** Per-recipient broadcast baked through {@link ServerLang#resolve} (Wave-5 A1 law). */
    private static void broadcast(MinecraftServer server, Component message) {
        server.sendSystemMessage(message);
        for (ServerPlayer player : List.copyOf(server.getPlayerList().getPlayers())) {
            player.sendSystemMessage(ServerLang.resolve(player, message));
        }
    }

    /** {@code 29:59} — bossbar name and dev feedback. */
    public static String mmss(long millis) {
        long totalSeconds = Math.max(0L, millis / 1000L);
        return String.format(java.util.Locale.ROOT, "%02d:%02d", totalSeconds / 60L, totalSeconds % 60L);
    }

    // ---- status/dev support ----

    public static BackroomsState stateOf(MinecraftServer server) {
        return BackroomsState.get(server);
    }

    /**
     * {@code /dev backrooms tp <layer>} backing (F-043 verification): drops the operator
     * on the walk plane of one of the five levels, keeping their X/Z when they are already
     * inside and searching outward for a cell whose walk block is actually standable.
     * Purely a teleport — no participation, no anchor, no lockout bookkeeping.
     */
    @Nullable
    public static Component devTeleport(MinecraftServer server, ServerPlayer player,
            BackroomsLayers.Layer layer) {
        ServerLevel level = server.getLevel(BackroomsDimension.BACKROOMS);
        if (level == null) {
            return Component.translatable("dev.eclipse.backrooms.start.no_level",
                    BackroomsDimension.BACKROOMS.location().toString());
        }
        BlockPos anchor = BackroomsDimension.isInBackrooms(player) ? player.blockPosition()
                : BackroomsMaze.cellCenter(BackroomsMaze.SPAWN_CELL, BackroomsMaze.SPAWN_CELL);
        int[] cell = BackroomsLayers.cellOf(layer, anchor);
        long seed = BackroomsMaze.worldSeed();
        BlockPos best = BackroomsLayers.cellCenter(layer, cell[0], cell[1]);
        search:
        for (int ring = 0; ring <= DEV_TP_SEARCH_RINGS; ring++) {
            for (int dz = -ring; dz <= ring; dz++) {
                for (int dx = -ring; dx <= ring; dx++) {
                    if (Math.max(Math.abs(dx), Math.abs(dz)) != ring) {
                        continue; // walk the ring, not the filled square
                    }
                    int cx = cell[0] + dx;
                    int cz = cell[1] + dz;
                    if (isOverDescent(seed, layer, cx, cz)) {
                        continue;
                    }
                    BlockPos candidate = BackroomsLayers.cellCenter(layer, cx, cz);
                    var standing = level.getBlockState(candidate);
                    if (standing.isAir() || !standing.getFluidState().isEmpty()) {
                        best = candidate;
                        break search;
                    }
                }
            }
        }
        player.teleportTo(level, best.getX() + 0.5D, best.getY(), best.getZ() + 0.5D,
                player.getYRot(), player.getXRot());
        player.fallDistance = 0.0F;
        return null;
    }

    /** {@code /dev backrooms flicker} backing — fires one blackout pulse on the caller. */
    public static void devFlicker(ServerPlayer player) {
        BackroomsDread.debugFlicker((ServerLevel) player.level(), player);
    }

    public static boolean isLockedOutNow(MinecraftServer server, Player player) {
        return BackroomsState.get(server).isLockedOut(player.getUUID());
    }
}
