package dev.projecteclipse.eclipse.backrooms;

import java.util.ArrayList;
import java.util.List;

import dev.projecteclipse.eclipse.registry.EclipseItems;
import dev.projecteclipse.eclipse.worldgen.DiscMapData;
import net.minecraft.core.BlockPos;
import net.minecraft.core.component.DataComponents;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.level.block.entity.BarrelBlockEntity;

/**
 * The Yellow-Rooms cell oracle (IDEAS-backrooms_finale §A1, terrain-gen edition): pure
 * hash-driven cell math over an INFINITE grid of 8×8-block cells — no global solver,
 * O(1) per cell, identical for a given seed. The old budgeted maze STAMP is gone: the
 * {@code eclipse:backrooms} dimension is now generated by {@link BackroomsChunkGenerator}
 * (FIVE stacked layers since F-043, see {@link BackroomsLayers}), and this class answers
 * the per-cell questions both the generator and {@code BackroomsEventService} ask about
 * the TOPMOST one.
 *
 * <ul>
 *   <li><b>Seed law:</b> the LAYOUT seed is per-world ({@link #worldSeed()} — terrain
 *       gen cannot re-roll per event instance); the per-instance
 *       {@link #mazeSeed(int)} now salts only the LOOT rolls, so barrels refill with
 *       fresh contents each instance.</li>
 *   <li><b>Bond percolation:</b> every shared edge between two adjacent cells opens iff
 *       {@code hash(seed, edge) % 100 < 58} — above the square-lattice threshold (0.5),
 *       so the open cluster spans the plane while sealed pockets still occur (closed
 *       walls get a hashed 1-block eye-level peep gap so you can see INTO pockets).</li>
 *   <li><b>Highways:</b> one hash-jittered lane per 8-cell band carves straight
 *       corridors — band 0 is PINNED to lane 0, so the spawn cell (0,0) always sits on
 *       a highway cross. Guaranteed reachability without a solver.</li>
 *   <li><b>Prefabs per cell</b> (hashed): CORRIDOR 40%, OFFICE 25%, PILLAR_HALL
 *       (double height) 12%, WET_ROOM 12%, DEAD_END_CLOSET 8%, LOOT_ALCOVE 3% — plus
 *       the terrain-gen {@code DROP_SHAFT} (3% of eligible cells): a rimmed 2×2 no-clip
 *       pit through the floor into the Poolrooms layer below.</li>
 * </ul>
 */
public final class BackroomsMaze {
    /** Blocks per cell side (7 interior + 1 shared wall line). */
    public static final int CELL = 8;
    /** Spawn cell coordinate (cell (0,0) sits on the pinned highway cross). */
    public static final int SPAWN_CELL = 0;
    /** Highway band size: one highway lane per {@value} rows/columns of cells. */
    public static final int HIGHWAY_BAND = 8;

    /** Per-instance seed salt (IDEAS §A1 verbatim). */
    private static final long SEED_SALT = 0xBAC2C0035EEDL;
    /** Bond-percolation open threshold, percent. */
    private static final int EDGE_OPEN_PERCENT = 58;
    /** Faulty light-panel share, percent (IDEAS §A2; halve to 3 if relight load bites). */
    private static final int FAULTY_PANEL_PERCENT = 6;
    /** DROP_SHAFT share of eligible (non-highway, non-spawn-adjacent) cells, percent. */
    private static final int DROP_SHAFT_PERCENT = 3;

    /** Cell prefab kinds, hashed per cell (IDEAS §A1 step 3 + the DROP_SHAFT pit). */
    public enum Prefab { CORRIDOR, OFFICE, PILLAR_HALL, WET_ROOM, DEAD_END_CLOSET, LOOT_ALCOVE, DROP_SHAFT }

    /** One ceiling light strip (2×1 froglight panel); {@code faulty} panels flicker. */
    public record Panel(BlockPos a, BlockPos b, boolean faulty) {}

    private BackroomsMaze() {}

    // ================================================================== seed & hashing

    /** Per-WORLD layout seed — the terrain function's input ({@code ECLIPSE_SEED ^ salt}). */
    public static long worldSeed() {
        return DiscMapData.ECLIPSE_SEED ^ SEED_SALT;
    }

    /** Per-instance loot seed ({@code ECLIPSE_SEED ^ salt ^ instanceId}) — barrel rolls only. */
    public static long mazeSeed(int instanceId) {
        return DiscMapData.ECLIPSE_SEED ^ SEED_SALT ^ (long) instanceId;
    }

    /** SplitMix64-style avalanche; the repo's stateless hash idiom. */
    private static long scramble(long x) {
        x ^= x >>> 33;
        x *= 0xFF51AFD7ED558CCDL;
        x ^= x >>> 33;
        x *= 0xC4CEB9FE1A85EC53L;
        x ^= x >>> 33;
        return x;
    }

    static long hash(long seed, long a, long b) {
        return scramble(seed ^ scramble(a * 0x9E3779B97F4A7C15L) ^ scramble(b * 0xC2B2AE3D27D4EB4FL));
    }

    static int hashPercent(long seed, long a, long b) {
        return (int) Math.floorMod(hash(seed, a, b), 100L);
    }

    // ================================================================== cell math

    static long cellKey(int cx, int cz) {
        return ((long) cx << 32) | (cz & 0xFFFFFFFFL);
    }

    /**
     * Whether cell row {@code cz} is a highway row: one lane per {@value #HIGHWAY_BAND}-row
     * band, hash-jittered within the band; band 0 is PINNED to lane 0 (the spawn cross).
     */
    public static boolean isHighwayRow(long seed, int cz) {
        int band = Math.floorDiv(cz, HIGHWAY_BAND);
        int lane = band == 0 ? 0 : (int) Math.floorMod(hash(seed, 0x11L, band), HIGHWAY_BAND);
        return Math.floorMod(cz, HIGHWAY_BAND) == lane;
    }

    /** Whether cell column {@code cx} is a highway column (same law, separate salt). */
    public static boolean isHighwayCol(long seed, int cx) {
        int band = Math.floorDiv(cx, HIGHWAY_BAND);
        int lane = band == 0 ? 0 : (int) Math.floorMod(hash(seed, 0x22L, band), HIGHWAY_BAND);
        return Math.floorMod(cx, HIGHWAY_BAND) == lane;
    }

    public static boolean isHighwayCell(long seed, int cx, int cz) {
        return isHighwayRow(seed, cz) || isHighwayCol(seed, cx);
    }

    /**
     * Whether the shared edge between (cx,cz) and its +X neighbor is OPEN. Highway rows
     * force their east-west run open; otherwise bond percolation at 58%.
     */
    public static boolean edgeOpenEast(long seed, int cx, int cz) {
        if (isHighwayRow(seed, cz)) {
            return true;
        }
        return hashPercent(seed, cellKey(cx, cz), cellKey(cx + 1, cz) ^ 0xEA57L) < EDGE_OPEN_PERCENT;
    }

    /** Whether the shared edge between (cx,cz) and its +Z neighbor is OPEN. */
    public static boolean edgeOpenSouth(long seed, int cx, int cz) {
        if (isHighwayCol(seed, cx)) {
            return true;
        }
        return hashPercent(seed, cellKey(cx, cz), cellKey(cx, cz + 1) ^ 0x50D7L) < EDGE_OPEN_PERCENT;
    }

    /**
     * Hashed prefab pick; the spawn cell and highway cells read as plain corridor.
     * DROP_SHAFT (the descent pit to the Poolrooms) rolls first on eligible cells —
     * never within 2 cells of the spawn cross, so fresh entrants cannot step into a pit.
     */
    public static Prefab prefab(long seed, int cx, int cz) {
        if ((cx == SPAWN_CELL && cz == SPAWN_CELL) || isHighwayCell(seed, cx, cz)) {
            return Prefab.CORRIDOR;
        }
        if ((Math.abs(cx) > 2 || Math.abs(cz) > 2)
                && hashPercent(seed, cellKey(cx, cz), 0xD209L) < DROP_SHAFT_PERCENT) {
            return Prefab.DROP_SHAFT;
        }
        int roll = hashPercent(seed, cellKey(cx, cz), 0x9EFAL);
        if (roll < 40) {
            return Prefab.CORRIDOR;
        } else if (roll < 65) {
            return Prefab.OFFICE;
        } else if (roll < 77) {
            return Prefab.PILLAR_HALL;
        } else if (roll < 89) {
            return Prefab.WET_ROOM;
        } else if (roll < 97) {
            return Prefab.DEAD_END_CLOSET;
        }
        return Prefab.LOOT_ALCOVE;
    }

    /** Ceiling Y of a cell (double height only for PILLAR_HALL). */
    public static int ceilY(long seed, int cx, int cz) {
        return prefab(seed, cx, cz) == Prefab.PILLAR_HALL
                ? BackroomsLayers.Y_CEIL_TALL : BackroomsLayers.Y_CEIL;
    }

    /** World min corner (block coords, floor Y) of a cell. */
    public static BlockPos cellMin(int cx, int cz) {
        return new BlockPos(cx * CELL, BackroomsLayers.Y_FLOOR, cz * CELL);
    }

    /** Interior center of a cell at floor-walk height (player teleport target). */
    public static BlockPos cellCenter(int cx, int cz) {
        return new BlockPos(cx * CELL + 3, BackroomsLayers.Y_WALK_Y, cz * CELL + 3);
    }

    /** Cell coords of a world position (the grid is infinite — always resolves). */
    public static int[] cellOf(BlockPos pos) {
        return new int[] {Math.floorDiv(pos.getX(), CELL), Math.floorDiv(pos.getZ(), CELL)};
    }

    // ================================================================== panels

    /**
     * Ceiling light panels of ONE cell: a 2×1 {@code ochre_froglight} strip at interior
     * offsets (2..3, 3); highway cells get a second strip at (2..3, 1). Faulty panels are
     * hashed at {@value #FAULTY_PANEL_PERCENT}% with same-cell adjacency rejection (no
     * two panels of one cell both faulty — photosensitivity guard, IDEAS §A2). The
     * flicker pass enumerates cells around players (the grid is infinite — there is no
     * global panel list any more).
     *
     * <p><b>F-042</b>: most cells no longer HAVE a lamp — the strip only exists where
     * {@link BackroomsLayers#yellowLampMain}/{@link BackroomsLayers#yellowLampHighway}
     * say so (40% density, ~4% inside a dead zone). Asking the generator's own predicates
     * is what keeps the flicker pass from turning a dead fixture into a working lamp.</p>
     */
    public static List<Panel> panelsForCell(long seed, int cx, int cz) {
        List<Panel> panels = new ArrayList<>(2);
        int ceil = ceilY(seed, cx, cz);
        BlockPos min = cellMin(cx, cz);
        BlockPos a1 = new BlockPos(min.getX() + 2, ceil, min.getZ() + 3);
        BlockPos b1 = new BlockPos(min.getX() + 3, ceil, min.getZ() + 3);
        boolean faulty1 = hashPercent(seed, a1.asLong(), 0xF11CL) < FAULTY_PANEL_PERCENT;
        if (BackroomsLayers.yellowLampMain(seed, cx, cz)) {
            panels.add(new Panel(a1, b1, faulty1));
        }
        if (BackroomsLayers.yellowLampHighway(seed, cx, cz)) {
            BlockPos a2 = new BlockPos(min.getX() + 2, ceil, min.getZ() + 1);
            BlockPos b2 = new BlockPos(min.getX() + 3, ceil, min.getZ() + 1);
            boolean faulty2 = !faulty1
                    && hashPercent(seed, a2.asLong(), 0xF11CL) < FAULTY_PANEL_PERCENT;
            panels.add(new Panel(a2, b2, faulty2));
        }
        return panels;
    }

    /**
     * Flicker schedule of a faulty panel (server clock): within each hashed period
     * (120–279 t) the panel is DARK for a hashed 3–6 t window — one cycle per period,
     * far under the 3-flashes/second photosensitivity ceiling.
     */
    public static boolean panelLitAt(long seed, Panel panel, long gameTime) {
        if (!panel.faulty()) {
            return true;
        }
        long h = hash(seed, panel.a().asLong(), 0x0FFL);
        long period = 120L + Math.floorMod(h, 160L);
        long phase = Math.floorMod(gameTime + Math.floorMod(h >>> 16, period), period);
        long darkLen = 3L + Math.floorMod(h >>> 32, 4L); // 3..6 t
        return phase >= darkLen;
    }

    // ================================================================== loot

    /** Barrel position of a LOOT_ALCOVE cell (the generator places the empty barrel). */
    public static BlockPos lootBarrelPos(int cx, int cz) {
        return new BlockPos(cx * CELL + 3, BackroomsLayers.Y_WALK_Y, cz * CELL + 3);
    }

    /**
     * LOOT_ALCOVE barrel loot (IDEAS §A5): Almond Water (re-skinned Regeneration potion —
     * the community in-joke and a mid-event heal), 1–2 glitch shards, rare wallpaper
     * trophy (yellow terracotta with a custom name). The generator places the barrel
     * EMPTY; the event service fills it lazily ONCE per instance with the per-instance
     * loot seed — natural one-shot semantics that refill each event.
     */
    public static void fillLootBarrel(ServerLevel level, long lootSeed, BlockPos pos, int cx, int cz) {
        if (!(level.getBlockEntity(pos) instanceof BarrelBlockEntity barrel)) {
            return;
        }
        barrel.clearContent();
        barrel.setItem(3, almondWater());
        int shards = 1 + hashPercent(lootSeed, cellKey(cx, cz), 0x10071L) % 2;
        barrel.setItem(5, new ItemStack(EclipseItems.GLITCH_SHARD.get(), shards));
        if (hashPercent(lootSeed, cellKey(cx, cz), 0x77A11L) < 20) {
            ItemStack wallpaper = new ItemStack(
                    net.minecraft.world.level.block.Blocks.STRIPPED_BAMBOO_BLOCK.asItem());
            wallpaper.set(DataComponents.CUSTOM_NAME,
                    Component.translatable("item.eclipse.yellow_wallpaper"));
            barrel.setItem(7, wallpaper);
        }
    }

    /** Almond Water — vanilla Regeneration potion aliased with the joke name. */
    public static ItemStack almondWater() {
        ItemStack stack = new ItemStack(Items.POTION);
        stack.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.REGENERATION));
        stack.set(DataComponents.CUSTOM_NAME, Component.translatable("item.eclipse.almond_water"));
        return stack;
    }
}
