package dev.projecteclipse.eclipse.sequence.endarrival;

import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;

/**
 * F-077 "Der Altar ruft das End" — logical FX cue ids for the End-arrival cinematic
 * ({@link EndArrivalSequence}). Declared HERE via {@link FxCues#cue} instead of as new
 * {@code FxCues.CUE_*} constants because {@code FxCues.java} is locked by the parallel
 * agent wave (see {@code docs/plans_v3/wiring/end_arrival_wiring.md}); the main agent may
 * fold these into {@code FxCues} afterwards. Wire format and namespace
 * ({@code eclipse:fx/cue/…}) are identical either way.
 *
 * <p>Client rows live in {@code veilfx/EndArrivalFxRows}; Photon assets are generated by
 * {@code tools/photon/end_arrival_fx.py} into {@code assets/eclipse/fx/end_arrival_*.fx}.
 * All cues ride the position lane ({@code FxPayloads.sendFxEvent}).</p>
 */
public final class EndArrivalFxCues {
    /** Phase 1 omen: violet in-fall streaks collapsing onto the altar. {@code a,b} unused. */
    public static final ResourceLocation CUE_SUCTION = FxCues.cue("end_arrival_suction");
    /** Phase 2 charge: energy rings climbing the altar column. {@code a,b} unused. */
    public static final ResourceLocation CUE_RINGS = FxCues.cue("end_arrival_rings");
    /**
     * Phases 2-3: the violet pillar, anchored at the ALTAR TOP. {@code a} = real pillar
     * height in blocks (altar top → rift mouth); the client row Y-scales the executor by
     * {@code a / 260} (the authored model height, see {@code end_arrival_fx.py}).
     */
    public static final ResourceLocation CUE_PILLAR = FxCues.cue("end_arrival_pillar");
    /** Phases 2-4: the giant End-rift maw, anchored at the rift point. {@code a,b} unused. */
    public static final ResourceLocation CUE_MAW = FxCues.cue("end_arrival_maw");
    /** Phase 3 garnish: Endergeist wisp streaks between the debris streams. {@code a,b} unused. */
    public static final ResourceLocation CUE_WISP = FxCues.cue("end_arrival_wisp");
    /** Phase 3: violet implosion puff where a debris chunk snaps into the island. {@code a,b} unused. */
    public static final ResourceLocation CUE_PUFF = FxCues.cue("end_arrival_puff");
    /** Phase 4: the rift-close implosion (flash + shock ring + shard scatter). {@code a,b} unused. */
    public static final ResourceLocation CUE_IMPLOSION = FxCues.cue("end_arrival_implosion");
    /**
     * Phase 4: the pillar dissolves into falling glitter, anchored at the ALTAR TOP.
     * {@code a} = real pillar height in blocks; the row Y-scales by {@code a / 240}.
     */
    public static final ResourceLocation CUE_GLITTER = FxCues.cue("end_arrival_glitter");

    // --- V2 "GIGANTISMUS" cues (PLAN-F077 §3; assets from tools/photon/end_arrival2_fx.py) ---

    /**
     * Beat-1 omen: the rune ring gathering in the sky over the altar (anchored at
     * altar top + 40; the ~80 t one-shot dies naturally ON the t = 160 erupt).
     * {@code a,b} unused.
     */
    public static final ResourceLocation CUE_GLYPHS = FxCues.cue("end_arrival_glyphs");
    /**
     * Beat-3: the comet-trail sheath around the three debris helix strands, anchored
     * at the ALTAR TOP. {@code a} = real pillar height in blocks; the row Y-scales by
     * {@code a / 260} (the {@code CUE_PILLAR} law).
     */
    public static final ResourceLocation CUE_STRAND_TRAIL = FxCues.cue("end_arrival_strand_trail");
    /**
     * Beat-3 wave stamp: the giant horizontal shock ring when an assembly wave
     * completes, anchored at the DISC CENTER (surface height). {@code a} = ring radius
     * in blocks; the row XZ-scales by {@code a / 60} (authored radius).
     */
    public static final ResourceLocation CUE_ISLAND_RING = FxCues.cue("end_arrival_island_ring");
    /**
     * Permanent: the subtle end-rift residue over the finished disc, anchored at disc
     * center + 40. Re-fired every 600 t by {@code worldgen/end/EndRiftAmbient} (the
     * ~660 t one-shot + dedup = a seamless ambient). {@code a,b} unused.
     */
    public static final ResourceLocation CUE_RIFT_AMBIENT = FxCues.cue("end_arrival_rift_ambient");
    /**
     * Beat-1/4 Veil grade lane (NOT a Photon row — an explicit {@code FxPayloads}
     * branch feeds {@code EclipseFxState.setArrivalDim}): {@code a} = dim target 0..1,
     * {@code b} = ramp ticks.
     */
    public static final ResourceLocation CUE_GRADE = FxCues.cue("end_arrival_grade");
    /**
     * Beat-4 Veil sky-pulse lane (explicit {@code FxPayloads} branch →
     * {@code EclipseFxState.setEndTintPulse}): {@code a} = pulse target 0..1,
     * {@code b} = ramp ticks.
     */
    public static final ResourceLocation CUE_TINT = FxCues.cue("end_arrival_tint");

    private EndArrivalFxCues() {}
}
