// swift-tools-version: 5.9
// Linux-runnable SwiftPM package covering the pure-logic (Foundation-only)
// subset of the SoooDreamy iOS app. The full app is built by XcodeGen from
// project.yml — this manifest exists ONLY so `swift test` can exercise the
// content packs, date helpers, seeded RNG and localization tables on Linux/CI.
// Do not add SwiftUI/UIKit files to `sources`.
import PackageDescription

let package = Package(
    name: "SoooDreamyLogic",
    // The app itself is iOS 26-only (see project.yml / docs/IOS-26.md);
    // ".v17"-style constants for 26 need newer tools, the string form works.
    platforms: [.macOS(.v14), .iOS("26.0")],
    products: [
        .library(name: "SoooDreamyLogic", targets: ["SoooDreamyLogic"])
    ],
    targets: [
        .target(
            name: "SoooDreamyLogic",
            path: ".",
            sources: [
                "SoooDreamy/Content/ContentModels.swift",
                "SoooDreamy/Content/DailyPinRules.swift",
                "SoooDreamy/Content/Data/DailyQuestionsData.swift",
                "SoooDreamy/Content/Data/QuizData.swift",
                "SoooDreamy/Content/Data/ThisOrThatData.swift",
                "SoooDreamy/Content/Data/WouldYouRatherData.swift",
                "SoooDreamy/Content/Data/TruthOrDareData.swift",
                "SoooDreamy/Content/Data/Questions36Data.swift",
                "SoooDreamy/Content/Data/DateIdeasData.swift",
                "SoooDreamy/Content/Data/WordleWordsData.swift",
                "SoooDreamy/Content/Data/EmojiRiddlesData.swift",
                "SoooDreamy/Content/Data/QuizDuelData.swift",
                "SoooDreamy/Content/Data/RelationshipSupportContent.swift",
                "SoooDreamy/Content/CoupleGamesLogic.swift",
                "SoooDreamy/Content/BattleshipLogic.swift",
                "SoooDreamy/Content/PictionaryLogic.swift",
                "SoooDreamy/Content/Data/PictionaryWordsData.swift",
                "SoooDreamy/Content/KniffelLogic.swift",
                "SoooDreamy/Content/MovieRouletteLogic.swift",
                "SoooDreamy/Content/Data/MovieRouletteData.swift",
                "SoooDreamy/Content/MovieNightLogic.swift",
                "SoooDreamy/Content/DashboardPriority.swift",
                "SoooDreamy/Content/DailyRevealLogic.swift",
                "SoooDreamy/Content/MissedInboxLogic.swift",
                "SoooDreamy/Content/AccessibilityBudget.swift",
                "SoooDreamy/Content/BackupContract.swift",
                "SoooDreamy/Content/RepairConversationLogic.swift",
                "SoooDreamy/Content/SeasonCalendarLogic.swift",
                "SoooDreamy/Content/GamesWaveLogic.swift",
                "SoooDreamy/Content/PersonalizationLogic.swift",
                "SoooDreamy/Content/PaperRules.swift",
                "SoooDreamy/Content/KartenschrankRules.swift",
                "SoooDreamy/Content/PolishAudit.swift",
                "SoooDreamy/Content/IntelligenceRules.swift",
                "SoooDreamy/Content/ChatLanguageRules.swift",
                "SoooDreamy/Content/CinematicScript.swift",
                "SoooDreamy/Content/CinematicManifest.swift",
                "SoooDreamy/Content/SurfaceState.swift",
                "SoooDreamy/Content/StadtLandFlussLogic.swift",
                "SoooDreamy/Content/TwoTruthsLogic.swift",
                "SoooDreamy/Content/DailyQuestsLogic.swift",
                "SoooDreamy/Content/TournamentLogic.swift",
                "SoooDreamy/Content/ReplayLogic.swift",
                "SoooDreamy/Content/TabBarLogic.swift",
                "SoooDreamy/Content/LayoutRules.swift",
                "SoooDreamy/Content/ZustellrundenLogic.swift",
                "SoooDreamy/Content/GameTableRules.swift",
                "SoooDreamy/Content/BoardGameRules.swift",
                "SoooDreamy/Content/GameDelightRules.swift",
                "SoooDreamy/Content/DelightArbiter.swift",
                "SoooDreamy/Content/PencilInputRules.swift",
                "SoooDreamy/Content/DraftContinuityRules.swift",
                "SoooDreamy/Content/WeekReviewLogic.swift",
                "SoooDreamy/Content/MemoriesLogic.swift",
                "SoooDreamy/Content/ArchivRules.swift",
                "SoooDreamy/Content/PresenceLogic.swift",
                "SoooDreamy/Content/RecoveryLogic.swift",
                "SoooDreamy/Content/OnboardingScript.swift",
                "SoooDreamy/Content/RejoinLink.swift",
                "SoooDreamy/Content/MultiDeviceRules.swift",
                "SoooDreamy/Content/GameLeaseRules.swift",
                "SoooDreamy/Content/GameTurnRules.swift",
                "SoooDreamy/Content/InboxMergeRules.swift",
                "SoooDreamy/Content/PostRules.swift",
                "SoooDreamy/Content/GameSecretRules.swift",
                "SoooDreamy/Content/PlayHubCuration.swift",
                "SoooDreamy/Content/BoardGameFeedbackRules.swift",
                "SoooDreamy/Content/GameIntroCatalog.swift",
                "SoooDreamy/Content/Data/DailyQuestsData.swift",
                "Shared/IconPaletteTable.swift",
                "Shared/SharedBridge.swift",
                "Shared/RevealedDailyStore.swift",
                "Shared/StrokeGeometry.swift",
                "Shared/WidgetStudio.swift",
                "Shared/WidgetReliability.swift",
                "Shared/LiveActivityConfig.swift",
                "Shared/LiveActivityLogic.swift",
                "Shared/TouchEmoji.swift",
                "SoooDreamy/Core/JSONValue.swift",
                "SoooDreamy/Core/APIErrorWire.swift",
                "SoooDreamy/Core/PendingInvite.swift",
                "SoooDreamy/Core/SeededRandom.swift",
                "SoooDreamy/Core/ExifDateParser.swift",
                "SoooDreamy/Core/CommitReveal.swift",
                "SoooDreamy/Core/HapticPatternKit.swift",
                "SoooDreamy/Core/AppCueCatalog.swift",
                "SoooDreamy/Core/SoundCreditsManifest.swift",
                "SoooDreamy/Core/DelightRules.swift",
                "SoooDreamy/Core/HandbookDocument.swift",
                "SoooDreamy/Core/LocalizedFormatters.swift",
                "SoooDreamy/Core/LevelMath.swift",
                "SoooDreamy/Core/SeasonLogic.swift",
                "SoooDreamy/Core/OfflineOutbox.swift",
                "SoooDreamy/Core/APIErrorHumanizer.swift",
                "SoooDreamy/Core/NotificationDamping.swift",
                "SoooDreamy/Core/PendingMediaStore.swift",
                "SoooDreamy/Core/VoiceCaptureLogic.swift",
                "SoooDreamy/Core/ReconnectBackoff.swift",
                "SoooDreamy/Core/CoreColdCache.swift",
                "SoooDreamy/Core/FIFOQueue.swift",
                "SoooDreamy/Core/L10n.swift",
                "SoooDreamy/Core/CoreStrings.swift",
                "SoooDreamy/Stationen/Schreibstube/ChatL10n.swift",
                "SoooDreamy/Stationen/Schreibstube/ChatSendeRegeln.swift",
                "SoooDreamy/Stationen/Spieltisch/GamesL10n.swift",
                "SoooDreamy/Stationen/Archiv/MemoriesL10n.swift",
                "SoooDreamy/Kino/OnboardingL10n.swift",
                "SoooDreamy/Stationen/Postfach/PlatformL10n.swift",
                "SoooDreamy/Stationen/Postfach/PostfachL10n.swift",
                "SoooDreamy/Zustelldienst/RitualsL10n.swift",
                "SoooDreamy/Stationen/Amt/IntelligenceL10n.swift",
                "SoooDreamy/Stationen/Amt/SettingsL10n.swift"
            ]
        ),
        .testTarget(
            name: "SoooDreamyLogicTests",
            dependencies: ["SoooDreamyLogic"],
            path: "LogicTests"
        )
    ]
)
