// Eingebauter Schätzfragen-Pool v0 — der Content-Loader kennt noch keine
// `schaetz`-Fragen (shared/content.ts ist choice4-only). Sobald der Content-Agent
// das Pack-Format erweitert, ersetzt der ContentSlice diesen Pool (siehe init()).
// Werte-Regeln aus CONTENT-PLAN §5.6: Richtwert NICHT in der Mitte der Spanne,
// Spanne mindestens Faktor 4, log-Skala bei großen Spannen.
import type { TresorFrage } from "../../../shared/minigames/bananen-tresor.meta";

export const TRESOR_FRAGEN: readonly TresorFrage[] = [
  {
    id: "tresor_eiffelturm",
    text: "Wie hoch ist der Eiffelturm (mit Antennen, in Metern)?",
    einheit: "m",
    richtwert: 330,
    eingabeMin: 50,
    eingabeMax: 1000,
    skala: "linear",
    variante: "standard",
    erklaerung: "330 Meter — seit der neuen Antenne von 2022 sechs Meter höher als davor.",
  },
  {
    id: "tresor_rhein",
    text: "Wie lang ist der Rhein (in Kilometern)?",
    einheit: "km",
    richtwert: 1233,
    eingabeMin: 300,
    eingabeMax: 4000,
    skala: "linear",
    variante: "standard",
    erklaerung: "1.233 km von den Alpen bis zur Nordsee — lange galt fälschlich 1.320 km.",
  },
  {
    id: "tresor_knochen",
    text: "Wie viele Knochen hat ein erwachsener Mensch?",
    einheit: "Knochen",
    richtwert: 206,
    eingabeMin: 50,
    eingabeMax: 800,
    skala: "linear",
    variante: "standard",
    erklaerung: "206 — Babys starten mit über 300, viele verwachsen beim Wachsen.",
  },
  {
    id: "tresor_klavier",
    text: "Wie viele Tasten hat ein klassisches Klavier?",
    einheit: "Tasten",
    richtwert: 88,
    eingabeMin: 20,
    eingabeMax: 200,
    skala: "linear",
    variante: "standard",
    erklaerung: "88 Tasten: 52 weiße und 36 schwarze — Standard seit Ende des 19. Jahrhunderts.",
  },
  {
    id: "tresor_uno",
    text: "Wie viele Mitgliedstaaten hat die UNO?",
    einheit: "Staaten",
    richtwert: 193,
    eingabeMin: 50,
    eingabeMax: 400,
    skala: "linear",
    variante: "standard",
    erklaerung: "193 Mitgliedstaaten — Südsudan kam 2011 als bisher letzter dazu.",
  },
  {
    id: "tresor_eiffel_jahr",
    text: "In welchem Jahr wurde der Eiffelturm fertiggestellt?",
    einheit: "Jahr",
    richtwert: 1889,
    eingabeMin: 1700,
    eingabeMax: 2000,
    skala: "linear",
    variante: "standard",
    erklaerung: "1889, pünktlich zur Weltausstellung in Paris — geplant nur für 20 Jahre.",
  },
  {
    id: "tresor_mond",
    text: "Wie weit ist der Mond im Schnitt von der Erde entfernt (in Kilometern)?",
    einheit: "km",
    richtwert: 384400,
    eingabeMin: 10000,
    eingabeMax: 10000000,
    skala: "log",
    variante: "hard",
    erklaerung: "Rund 384.400 km — Licht braucht dafür etwa 1,3 Sekunden.",
  },
  {
    id: "tresor_mauer",
    text: "Wie lang ist die Chinesische Mauer mit allen Abschnitten (offiziell, in Kilometern)?",
    einheit: "km",
    richtwert: 21196,
    eingabeMin: 1000,
    eingabeMax: 100000,
    skala: "log",
    variante: "hard",
    erklaerung: "21.196 km laut offizieller Vermessung von 2012 — inklusive aller Nebenäste.",
  },
  {
    id: "tresor_marianen",
    text: "Wie tief ist der tiefste Punkt des Meeres (Marianengraben, in Metern)?",
    einheit: "m",
    richtwert: 10935,
    eingabeMin: 2000,
    eingabeMax: 50000,
    skala: "log",
    variante: "hard",
    erklaerung: "Rund 10.935 m — der Mount Everest würde komplett darin versinken.",
  },
  {
    id: "tresor_island",
    text: "Wie viele Einwohner hat Island (gerundet)?",
    einheit: "Einwohner",
    richtwert: 390000,
    eingabeMin: 50000,
    eingabeMax: 5000000,
    skala: "log",
    variante: "standard",
    erklaerung: "Rund 390.000 — weniger als Bochum, auf einer Insel größer als Portugal.",
  },
];
