/**
 * Syncs ../assets → public/assets so Remotion can serve them via staticFile(),
 * and generates src/lib/manifest.generated.ts containing:
 *   - assetFiles: list of all synced files (relative, posix-style paths)
 *   - beatGridJson: the parsed contents of assets/music/beat_grid.json (or null)
 *
 * Runs automatically via npm pre-scripts (prestudio, prerender:*, postinstall).
 * Never fails hard: missing source dirs just produce an empty manifest so the
 * compositions can fall back to color planes.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const remotionRoot = path.resolve(__dirname, '..');
const assetsSrc = path.resolve(remotionRoot, '..', 'assets');
const publicDst = path.resolve(remotionRoot, 'public', 'assets');
const manifestPath = path.resolve(remotionRoot, 'src', 'lib', 'manifest.generated.ts');

// blender/ contains heavy work files that must not end up in the bundle.
const SYNC_DIRS = ['images', 'music', 'renders', 'fonts'];

const toPosix = (p) => p.split(path.sep).join('/');

const listFilesRecursive = (dir, base = dir) => {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFilesRecursive(abs, base));
    } else if (entry.isFile() && !entry.name.startsWith('.')) {
      out.push(toPosix(path.relative(base, abs)));
    }
  }
  return out;
};

let copied = 0;
let removed = 0;
const manifestFiles = [];

for (const dirName of SYNC_DIRS) {
  const srcDir = path.join(assetsSrc, dirName);
  const dstDir = path.join(publicDst, dirName);
  const srcFiles = listFilesRecursive(srcDir);
  const dstFiles = listFilesRecursive(dstDir);
  const srcSet = new Set(srcFiles);

  // Remove stale files that no longer exist in the source.
  for (const rel of dstFiles) {
    if (!srcSet.has(rel)) {
      fs.rmSync(path.join(dstDir, rel));
      removed++;
    }
  }

  for (const rel of srcFiles) {
    const srcFile = path.join(srcDir, rel);
    const dstFile = path.join(dstDir, rel);
    const srcStat = fs.statSync(srcFile);
    let needsCopy = true;
    if (fs.existsSync(dstFile)) {
      const dstStat = fs.statSync(dstFile);
      needsCopy = srcStat.size !== dstStat.size || srcStat.mtimeMs > dstStat.mtimeMs;
    }
    if (needsCopy) {
      fs.mkdirSync(path.dirname(dstFile), {recursive: true});
      fs.copyFileSync(srcFile, dstFile);
      copied++;
    }
    manifestFiles.push(`${dirName}/${rel}`);
  }
}

fs.mkdirSync(publicDst, {recursive: true});
manifestFiles.sort();

// Embed beat_grid.json (if present) so src/lib/beats.ts can read it synchronously.
let beatGrid = null;
const beatGridPath = path.join(assetsSrc, 'music', 'beat_grid.json');
if (fs.existsSync(beatGridPath)) {
  try {
    beatGrid = JSON.parse(fs.readFileSync(beatGridPath, 'utf8'));
  } catch (err) {
    console.warn(`[sync-assets] WARN: could not parse ${beatGridPath}: ${err.message}`);
  }
}

const manifestSource = `// AUTO-GENERATED by scripts/sync-assets.mjs — DO NOT EDIT.
// Regenerate with: npm run sync-assets

/** All files available under public/assets/, relative posix paths. */
export const assetFiles: readonly string[] = ${JSON.stringify(manifestFiles, null, 2)};

/** Parsed contents of assets/music/beat_grid.json, or null if absent/invalid. */
export const beatGridJson: unknown = ${beatGrid === null ? 'null' : JSON.stringify(beatGrid, null, 2)};
`;

fs.mkdirSync(path.dirname(manifestPath), {recursive: true});
const previous = fs.existsSync(manifestPath) ? fs.readFileSync(manifestPath, 'utf8') : null;
if (previous !== manifestSource) {
  fs.writeFileSync(manifestPath, manifestSource);
}

if (!fs.existsSync(assetsSrc)) {
  console.warn(`[sync-assets] WARN: ${assetsSrc} does not exist — wrote empty manifest.`);
}
console.log(
  `[sync-assets] ${manifestFiles.length} assets in manifest (${copied} copied, ${removed} stale removed), beat_grid.json: ${beatGrid ? 'found' : 'absent (fallback grid will be used)'}`,
);
