package dev.projecteclipse.eclipse.woah.resonance.client;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.core.config.EclipseClientConfig;
import dev.projecteclipse.eclipse.veilfx.FxBudget;
import dev.projecteclipse.eclipse.veilfx.PhotonBridge;
import dev.projecteclipse.eclipse.veilfx.VeilPostController;
import dev.projecteclipse.eclipse.woah.resonance.ResonanceMelodyMachine;
import foundry.veil.api.client.render.VeilRenderSystem;
import foundry.veil.api.client.render.light.data.PointLightData;
import foundry.veil.api.client.render.light.renderer.LightRenderHandle;
import foundry.veil.api.client.render.post.PostPipeline;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientPlayerNetworkEvent;
import net.neoforged.neoforge.client.event.ClientTickEvent;

/**
 * WOAH-04 §4.3–§4.6 — the client FX controller: per-crystal Photon aura loops,
 * per-edge light-path ("Bahn") loops, the 160–400-block far-LOD (hair-thin HDR
 * shafts + the 8-second sky pulse), the ≤2 idle Veil point lights, the finale light
 * and the optional post shimmer envelope.
 *
 * <p>Per-anchor loops deliberately do NOT run over registry loop rows (the
 * {@code STORM_CROWN_HALO} "not a registry row" law): this controller owns raw
 * {@link PhotonBridge.LoopHandle}s with hysteresis windows and releases them on
 * reducedFx / dimension change / logout (WINDOWED-loop law). Field quota:
 * ≤ {@value #MAX_FIELD_HANDLES} of {@code PhotonBridge.MAX_LIVE_EXECUTORS} = 24 —
 * the controller counts its OWN handles and refuses above the quota (§8).</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT)
public final class ResonanceFieldFx {
    // --- Photon asset ids (generated by tools/photon/resonance_fx.py) ---
    static final ResourceLocation FX_CRYSTAL_AURA = fx("resonance_crystal_aura");
    static final ResourceLocation FX_BAHN = fx("resonance_bahn");
    static final ResourceLocation FX_FAR_SHAFT = fx("resonance_far_shaft");
    static final ResourceLocation FX_FAR_PULSE = fx("resonance_far_pulse");

    /** Veil post pipeline id (§4.6; pinwheel/post/resonance_shimmer.json). */
    public static final ResourceLocation SHIMMER_POST =
            ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, "resonance_shimmer");

    // --- §8 budgets + hysteresis windows (engage/release) ---
    private static final int MAX_FIELD_HANDLES = 12;
    private static final int MAX_AURAS = 4;
    private static final double AURA_ENGAGE = 56.0D;
    private static final double AURA_RELEASE = 64.0D;
    private static final int MAX_BAHNEN = 6;
    private static final double BAHN_ENGAGE = 64.0D;
    private static final double BAHN_RELEASE = 72.0D;
    private static final int MAX_FAR_SHAFTS = 4;
    private static final double FAR_ENGAGE_MIN = 160.0D;
    private static final double FAR_RELEASE_MIN = 150.0D;
    private static final double FAR_ENGAGE_MAX = 400.0D;
    private static final double FAR_RELEASE_MAX = 420.0D;

    // --- §4.5 point lights ---
    private static final int MAX_IDLE_LIGHTS = 2;
    private static final double LIGHT_ENGAGE = 40.0D;
    private static final double LIGHT_RELEASE = 48.0D;
    private static final float LIGHT_RADIUS = 18.0F;
    /** skyDarken ≥ 9 ≙ night (vanilla darkens 0–11). */
    private static final int NIGHT_SKY_DARKEN = 9;
    private static final float FINALE_LIGHT_RADIUS = 40.0F;

    // --- §4.6 shimmer ---
    private static final float STRIKE_SHIMMER_PEAK = 0.35F;
    private static final int STRIKE_SHIMMER_TICKS = 12;
    private static final double STRIKE_SHIMMER_RANGE = 16.0D;
    private static final float FINALE_SHIMMER_PEAK = 0.6F;
    private static final int FINALE_SHIMMER_TICKS = 40;
    private static final double FINALE_SHIMMER_RANGE = 48.0D;

    /** COOLDOWN dim: the bahn loops respawn at this executor scale (§7.5 — no new asset). */
    private static final float COOLDOWN_DIM_SCALE = 0.6F;

    /** Live loop handles (client main thread only). */
    private static final Map<Integer, PhotonBridge.LoopHandle> AURAS = new HashMap<>();
    private static final Map<Integer, PhotonBridge.LoopHandle> BAHNEN = new HashMap<>();
    private static final Map<Integer, PhotonBridge.LoopHandle> FAR_SHAFTS = new HashMap<>();
    @Nullable
    private static PhotonBridge.LoopHandle farPulse;
    /** Whether the live bahn loops were spawned with the COOLDOWN dim scale. */
    private static boolean bahnenDimmed;

    /** Idle crystal point lights by crystal index (≤ {@value #MAX_IDLE_LIGHTS}). */
    private static final Map<Integer, LightRenderHandle<PointLightData>> LIGHTS = new HashMap<>();
    private static final Map<Integer, Boolean> LIGHT_BUDGETED = new HashMap<>();
    @Nullable
    private static LightRenderHandle<PointLightData> finaleLight;
    private static boolean finaleLightBudgeted;
    private static boolean lightsBroken;
    private static int lightTicks;

    /** §4.6 post shimmer envelope (client tick domain). */
    private static float shimmer;
    private static float shimmerStep;

    static {
        // Feature-owned pipeline row (the ChronoGradeFx/TransitionFx pattern): this class
        // is an event subscriber, so it loads on client startup and the row exists before
        // the first tick. Iris gate + veilPostFx toggle + ≤3-pass budget are the
        // controller's job.
        VeilPostController.register(new VeilPostController.PipelineSpec(
                SHIMMER_POST, VeilPostController.PipelinePriority.FEATURE,
                ResonanceFieldFx::wantShimmer, ResonanceFieldFx::feedShimmer));
    }

    private ResonanceFieldFx() {}

    // ------------------------------------------------------------------ cue hooks

    /** Row-leg hook: a strike cue landed at {@code pos} (before the Photon spawn). */
    static void onStrikeCue(Vec3 pos) {
        LocalPlayer player = Minecraft.getInstance().player;
        if (player != null && player.position().distanceTo(pos) <= STRIKE_SHIMMER_RANGE) {
            raiseShimmer(STRIKE_SHIMMER_PEAK, STRIKE_SHIMMER_TICKS);
        }
    }

    /** Row-leg hook: the finale cue landed at {@code pos}. */
    static void onFinaleCue(Vec3 pos) {
        LocalPlayer player = Minecraft.getInstance().player;
        if (player != null && player.position().distanceTo(pos) <= FINALE_SHIMMER_RANGE) {
            raiseShimmer(FINALE_SHIMMER_PEAK, FINALE_SHIMMER_TICKS);
        }
    }

    private static void raiseShimmer(float peak, int decayTicks) {
        if (peak > shimmer) {
            shimmer = peak;
            shimmerStep = peak / decayTicks;
        }
    }

    /** State payload hook: a COOLDOWN⇄active flip re-scales the bahn loops (§7.5). */
    static void onStateSynced(ResonanceFieldClient.Snapshot snapshot) {
        boolean dim = snapshot.stateEnum() == ResonanceMelodyMachine.State.COOLDOWN;
        if (dim != bahnenDimmed) {
            releaseAll(BAHNEN);
            bahnenDimmed = dim;
        }
    }

    // ------------------------------------------------------------------ post pipeline

    /** Activation predicate of the {@code resonance_shimmer} pipeline (§4.6). */
    public static boolean wantShimmer() {
        return shimmer > 0.004F && !EclipseClientConfig.reducedFx();
    }

    /** Per-frame uniform feeder — primitives only (VeilPostController contract). */
    public static void feedShimmer(PostPipeline pipeline) {
        pipeline.getUniform("ShimmerAmount").setFloat(shimmer);
        pipeline.getUniform("Time").setFloat((lightTicks % 2000) / 20.0F);
    }

    // ------------------------------------------------------------------ per-tick driver

    @SubscribeEvent
    static void onClientTick(ClientTickEvent.Post event) {
        lightTicks++;
        if (shimmer > 0.0F) {
            shimmer = Math.max(0.0F, shimmer - shimmerStep);
        }
        Minecraft minecraft = Minecraft.getInstance();
        ClientLevel level = minecraft.level;
        LocalPlayer player = minecraft.player;
        ResonanceFieldClient.Snapshot field = ResonanceFieldClient.get();
        if (level == null || player == null || field == null
                || level.dimension() != Level.OVERWORLD || EclipseClientConfig.reducedFx()) {
            teardownLoops();
            teardownLights();
            return;
        }
        Vec3 eye = player.getEyePosition();
        Vec3 anchorCenter = Vec3.atCenterOf(field.anchor());
        double anchorDistance = eye.distanceTo(anchorCenter);

        tickNearLoops(field, eye, anchorDistance);
        tickFarLod(field, anchorCenter, anchorDistance);
        tickIdleLights(level, field, eye);
        tickFinaleLight(field);
    }

    // ------------------------------------------------------------------ near loops (§4.3/§4.4)

    private static void tickNearLoops(ResonanceFieldClient.Snapshot field, Vec3 eye,
            double anchorDistance) {
        if (anchorDistance > AURA_RELEASE + 60.0D) {
            // Far outside the valley: drop every near window in one sweep.
            releaseAll(AURAS);
            releaseAll(BAHNEN);
            return;
        }
        // Auras: the ≤4 nearest crystals inside 56/64.
        record Near(int index, double distance) {}
        List<Near> nearCrystals = new ArrayList<>(field.crystals().size());
        for (int i = 0; i < field.crystals().size(); i++) {
            nearCrystals.add(new Near(i, eye.distanceTo(field.voicePos(i))));
        }
        nearCrystals.sort(Comparator.comparingDouble(Near::distance));
        for (Iterator<Map.Entry<Integer, PhotonBridge.LoopHandle>> it =
                AURAS.entrySet().iterator(); it.hasNext();) {
            Map.Entry<Integer, PhotonBridge.LoopHandle> entry = it.next();
            double distance = eye.distanceTo(field.voicePos(entry.getKey()));
            boolean inBudget = false;
            for (int rank = 0; rank < Math.min(nearCrystals.size(), MAX_AURAS); rank++) {
                if (nearCrystals.get(rank).index() == entry.getKey()) {
                    inBudget = true;
                    break;
                }
            }
            if (distance > AURA_RELEASE || !inBudget) {
                PhotonBridge.stopLoop(entry.getValue(), true);
                it.remove();
            }
        }
        for (int rank = 0; rank < Math.min(nearCrystals.size(), MAX_AURAS); rank++) {
            Near near = nearCrystals.get(rank);
            if (near.distance() >= AURA_ENGAGE || AURAS.containsKey(near.index())
                    || handleCount() >= MAX_FIELD_HANDLES) {
                continue;
            }
            var crystal = field.crystals().get(near.index());
            float sy = crystal.height() / 20.0F;
            float sxz = 0.8F + crystal.height() / 80.0F;
            PhotonBridge.LoopHandle handle = PhotonBridge.spawnLoop(FX_CRYSTAL_AURA,
                    Vec3.atBottomCenterOf(crystal.basePos()),
                    PhotonBridge.SpawnOptions.DEFAULT.withScale(sxz, sy, sxz));
            if (handle != null) {
                AURAS.put(near.index(), handle);
            }
        }

        // Bahnen: edges whose BOTH ends sit inside 64/72; ≤6 handles, nearest first.
        record NearEdge(int index, double distance) {}
        List<NearEdge> nearEdges = new ArrayList<>(field.edges().size());
        for (int i = 0; i < field.edges().size(); i++) {
            var edge = field.edges().get(i);
            double a = eye.distanceTo(field.topPos(edge.a()));
            double b = eye.distanceTo(field.topPos(edge.b()));
            nearEdges.add(new NearEdge(i, Math.max(a, b)));
        }
        nearEdges.sort(Comparator.comparingDouble(NearEdge::distance));
        for (Iterator<Map.Entry<Integer, PhotonBridge.LoopHandle>> it =
                BAHNEN.entrySet().iterator(); it.hasNext();) {
            Map.Entry<Integer, PhotonBridge.LoopHandle> entry = it.next();
            var edge = field.edges().get(entry.getKey());
            double worst = Math.max(eye.distanceTo(field.topPos(edge.a())),
                    eye.distanceTo(field.topPos(edge.b())));
            boolean inBudget = false;
            for (int rank = 0; rank < Math.min(nearEdges.size(), MAX_BAHNEN); rank++) {
                if (nearEdges.get(rank).index() == entry.getKey()) {
                    inBudget = true;
                    break;
                }
            }
            if (worst > BAHN_RELEASE || !inBudget) {
                PhotonBridge.stopLoop(entry.getValue(), true);
                it.remove();
            }
        }
        for (int rank = 0; rank < Math.min(nearEdges.size(), MAX_BAHNEN); rank++) {
            NearEdge nearEdge = nearEdges.get(rank);
            if (nearEdge.distance() >= BAHN_ENGAGE || BAHNEN.containsKey(nearEdge.index())
                    || handleCount() >= MAX_FIELD_HANDLES) {
                continue;
            }
            var edge = field.edges().get(nearEdge.index());
            Vec3 source = field.topPos(edge.a());
            Vec3 target = field.topPos(edge.b());
            double dx = target.x - source.x;
            double dz = target.z - source.z;
            double length = Math.sqrt(dx * dx + dz * dz);
            if (length < 1.0E-3D) {
                continue;
            }
            // Asset's beam runs to local −Z; Minecraft yaw φ has forward (−sin φ, 0,
            // cos φ) ⇒ executor rotationY = 180° − φ (the FerrymanFinaleFxRows JOML
            // derivation); length rides the z-scale.
            double yawDeg = Math.toDegrees(Math.atan2(-dx, dz));
            float dim = bahnenDimmed ? COOLDOWN_DIM_SCALE : 1.0F;
            PhotonBridge.LoopHandle handle = PhotonBridge.spawnLoop(FX_BAHN, source,
                    PhotonBridge.SpawnOptions.DEFAULT
                            .withRotationDeg(0.0D, 180.0D - yawDeg, 0.0D)
                            .withScale(dim, dim, length * dim));
            if (handle != null) {
                BAHNEN.put(nearEdge.index(), handle);
            }
        }
    }

    // ------------------------------------------------------------------ far LOD (§8)

    private static void tickFarLod(ResonanceFieldClient.Snapshot field, Vec3 anchorCenter,
            double anchorDistance) {
        boolean farWanted = anchorDistance >= FAR_ENGAGE_MIN && anchorDistance <= FAR_ENGAGE_MAX;
        boolean farHeld = anchorDistance >= FAR_RELEASE_MIN && anchorDistance <= FAR_RELEASE_MAX;
        if (!farWanted && !(farHeld && (!FAR_SHAFTS.isEmpty() || farPulse != null))) {
            releaseAll(FAR_SHAFTS);
            if (farPulse != null) {
                PhotonBridge.stopLoop(farPulse, true);
                farPulse = null;
            }
            return;
        }
        if (!farWanted) {
            return; // inside the hysteresis band — hold what is live, add nothing
        }
        // The ≤4 tallest crystals carry the silhouette (§1 Fernwirkung).
        record Tall(int index, float height) {}
        List<Tall> tallest = new ArrayList<>(field.crystals().size());
        for (int i = 0; i < field.crystals().size(); i++) {
            tallest.add(new Tall(i, field.crystals().get(i).height()));
        }
        tallest.sort(Comparator.comparingDouble(Tall::height).reversed());
        float widthScale = (float) Mth.clamp(anchorDistance / 220.0D, 1.0D, 2.2D);
        for (int rank = 0; rank < Math.min(tallest.size(), MAX_FAR_SHAFTS); rank++) {
            Tall tall = tallest.get(rank);
            if (FAR_SHAFTS.containsKey(tall.index()) || handleCount() >= MAX_FIELD_HANDLES) {
                continue;
            }
            var crystal = field.crystals().get(tall.index());
            // Shaft height ≈ crystal height × 2 (asset is authored 60 blocks tall);
            // width distance-scaled — the CUE_SUMMON_BEACON far-readability recipe.
            float sy = crystal.height() * 2.0F / 60.0F;
            PhotonBridge.LoopHandle handle = PhotonBridge.spawnLoop(FX_FAR_SHAFT,
                    Vec3.atBottomCenterOf(crystal.basePos()),
                    PhotonBridge.SpawnOptions.DEFAULT.withScale(widthScale, sy, widthScale));
            if (handle != null) {
                FAR_SHAFTS.put(tall.index(), handle);
            }
        }
        if (farPulse == null && handleCount() < MAX_FIELD_HANDLES) {
            farPulse = PhotonBridge.spawnLoop(FX_FAR_PULSE, anchorCenter.add(0.0D, 50.0D, 0.0D));
        }
    }

    // ------------------------------------------------------------------ point lights (§4.5)

    /** ≤2 idle violet lights on the nearest monoliths, night only, breathing brightness. */
    private static void tickIdleLights(ClientLevel level, ResonanceFieldClient.Snapshot field,
            Vec3 eye) {
        boolean night = level.getSkyDarken() >= NIGHT_SKY_DARKEN;
        record Near(int index, double distance) {}
        List<Near> near = new ArrayList<>(field.crystals().size());
        for (int i = 0; i < field.crystals().size(); i++) {
            near.add(new Near(i, eye.distanceTo(field.voicePos(i))));
        }
        near.sort(Comparator.comparingDouble(Near::distance));
        for (Iterator<Map.Entry<Integer, LightRenderHandle<PointLightData>>> it =
                LIGHTS.entrySet().iterator(); it.hasNext();) {
            Map.Entry<Integer, LightRenderHandle<PointLightData>> entry = it.next();
            double distance = eye.distanceTo(field.voicePos(entry.getKey()));
            boolean inBudget = false;
            for (int rank = 0; rank < Math.min(near.size(), MAX_IDLE_LIGHTS); rank++) {
                if (near.get(rank).index() == entry.getKey()) {
                    inBudget = true;
                    break;
                }
            }
            if (!night || distance > LIGHT_RELEASE || !inBudget
                    || !entry.getValue().isValid()) {
                freeLight(entry.getKey(), entry.getValue());
                it.remove();
            }
        }
        if (night && !lightsBroken) {
            for (int rank = 0; rank < Math.min(near.size(), MAX_IDLE_LIGHTS); rank++) {
                Near candidate = near.get(rank);
                if (candidate.distance() >= LIGHT_ENGAGE
                        || LIGHTS.containsKey(candidate.index())) {
                    continue;
                }
                LightRenderHandle<PointLightData> handle =
                        addLight(0.71F, 0.36F, 1.0F, LIGHT_RADIUS);
                if (handle != null) {
                    LIGHTS.put(candidate.index(), handle);
                    LIGHT_BUDGETED.put(candidate.index(), Boolean.TRUE);
                }
            }
        }
        // Breathing on the bahn beat (40 t period), per-crystal phase offset.
        for (Map.Entry<Integer, LightRenderHandle<PointLightData>> entry : LIGHTS.entrySet()) {
            Vec3 pos = field.voicePos(entry.getKey());
            PointLightData data = entry.getValue().getLightData();
            data.setPosition(pos.x, pos.y, pos.z);
            data.setBrightness(0.55F + 0.25F
                    * Mth.sin((lightTicks + entry.getKey() * 7) * (Mth.TWO_PI / 40.0F)));
        }
    }

    /** The 160-tick finale light at the altar (radius 40) while the FINALE state is live. */
    private static void tickFinaleLight(ResonanceFieldClient.Snapshot field) {
        boolean finale = field.stateEnum() == ResonanceMelodyMachine.State.FINALE
                && field.age() <= ResonanceMelodyMachine.FINALE_TICKS;
        if (!finale) {
            freeFinaleLight();
            return;
        }
        if (finaleLight == null && !lightsBroken) {
            finaleLight = addLight(0.78F, 0.46F, 1.0F, FINALE_LIGHT_RADIUS);
            finaleLightBudgeted = finaleLight != null;
        }
        if (finaleLight != null && finaleLight.isValid()) {
            float age = field.age();
            // Envelope: 20 t attack, hold, linear release into the cooldown.
            float envelope = age < 20.0F ? age / 20.0F
                    : 1.0F - Math.max(0.0F, age - 100.0F) / 60.0F;
            Vec3 altar = Vec3.atCenterOf(field.altar().above());
            PointLightData data = finaleLight.getLightData();
            data.setPosition(altar.x, altar.y + 2.0D, altar.z);
            data.setBrightness(1.2F * Mth.clamp(envelope, 0.0F, 1.0F));
        }
    }

    @Nullable
    private static LightRenderHandle<PointLightData> addLight(float r, float g, float b,
            float radius) {
        if (!FxBudget.tryLight()) {
            return null;
        }
        try {
            PointLightData data = new PointLightData();
            data.setColor(r, g, b);
            data.setRadius(radius);
            data.setBrightness(0.0F);
            return VeilRenderSystem.renderer().getLightRenderer().addLight(data);
        } catch (Throwable t) {
            FxBudget.releaseLight();
            if (!lightsBroken) {
                lightsBroken = true;
                EclipseMod.LOGGER.warn(
                        "Veil light renderer unavailable; resonance field renders without dynamic lights", t);
            }
            return null;
        }
    }

    private static void freeLight(int index, LightRenderHandle<PointLightData> handle) {
        try {
            handle.free();
        } catch (Throwable ignored) {
            // Teardown-order safe: Veil may already have freed its state.
        }
        if (Boolean.TRUE.equals(LIGHT_BUDGETED.remove(index))) {
            FxBudget.releaseLight();
        }
    }

    private static void freeFinaleLight() {
        LightRenderHandle<PointLightData> handle = finaleLight;
        finaleLight = null;
        if (handle != null) {
            try {
                handle.free();
            } catch (Throwable ignored) {
                // Teardown-order safe.
            }
        }
        if (finaleLightBudgeted) {
            finaleLightBudgeted = false;
            FxBudget.releaseLight();
        }
    }

    // ------------------------------------------------------------------ teardown

    private static int handleCount() {
        return AURAS.size() + BAHNEN.size() + FAR_SHAFTS.size() + (farPulse != null ? 1 : 0);
    }

    private static void releaseAll(Map<Integer, PhotonBridge.LoopHandle> handles) {
        for (PhotonBridge.LoopHandle handle : handles.values()) {
            PhotonBridge.stopLoop(handle, true);
        }
        handles.clear();
    }

    private static void teardownLoops() {
        releaseAll(AURAS);
        releaseAll(BAHNEN);
        releaseAll(FAR_SHAFTS);
        if (farPulse != null) {
            PhotonBridge.stopLoop(farPulse, true);
            farPulse = null;
        }
    }

    private static void teardownLights() {
        for (Map.Entry<Integer, LightRenderHandle<PointLightData>> entry : LIGHTS.entrySet()) {
            freeLight(entry.getKey(), entry.getValue());
        }
        LIGHTS.clear();
        LIGHT_BUDGETED.clear();
        freeFinaleLight();
    }

    @SubscribeEvent
    static void onLoggingOut(ClientPlayerNetworkEvent.LoggingOut event) {
        teardownLoops();
        teardownLights();
        shimmer = 0.0F;
        bahnenDimmed = false;
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
