import Foundation

/// Core UI strings (onboarding, tabs, home, settings, servers, errors).
/// Feature-specific strings live in ChatL10n / GamesL10n / MemoriesL10n.
enum CoreStrings {
    static let table: [String: LText] = [
        // Common
        "common.ok": LText(de: "OK", en: "OK"),
        "common.cancel": LText(de: "Abbrechen", en: "Cancel"),
        "common.save": LText(de: "Speichern", en: "Save"),
        "common.delete": LText(de: "Löschen", en: "Delete"),
        "common.edit": LText(de: "Bearbeiten", en: "Edit"),
        "common.done": LText(de: "Fertig", en: "Done"),
        "common.retry": LText(de: "Nochmal versuchen", en: "Retry"),
        "common.close": LText(de: "Schließen", en: "Close"),
        "common.add": LText(de: "Hinzufügen", en: "Add"),
        "common.error": LText(de: "Ups, das hat nicht geklappt", en: "Oops, that didn't work"),
        "common.loading": LText(de: "Lädt…", en: "Loading…"),
        "common.back": LText(de: "Zurück", en: "Back"),
        "common.share": LText(de: "Teilen", en: "Share"),
        "common.copy": LText(de: "Kopieren", en: "Copy"),
        "common.copied": LText(de: "Kopiert!", en: "Copied!"),
        "common.today": LText(de: "Heute", en: "Today"),
        "common.days": LText(de: "Tage", en: "days"),
        "common.day": LText(de: "Tag", en: "day"),

        // Compact relative times (see L10n.relativeShort)
        "time.justNow": LText(de: "gerade eben", en: "just now"),
        "time.minutesAgo": LText(de: "vor {n} Min.", en: "{n} min ago"),
        "time.hoursAgo": LText(de: "vor {n} Std.", en: "{n} h ago"),
        "time.yesterday": LText(de: "gestern", en: "yesterday"),
        "time.daysAgo": LText(de: "vor {n} Tagen", en: "{n} days ago"),
        "common.you": LText(de: "Du", en: "You"),
        "common.partner": LText(de: "Schatz", en: "Sweetheart"),
        "common.send": LText(de: "Senden", en: "Send"),

        // Tabs
        "tab.home": LText(de: "Zuhause", en: "Home"),
        "tab.chat": LText(de: "Chat", en: "Chat"),
        "tab.play": LText(de: "Spielen", en: "Play"),
        "tab.us": LText(de: "Wir", en: "Us"),
        "tab.more": LText(de: "Mehr", en: "More"),

        // Onboarding
        "onboarding.title": LText(de: "SoooDreamy", en: "SoooDreamy"),
        "onboarding.tagline": LText(de: "Die App für euch zwei. Euer Server, eure Daten, eure Welt. 💜",
                                    en: "The app for the two of you. Your server, your data, your world. 💜"),
        "onboarding.feature1": LText(de: "Herzklopfen senden — mit echter Haptik", en: "Send heartbeats — with real haptics"),
        "onboarding.feature2": LText(de: "Chat, Fotos, Sprachnachrichten & Kritzel-Canvas", en: "Chat, photos, voice notes & doodle canvas"),
        "onboarding.feature3": LText(de: "Spiele, Fragen des Tages & Date-Ideen", en: "Games, daily questions & date ideas"),
        "onboarding.feature4": LText(de: "Widgets & Live-Countdowns für eure Momente", en: "Widgets & live countdowns for your moments"),
        "onboarding.start": LText(de: "Los geht's", en: "Let's go"),
        "onboarding.language": LText(de: "Sprache", en: "Language"),
        "language.system": LText(de: "System", en: "System"),
        "language.de": LText(de: "Deutsch", en: "German"),
        "language.en": LText(de: "Englisch", en: "English"),

        // Server setup
        "server.setupTitle": LText(de: "Euer Server", en: "Your server"),
        "server.setupSubtitle": LText(de: "SoooDreamy läuft auf eurem eigenen kleinen Server — zuhause, auf einem Raspberry Pi oder in der Cloud. Tragt hier seine Adresse ein.",
                                      en: "SoooDreamy runs on your own little server — at home, on a Raspberry Pi or in the cloud. Enter its address here."),
        "server.name": LText(de: "Name (z. B. „Zuhause“)", en: "Name (e.g. “Home”)"),
        "server.url": LText(de: "Adresse, z. B. 192.168.1.20:4321", en: "Address, e.g. 192.168.1.20:4321"),
        "server.test": LText(de: "Verbindung testen", en: "Test connection"),
        "server.testOK": LText(de: "Verbunden! {name} ({version})", en: "Connected! {name} ({version})"),
        "server.testFail": LText(de: "Keine Verbindung: {error}", en: "No connection: {error}"),
        "server.testFailATS": LText(de: "Alte App-Version erkannt (ATS blockiert http://). Bitte IPA 1.2.0+ neu sideloaden von github.com/MedusaV9/ModdingWebseite/releases/tag/sooodreamy-latest — vorher die alte App löschen. Dein Server ist ok; nur der Client ist veraltet.",
                                    en: "Old app build detected (ATS blocks http://). Please re-sideload IPA 1.2.0+ from github.com/MedusaV9/ModdingWebseite/releases/tag/sooodreamy-latest — delete the old app first. Your server is fine; only the client is outdated."),
        "server.invalidURL": LText(de: "Das sieht nicht wie eine gültige Adresse aus", en: "That doesn't look like a valid address"),
        "server.buildBadge": LText(de: "App-Build {version} · HTTP freigeschaltet", en: "App build {version} · HTTP allowed"),
        "server.add": LText(de: "Server hinzufügen", en: "Add server"),
        "server.manage": LText(de: "Server verwalten", en: "Manage servers"),
        "server.active": LText(de: "Aktiv", en: "Active"),
        "server.switch": LText(de: "Zu diesem Server wechseln", en: "Switch to this server"),
        "server.switched": LText(de: "Server gewechselt: {name}", en: "Switched server: {name}"),
        "server.delete": LText(de: "Server entfernen", en: "Remove server"),
        "server.deleteConfirm": LText(de: "„{name}“ wirklich entfernen? Die Kopplung auf diesem Server geht auf diesem Gerät verloren.",
                                      en: "Really remove “{name}”? Your pairing on that server will be lost on this device."),
        "server.paired": LText(de: "Gekoppelt", en: "Paired"),
        "server.notPaired": LText(de: "Noch nicht gekoppelt", en: "Not paired yet"),
        "server.hint": LText(de: "★ Normales http:// ist freigeschaltet (Build 1.2.1+) — wenn du den mintfarbenen App-Build-Badge siehst, bist du auf dem richtigen IPA. Adresse z. B. http://ark.atomi23.de:4321 — den Port :4321 nicht weglassen!",
                             en: "★ Plain http:// is unlocked (build 1.2.1+) — if you see the mint App-Build badge, you have the right IPA. Address e.g. http://ark.atomi23.de:4321 — don't drop the :4321 port!"),
        "server.continue": LText(de: "Weiter", en: "Continue"),
        "server.pickTitle": LText(de: "Mit welchem Server?", en: "Which server?"),

        // Pairing
        "pairing.title": LText(de: "Findet zueinander", en: "Find each other"),
        "pairing.subtitle": LText(de: "Eine:r von euch erstellt euer Paar, die/der andere tritt mit dem Code bei.",
                                  en: "One of you creates your couple, the other joins with the code."),
        "pairing.create": LText(de: "Paar erstellen", en: "Create couple"),
        "pairing.join": LText(de: "Mit Code beitreten", en: "Join with code"),
        "pairing.codePlaceholder": LText(de: "Code, z. B. H4XK9P", en: "Code, e.g. H4XK9P"),
        "pairing.yourCode": LText(de: "Euer Code", en: "Your code"),
        "pairing.shareCode": LText(de: "Schick den Code deinem Schatz 💌", en: "Send the code to your sweetheart 💌"),
        "pairing.waiting": LText(de: "Warte auf deinen Schatz…", en: "Waiting for your sweetheart…"),
        "pairing.scanQR": LText(de: "QR-Code scannen", en: "Scan QR code"),
        "pairing.showQR": LText(de: "QR-Code zeigen", en: "Show QR code"),
        "pairing.partnerJoined": LText(de: "{name} ist da! 🎉", en: "{name} joined! 🎉"),
        "pairing.unknownCode": LText(de: "Diesen Code kennt der Server nicht", en: "The server doesn't know this code"),
        "pairing.coupleFull": LText(de: "Dieses Paar ist schon komplett", en: "This couple is already complete"),
        "pairing.yourName": LText(de: "Dein Name", en: "Your name"),
        "pairing.avatar": LText(de: "Dein Emoji", en: "Your emoji"),
        "pairing.color": LText(de: "Deine Farbe", en: "Your color"),
        "pairing.profileTitle": LText(de: "Das bist du", en: "This is you"),
        "pairing.qrHint": LText(de: "Dein Schatz kann den Code auch scannen — Server & Code in einem.",
                                en: "Your sweetheart can also scan the code — server & code in one."),

        // Home / dashboard
        "home.daysTogether": LText(de: "Tage zusammen", en: "days together"),
        "home.sinceHint": LText(de: "Jahrestag in den Einstellungen setzen", en: "Set your anniversary in settings"),
        "home.online": LText(de: "online", en: "online"),
        "home.offline": LText(de: "offline", en: "offline"),
        "home.lastSeen": LText(de: "zuletzt {time}", en: "last seen {time}"),
        "home.yourMood": LText(de: "Deine Stimmung", en: "Your mood"),
        "home.moodOf": LText(de: "{name} fühlt sich…", en: "{name} is feeling…"),
        "home.noMood": LText(de: "Noch keine Stimmung geteilt", en: "No mood shared yet"),
        "home.setMood": LText(de: "Stimmung teilen", en: "Share mood"),
        "home.moodNote": LText(de: "Kleine Notiz dazu? (optional)", en: "A little note? (optional)"),
        "home.sendLove": LText(de: "Schick Liebe", en: "Send love"),
        "home.dailyQuestion": LText(de: "Frage des Tages", en: "Question of the day"),
        "home.answerNow": LText(de: "Jetzt antworten", en: "Answer now"),
        "home.waitingPartnerAnswer": LText(de: "Warte auf {name}s Antwort…", en: "Waiting for {name}'s answer…"),
        "home.bothAnswered": LText(de: "Ihr habt beide geantwortet! 💞", en: "You both answered! 💞"),
        "home.shareAnswers": LText(de: "Antworten in den Chat 💬", en: "Send answers to chat 💬"),
        "home.dailyShareHeader": LText(de: "❓ Frage des Tages:", en: "❓ Question of the day:"),
        "home.streak": LText(de: "{n}er-Serie", en: "{n}-day streak"),
        "home.nextEvent": LText(de: "Als Nächstes", en: "Up next"),
        "home.inDays": LText(de: "in {n} Tagen", en: "in {n} days"),
        "home.tomorrow": LText(de: "morgen!", en: "tomorrow!"),
        "home.todayBang": LText(de: "HEUTE! 🎉", en: "TODAY! 🎉"),
        "home.waitingForPartner": LText(de: "Euer Nest ist fast fertig", en: "Your nest is almost ready"),
        "home.waitingForPartnerSub": LText(de: "Teile den Code mit deinem Schatz, dann geht's los:",
                                           en: "Share the code with your sweetheart to get started:"),
        "home.touchSent": LText(de: "Gesendet! {emoji}", en: "Sent! {emoji}"),
        "home.heartTapHint": LText(de: "Tipp aufs Herz, um Herzklopfen zu senden", en: "Tap the heart to send a heartbeat"),

        // Touches
        "touch.heartbeat": LText(de: "Herzklopfen", en: "Heartbeat"),
        "touch.kiss": LText(de: "Kuss", en: "Kiss"),
        "touch.hug": LText(de: "Umarmung", en: "Hug"),
        "touch.missyou": LText(de: "Vermiss dich", en: "Miss you"),
        "touch.tickle": LText(de: "Kitzeln", en: "Tickle"),
        "touch.thinking": LText(de: "Denk an dich", en: "Thinking of you"),
        "touch.received.heartbeat": LText(de: "{name} schickt dir Herzklopfen", en: "{name} sends you a heartbeat"),
        "touch.received.kiss": LText(de: "{name} küsst dich", en: "{name} kisses you"),
        "touch.received.hug": LText(de: "{name} umarmt dich ganz fest", en: "{name} hugs you tight"),
        "touch.received.missyou": LText(de: "{name} vermisst dich", en: "{name} misses you"),
        "touch.received.tickle": LText(de: "{name} kitzelt dich", en: "{name} tickles you"),
        "touch.received.thinking": LText(de: "{name} denkt gerade an dich", en: "{name} is thinking of you"),

        // Settings
        "settings.title": LText(de: "Mehr", en: "More"),
        "settings.profile": LText(de: "Dein Profil", en: "Your profile"),
        "settings.couple": LText(de: "Euer Paar", en: "Your couple"),
        "settings.coupleName": LText(de: "Name eures Paars", en: "Couple name"),
        "settings.anniversary": LText(de: "Jahrestag", en: "Anniversary"),
        "settings.anniversaryHint": LText(de: "Seit wann seid ihr zusammen?", en: "Since when are you together?"),
        "settings.language": LText(de: "Sprache", en: "Language"),
        "settings.sounds": LText(de: "Sounds", en: "Sounds"),
        "settings.haptics": LText(de: "Haptik", en: "Haptics"),
        "settings.reminder": LText(de: "Tägliche Erinnerung", en: "Daily reminder"),
        "settings.reminderHint": LText(de: "Erinnert euch abends an die Frage des Tages", en: "Evening nudge for the question of the day"),
        "settings.reminderTime": LText(de: "Uhrzeit", en: "Time"),
        "settings.streakGuard": LText(de: "Serien-Schutz", en: "Streak guard"),
        "settings.streakGuardHint": LText(de: "Zweite Erinnerung um 21:30, wenn eure Antwort-Serie in Gefahr ist",
                                          en: "Second reminder at 9:30 pm when your answer streak is at risk"),
        "settings.unpair": LText(de: "Paar auflösen", en: "Dissolve couple"),
        "settings.unpairConfirm": LText(de: "Wirklich? Das löscht ALLE eure Daten auf dem Server — Chats, Fotos, alles. Das kann nicht rückgängig gemacht werden.",
                                        en: "Really? This deletes ALL your data on the server — chats, photos, everything. This cannot be undone."),
        "settings.leaveDevice": LText(de: "Auf diesem Gerät abmelden", en: "Sign out on this device"),
        "settings.leaveDeviceHint": LText(de: "Eure Daten bleiben auf dem Server. Mit dem Code kommst du nicht wieder rein — hebe den Server gut auf!",
                                          en: "Your data stays on the server. Keep your server safe!"),
        "settings.about": LText(de: "Über SoooDreamy", en: "About SoooDreamy"),
        "settings.version": LText(de: "Version", en: "Version"),
        "settings.madeWith": LText(de: "Mit 💜 gebaut — für euch zwei.", en: "Built with 💜 — for the two of you."),
        "settings.connection": LText(de: "Verbindung", en: "Connection"),
        "settings.pairingShow": LText(de: "Paar-Code & QR zeigen", en: "Show couple code & QR"),
        "settings.pairingHint": LText(de: "Zum Koppeln eines neuen Geräts — oder falls dein Schatz den Code nochmal braucht.",
                                      en: "For pairing a new device — or in case your sweetheart needs the code again."),
        "settings.widgets": LText(de: "Widgets", en: "Widgets"),
        "settings.widgetsHint": LText(de: "Lange auf den Homescreen drücken → „Widget hinzufügen“ → SoooDreamy",
                                      en: "Long-press your home screen → “Add widget” → SoooDreamy"),
        "settings.widgetBackground": LText(de: "Widget-Hintergrund", en: "Widget background"),
        "settings.widgetPhotoChrome": LText(de: "Foto als Widget-Hintergrund", en: "Photo as widget backdrop"),
        "settings.widgetPhotoChromeHint": LText(de: "Foto- & Leinwand-Widgets zeigen euer Lieblingsfoto abgedunkelt im Hintergrund",
                                                en: "Photo & canvas widgets show your favorite photo, dimmed, as their backdrop"),
        "settings.widgetBg.night": LText(de: "Nacht", en: "Night"),
        "settings.widgetBg.sunset": LText(de: "Abendrot", en: "Sunset"),
        "settings.widgetBg.ocean": LText(de: "Ozean", en: "Ocean"),
        "settings.widgetBg.blush": LText(de: "Rosé", en: "Blush"),
        "settings.widgetBg.mono": LText(de: "Mono", en: "Mono"),
        "settings.widgetBg.photo": LText(de: "Foto", en: "Photo"),

        // Couple Pulse Live Activity
        "settings.pulse": LText(de: "Live Activity: Couple Pulse", en: "Live Activity: Couple Pulse"),
        "settings.pulseHint": LText(de: "Stimmung, Online-Status, letzte Berührung & Serie deines Schatzes auf dem Sperrbildschirm & in der Dynamic Island — aktualisiert, solange die App läuft (kein Push).",
                                    en: "Your sweetheart's mood, online status, last touch & streak on the lock screen & Dynamic Island — updated while the app is running (no push)."),
        "settings.pulseStarted": LText(de: "Couple Pulse läuft! 💜", en: "Couple Pulse is live! 💜"),

        // Notifications (couple alerts — local, WebSocket-driven)
        "notif.section": LText(de: "Benachrichtigungen", en: "Notifications"),
        "notif.master": LText(de: "Paar-Benachrichtigungen", en: "Couple alerts"),
        "notif.masterHint": LText(de: "Lokale Hinweise, wenn dein Schatz etwas schickt — solange die App läuft (Sideload, kein Push).",
                                  en: "Local alerts when your sweetheart sends something — while the app is running (sideload, no push)."),
        "notif.sound": LText(de: "Benachrichtigungston", en: "Notification sound"),
        "notif.sound.soft": LText(de: "Sanft", en: "Soft"),
        "notif.sound.chime": LText(de: "Glöckchen", en: "Chime"),
        "notif.sound.heartbeat": LText(de: "Herzschlag", en: "Heartbeat"),
        "notif.sound.kiss": LText(de: "Kuss", en: "Kiss"),
        "notif.sound.sparkle": LText(de: "Funkeln", en: "Sparkle"),
        "notif.sound.whoosh": LText(de: "Wusch", en: "Whoosh"),
        "notif.sound.tada": LText(de: "Tada", en: "Tada"),
        "notif.sound.default": LText(de: "System", en: "System"),
        "notif.type.touch": LText(de: "Berührungen", en: "Touches"),
        "notif.type.message": LText(de: "Nachrichten", en: "Messages"),
        "notif.type.photo": LText(de: "Neue Fotos", en: "New photos"),
        "notif.type.dailyReveal": LText(de: "Frage des Tages gelüftet", en: "Daily question revealed"),
        "notif.type.partnerOnline": LText(de: "Schatz kommt online", en: "Sweetheart comes online"),
        "notif.type.coupon": LText(de: "Gutscheine", en: "Coupons"),
        "notif.message.title": LText(de: "Neue Nachricht von {name}", en: "New message from {name}"),
        "notif.message.letter": LText(de: "Ein Brief für dich 💌", en: "A letter for you 💌"),
        "notif.message.voice": LText(de: "Eine Sprachnachricht für dich 🎤", en: "A voice note for you 🎤"),
        "notif.photo.title": LText(de: "Neues Foto 📸", en: "New photo 📸"),
        "notif.photo.body": LText(de: "{name} hat ein neues Foto geteilt", en: "{name} shared a new photo"),
        "notif.daily.body": LText(de: "Eure Antworten auf die Frage des Tages sind jetzt sichtbar",
                                  en: "Your answers to the daily question are revealed"),
        "notif.online.title": LText(de: "{name} ist jetzt online 💜", en: "{name} is online now 💜"),
        "notif.online.body": LText(de: "Jetzt wäre ein Herzklopfen perfekt …", en: "Now would be perfect for a heartbeat…"),
        "notif.coupon.title": LText(de: "Neuer Gutschein 🎟️", en: "New coupon 🎟️"),
        "notif.coupon.body": LText(de: "{name} schenkt dir: „{title}“", en: "{name} gives you: “{title}”"),
        "notif.streak.title": LText(de: "Eure Serie ist in Gefahr! 🔥", en: "Your streak is at risk! 🔥"),
        "notif.streak.body": LText(de: "Beantworte noch schnell die Frage des Tages und rette eure {n}er-Serie.",
                                   en: "Answer today's question quickly and save your {n}-day streak."),

        // App lock
        "lock.title": LText(de: "SoooDreamy ist gesperrt", en: "SoooDreamy is locked"),
        "lock.subtitle": LText(de: "Eure Momente gehören nur euch zwei.", en: "Your moments belong to the two of you only."),
        "lock.unlock": LText(de: "Entsperren", en: "Unlock"),
        "lock.reason": LText(de: "Eure gemeinsamen Momente entsperren", en: "Unlock your shared moments"),
        "settings.appLock": LText(de: "App-Sperre", en: "App lock"),
        "settings.appLockHint": LText(de: "Beim Öffnen mit Face ID / Touch ID oder Code entsperren",
                                      en: "Unlock with Face ID / Touch ID or passcode when opening"),

        // Monthiversary
        "home.monthiversary": LText(de: "{n} Monate zusammen — genau heute! 🎉",
                                    en: "{n} months together — today! 🎉"),
        "home.monthiversaryOne": LText(de: "1 Monat zusammen — genau heute! 🎉",
                                       en: "1 month together — today! 🎉"),
        "home.anniversaryYears": LText(de: "{n} Jahre zusammen — happy Jahrestag! 🥂",
                                       en: "{n} years together — happy anniversary! 🥂"),
        "home.anniversaryOneYear": LText(de: "1 Jahr zusammen — happy Jahrestag! 🥂",
                                         en: "1 year together — happy anniversary! 🥂"),

        // Coupons (global toasts)
        "coupon.receivedToast": LText(de: "Neuer Gutschein für dich! 🎟️", en: "A new coupon for you! 🎟️"),
        "coupon.redeemedToast": LText(de: "„{title}“ wurde eingelöst! 🎉", en: "“{title}” was redeemed! 🎉"),

        // Flashback card
        "home.flashback": LText(de: "Erinnerung", en: "Memory"),
        "home.flashbackDaysAgo": LText(de: "vor {n} Tagen", en: "{n} days ago"),
        "home.flashbackQuestion": LText(de: "Eure Frage von damals", en: "Your question back then"),

        // "While you were away" card (missed inbox)
        "home.missedTitle": LText(de: "Während du weg warst", en: "While you were away"),
        "home.missedBody": LText(de: "Tippen, um alles nachzuholen", en: "Tap to catch up"),
        "home.missed.messages": LText(de: "Nachrichten", en: "Messages"),
        "home.missed.touches": LText(de: "Berührungen", en: "Touches"),
        "home.missed.photos": LText(de: "Fotos", en: "Photos"),
        "home.missed.coupons": LText(de: "Gutscheine", en: "Coupons"),
        "home.missed.songs": LText(de: "Songs", en: "Songs"),
        "home.missed.canvas": LText(de: "Leinwand-Kritzeleien", en: "Canvas doodles"),
        "home.missed.daily": LText(de: "Frage des Tages beantwortet", en: "Daily question answered"),

        // Connection banner
        "conn.connecting": LText(de: "Verbinde…", en: "Connecting…"),
        "conn.offline": LText(de: "Offline — versuche es wieder…", en: "Offline — retrying…"),
        "conn.connected": LText(de: "Verbunden", en: "Connected"),

        // Errors
        "error.invalidURL": LText(de: "Ungültige Server-Adresse", en: "Invalid server address"),
        "error.decoding": LText(de: "Antwort vom Server nicht verstanden", en: "Couldn't understand the server's reply"),
        "error.network": LText(de: "Netzwerkfehler — ist der Server erreichbar?", en: "Network error — is the server reachable?"),
        "error.unauthorized": LText(de: "Anmeldung abgelaufen — bitte neu koppeln", en: "Session expired — please pair again"),

        // Misc
        "misc.partnerDefault": LText(de: "dein Schatz", en: "your sweetheart"),
        "misc.dissolvedTitle": LText(de: "Euer Paar wurde aufgelöst", en: "Your couple was dissolved"),
        "misc.partnerJoinedToast": LText(de: "{name} ist beigetreten! 💞", en: "{name} joined! 💞")
    ]
}
