#!/usr/bin/env python3
"""Gazer face-rig v2 (MOB-AMBIENT) — in-place refinement of `textures/entity/gazer.png`.

The gazer's iris/eyelid rig (`GazerModel` v2) adds four cubes to the frozen 64x64 sheet
(`docs/uv/gazer.md`); this script paints ONLY those new rects into the existing Batch D
art (generated by `scripts/placeholder_gen/EntitySkinArtist.writeGazer`) — everything
else is left byte-identical:

- iris pips, texOffs (46,16), 1x2x1 (shared by iris_left/iris_right): EMISSIVE — they
  render in the `RenderType.eyes` pass with the face, so they are painted unshaded and
  one step HOTTER than the mask plate (`#F7F0FF`) to read as pupils inside the hollow
  eye slits.
- eyelids, texOffs (44,24) + (44,28), 7x3x1 (lid_top / lid_bottom): hood cloth
  (`#1E1A30` weave, albedo pass only) with a darkened rim row on the closing edge so a
  blink reads as cloth sliding over the glow.

Run from the ProjectEclipse root: `python3 scripts/skin_gen/gazer_v2.py`.
Deterministic -> byte-identical output on every rerun.
"""

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from boss_paint import face_rects, hexc, mix, mul  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PNG = ROOT / "src/main/resources/assets/eclipse/textures/entity/gazer.png"

SEED = 0x6A2E12

HOOD = hexc("#1E1A30")       # hood/lid cloth (EntitySkinArtist.writeGazer hoodC)
IRIS_HOT = hexc("#FFF4FF")   # pip core — hotter than the mask's #F7F0FF
IRIS = hexc("#E6D9FA")       # mask plate violet
IRIS_DIM = hexc("#B9A6DC")   # mask dim rim


def noise(x, y, salt=0):
    n = (x * 374761393 + y * 668265263 + salt * 2246822519 + SEED) & 0xFFFFFFFF
    n = (n ^ (n >> 13)) * 1274126177 & 0xFFFFFFFF
    return ((n ^ (n >> 16)) & 0xFFFF) / 65536.0


def weave(base, gx, gy, salt, amp=0.28):
    """Vertical-streak cloth dither (the hood weave from EntitySkinArtist)."""
    streak = noise(gx, gy // 3, salt)
    fine = noise(gx, gy, salt + 101)
    return mul(base, 1.0 + (0.72 * streak + 0.28 * fine - 0.5) * amp)


def paint_box(px, u, v, w, h, d, painter):
    for face, (x0, y0, x1, y1) in face_rects(u, v, w, h, d).items():
        for gy in range(y0, y1):
            for gx in range(x0, x1):
                color = painter(face, gx - x0, gy - y0, x1 - x0, y1 - y0, gx, gy)
                if color is not None:
                    px[gx, gy] = color


def iris(face, fx, fy, fw, fh, gx, gy):
    if face == "north":
        return IRIS_HOT if fy == 0 else mix(IRIS_HOT, IRIS, 0.5)
    if face == "up":
        return IRIS
    if face == "down":
        return mul(IRIS_DIM, 0.8)
    return IRIS_DIM  # east/west/south slivers face the hood interior


def lid(closing_edge_row):
    """Hood-cloth lid; `closing_edge_row` picks which north row is the darkened rim
    (bottom row for lid_top, top row for lid_bottom — the edges that meet mid-blink)."""
    def paint(face, fx, fy, fw, fh, gx, gy):
        col = weave(HOOD, gx, gy, 12)
        if face == "south":
            return mul(col, 0.6)  # inner side, buried in the hood shadow
        if face == "north" and fy == (fh - 1 if closing_edge_row == "bottom" else 0):
            return mul(col, 0.66)  # rim the closing edge
        return col
    return paint


def main():
    img = Image.open(PNG).convert("RGBA")
    px = img.load()
    paint_box(px, 46, 16, 1, 2, 1, iris)
    paint_box(px, 44, 24, 7, 3, 1, lid("bottom"))
    paint_box(px, 44, 28, 7, 3, 1, lid("top"))
    img.save(PNG)
    print(f"gazer v2 face rig painted into {PNG} ({img.size[0]}x{img.size[1]})")


if __name__ == "__main__":
    main()
