package dev.projecteclipse.eclipse.devtools.dev;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import net.minecraft.server.MinecraftServer;
import net.neoforged.fml.loading.FMLPaths;

/**
 * Generates {@code docs/DEV_COMMANDS.md} from {@link DevCommandRegistry} (§2.1).
 */
public final class DevDocsExporter {
    private static final String GENERATED_HEADER =
            "<!-- GENERATED by /dev docs export - do not hand-edit -->\n";

    private DevDocsExporter() {}

    /**
     * Writes markdown and returns the absolute path written.
     *
     * @param resolveDescriptions when {@code true}, {@code descKey} values are resolved via the
     *                            server's registry (export command); when {@code false}, keys are emitted
     *                            literally (repo bootstrap without a running server).
     */
    public static Path export(@javax.annotation.Nullable MinecraftServer server) throws IOException {
        return export(server, true);
    }

    public static Path export(@javax.annotation.Nullable MinecraftServer server, boolean resolveDescriptions)
            throws IOException {
        Path gameDir = FMLPaths.GAMEDIR.get();
        Path target = resolveOutputPath(gameDir);
        Files.createDirectories(target.getParent());
        String markdown = generate(server, resolveDescriptions);
        Files.writeString(target, markdown, StandardCharsets.UTF_8);
        return target.toAbsolutePath().normalize();
    }

    public static Path resolveOutputPath(Path gameDir) {
        Path docsSibling = gameDir.getParent().resolve("docs").resolve("DEV_COMMANDS.md");
        if (Files.isDirectory(docsSibling.getParent())) {
            return docsSibling;
        }
        return gameDir.resolve("eclipse-dev-commands.md");
    }

    public static String generate(@javax.annotation.Nullable MinecraftServer server) {
        return generate(server, server != null);
    }

    public static String generate(@javax.annotation.Nullable MinecraftServer server, boolean resolveDescriptions) {
        StringBuilder out = new StringBuilder(8192);
        out.append(GENERATED_HEADER);
        out.append("# Eclipse Dev Commands\n\n");
        out.append("Operator reference for `/dev` and legacy admin roots. Regenerate with `/dev docs export`.\n\n");

        Map<DevCategory, List<DevCommandDoc>> grouped = new TreeMap<>(Comparator.comparing(Enum::name));
        for (DevCommandDoc doc : DevCommandRegistry.all()) {
            if (doc.legacy()) {
                continue;
            }
            grouped.computeIfAbsent(doc.category(), k -> new ArrayList<>()).add(doc);
        }
        for (Map.Entry<DevCategory, List<DevCommandDoc>> entry : grouped.entrySet()) {
            out.append("## ").append(categoryTitle(entry.getKey())).append("\n\n");
            List<DevCommandDoc> docs = entry.getValue();
            docs.sort(Comparator.comparing(DevCommandDoc::syntax));
            for (DevCommandDoc doc : docs) {
                appendDocLine(out, doc, server, resolveDescriptions);
            }
            out.append("\n");
        }

        out.append("## Legacy `/eclipse` and reference roots\n\n");
        out.append("Permission level **3** unless noted. Prefer polished `/dev` equivalents when available.\n\n");
        List<DevCommandDoc> legacy = DevCommandRegistry.all().stream().filter(DevCommandDoc::legacy).toList();
        legacy = new ArrayList<>(legacy);
        legacy.sort(Comparator.comparing(DevCommandDoc::syntax));
        for (DevCommandDoc doc : legacy) {
            appendDocLine(out, doc, server, resolveDescriptions);
        }
        out.append("\n");

        out.append("## Config reference\n\n");
        out.append("| File | Purpose | Layer | Reload step |\n");
        out.append("|------|---------|-------|-------------|\n");
        for (ConfigRefEntry ref : DevReload.configReferences()) {
            out.append("| `").append(ref.file()).append("` | ");
            out.append(describe(ref.purposeKey(), server, resolveDescriptions)).append(" | ");
            out.append(describe(ref.layerKey(), server, resolveDescriptions)).append(" | ");
            if (ref.reloadStep() == 0) {
                out.append("manual `/reload` |\n");
            } else if (ref.reloadStep() == 6) {
                out.append("hint only (vanilla `/reload`) |\n");
            } else {
                out.append(ref.reloadStep()).append(" (`/dev reload`) |\n");
            }
        }
        out.append("\n");

        out.append("## Dev blocks & items\n\n");
        out.append("- **Display Wand** — `/dev display give` (P5-W6). Vanilla `block_display` placer; ");
        out.append("Axiom is not available for NeoForge 1.21.1; wand + commands are the supported editor.\n");

        return out.toString();
    }

    private static void appendDocLine(StringBuilder out, DevCommandDoc doc, @javax.annotation.Nullable MinecraftServer server,
            boolean resolveDescriptions) {
        out.append("- `").append(doc.syntax()).append("` — ");
        out.append(describe(doc.descKey(), server, resolveDescriptions));
        out.append(" · perm **").append(doc.permission()).append("**");
        if (doc.legacy()) {
            out.append(" · *legacy*");
        }
        if (doc.danger() != Danger.SAFE) {
            out.append(" · *").append(doc.danger().name().toLowerCase(Locale.ROOT)).append("*");
        }
        out.append("\n");
    }

    private static String categoryTitle(DevCategory category) {
        return switch (category) {
            case EVENT -> "Event";
            case TIMER -> "Timer";
            case BUFFS -> "Buffs";
            case QUESTS -> "Quests";
            case PLAYERS -> "Players";
            case STAGE -> "Stage";
            case DISPLAY -> "Display";
            case SPAWN -> "Spawn";
            case XBOX -> "Xbox event";
            case MODS -> "Mods";
            case MUSIC -> "Music";
            case CONFIG -> "Config & handbook";
            case ANALYTICS -> "Analytics";
            case CUTSCENE -> "Cutscene";
            case LEGACY -> "Legacy";
        };
    }

    private static String describe(String key, @javax.annotation.Nullable MinecraftServer server,
            boolean resolveDescriptions) {
        if (!resolveDescriptions || server == null) {
            return key;
        }
        return net.minecraft.network.chat.Component.translatable(key).getString();
    }
}
