package dev.projecteclipse.eclipse.client.entity.player;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.core.config.EclipseClientConfig;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.player.AbstractClientPlayer;
import net.minecraft.client.renderer.LightTexture;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.RenderLayerParent;
import net.minecraft.client.renderer.entity.layers.RenderLayer;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.FastColor;
import net.minecraft.util.Mth;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;

/**
 * Emissive pass for the uniform "Purple Mythic" player skin (plans_v3 P6 §2.7): re-renders
 * the whole player model with {@code RenderType.eyes} (Ferryman/Herald skipDraw-family
 * pattern — vanilla render type, Veil-compatible, self-disabling under nothing) over a
 * dedicated glow texture that carries ONLY the heart, energy veins and eyes. Everything
 * else in that texture is transparent, so just those pixels draw — fullbright at any light
 * level, alpha-graded so forks glow softer than the heart core.
 *
 * <p><strong>WB-GHOSTFX upgrades</strong> (both {@code reducedFx}-gated, both allocation-free):</p>
 * <ul>
 *   <li><b>Heartbeat pulse</b>: the glow pass alpha breathes {@value #PULSE_MIN}→1.0 on a
 *       slow ~2 s sine ({@value #PULSE_PERIOD_TICKS} ticks), phase-offset per entity id so
 *       a crowd never throbs in lockstep. Under {@code reducedFx} the glow holds steady at
 *       full strength (no pulsing overlays, per the config comment).</li>
 *   <li><b>Occasional lightning arcs</b>: every 6–12 s per player (deterministic — one
 *       burst per {@value #ARC_WINDOW_TICKS}-tick window at a hashed offset within the
 *       first {@value #ARC_OFFSET_RANGE_TICKS} ticks, so consecutive bursts land 120–240
 *       ticks apart) a {@value #ARC_BURST_TICKS}-tick additive flicker frame-switches
 *       through the three sparse {@code eclipsed_player_arcs_N.png} overlays (generated by
 *       {@code scripts/skin_gen/eclipsed_player_v2.py}). Alpha stays ≤ ~0.6 and tapers over
 *       the burst — a brief vein-crawl, not a strobe.</li>
 * </ul>
 *
 * <p>OFF-safe by design (no config): if {@code eclipsed_player_glow.png} is missing from
 * resources the layer no-ops forever after one warning, and the albedo skin still carries
 * bright heart/vein pixels (Iris-shaderpack fallback per plan §5). Missing arc frames only
 * disable the arc pass (one warning), never the base glow. Skips invisible players so the
 * glow can never betray a potion-invisible teammate.</p>
 */
@OnlyIn(Dist.CLIENT)
public class EclipsedPlayerGlowLayer extends RenderLayer<AbstractClientPlayer, PlayerModel<AbstractClientPlayer>> {
    public static final ResourceLocation GLOW_TEXTURE = ResourceLocation.fromNamespaceAndPath(
            EclipseMod.MOD_ID, "textures/entity/eclipsed_player_glow.png");
    private static final RenderType GLOW_RENDER_TYPE = RenderType.eyes(GLOW_TEXTURE);

    /** Arc overlay frames — sparse bolts only, transparent elsewhere (skin-gen script). */
    private static final ResourceLocation[] ARC_TEXTURES = {
            arcTexture(0), arcTexture(1), arcTexture(2)};
    private static final RenderType[] ARC_RENDER_TYPES = {
            RenderType.eyes(ARC_TEXTURES[0]), RenderType.eyes(ARC_TEXTURES[1]),
            RenderType.eyes(ARC_TEXTURES[2])};

    /** Heartbeat pulse floor (peak is 1.0) — subtle breathing, never a blink. */
    private static final float PULSE_MIN = 0.75F;
    /** ~2 s heartbeat (40 ticks at 20 TPS). */
    private static final int PULSE_PERIOD_TICKS = 40;

    /** One arc burst per 9 s window, offset-hashed inside the window's first 3 s. */
    private static final int ARC_WINDOW_TICKS = 180;
    /** Offset range: consecutive burst starts land 120–240 ticks (6–12 s) apart. */
    private static final int ARC_OFFSET_RANGE_TICKS = 60;
    /** Burst length (~350 ms) — brief by design. */
    private static final int ARC_BURST_TICKS = 7;
    /** Arc frame-switch cadence within a burst (crawl read, not strobe). */
    private static final int ARC_FRAME_TICKS = 2;

    /** Lazily resolved once; {@code null} = not checked yet (resources not ready at ctor). */
    private static volatile Boolean glowTexturePresent;
    /** Lazily resolved once for all three arc frames together. */
    private static volatile Boolean arcTexturesPresent;

    public EclipsedPlayerGlowLayer(RenderLayerParent<AbstractClientPlayer, PlayerModel<AbstractClientPlayer>> parent) {
        super(parent);
    }

    private static ResourceLocation arcTexture(int index) {
        return ResourceLocation.fromNamespaceAndPath(
                EclipseMod.MOD_ID, "textures/entity/eclipsed_player_arcs_" + index + ".png");
    }

    /** Shared with {@code GhostPlayerRenderer}'s heart-glow pass (same skin family). */
    public static boolean glowTextureAvailable() {
        Boolean present = glowTexturePresent;
        if (present == null) {
            present = Minecraft.getInstance().getResourceManager().getResource(GLOW_TEXTURE).isPresent();
            if (!present) {
                EclipseMod.LOGGER.warn("[skin v2] {} missing — player glow layer disabled (albedo fallback only)",
                        GLOW_TEXTURE);
            }
            glowTexturePresent = present;
        }
        return present;
    }

    private static boolean arcTexturesAvailable() {
        Boolean present = arcTexturesPresent;
        if (present == null) {
            present = true;
            for (ResourceLocation texture : ARC_TEXTURES) {
                if (Minecraft.getInstance().getResourceManager().getResource(texture).isEmpty()) {
                    present = false;
                    EclipseMod.LOGGER.warn("[skin v2] {} missing — lightning-arc flicker disabled", texture);
                    break;
                }
            }
            arcTexturesPresent = present;
        }
        return present;
    }

    /**
     * The slow heartbeat: sin-based alpha {@code min}→{@code max} over ~2 s, phase-offset
     * by entity id. Public so the ghost renderer breathes on the same clock.
     */
    public static float heartbeatAlpha(int entityId, float time, float min, float max) {
        float phase = hash(entityId, 0x48B2A7) & 63; // 0..63-tick offset — desyncs players
        float sin = Mth.sin((time + phase) * (Mth.TWO_PI / PULSE_PERIOD_TICKS));
        return (min + max) * 0.5F + (max - min) * 0.5F * sin;
    }

    @Override
    public void render(PoseStack poseStack, MultiBufferSource bufferSource, int packedLight,
            AbstractClientPlayer player, float limbSwing, float limbSwingAmount, float partialTick,
            float ageInTicks, float netHeadYaw, float headPitch) {
        if (player.isInvisible() || !glowTextureAvailable()) {
            return;
        }
        boolean reduced = EclipseClientConfig.reducedFx();
        float alpha = reduced ? 1.0F
                : heartbeatAlpha(player.getId(), player.tickCount + partialTick, PULSE_MIN, 1.0F);
        VertexConsumer buffer = bufferSource.getBuffer(GLOW_RENDER_TYPE);
        this.getParentModel().renderToBuffer(poseStack, buffer,
                LightTexture.FULL_BRIGHT, OverlayTexture.NO_OVERLAY,
                FastColor.ARGB32.colorFromFloat(alpha, 1.0F, 1.0F, 1.0F));

        if (reduced || !arcTexturesAvailable()) {
            return; // reducedFx: steady glow only — no flicker overlays
        }
        int burstTick = arcBurstTick(player.getId(), player.tickCount);
        if (burstTick < 0) {
            return;
        }
        int slice = burstTick / ARC_FRAME_TICKS;
        int frame = Math.floorMod(hash(player.getId(), slice * 0x1F0F1), ARC_RENDER_TYPES.length);
        // Taper over the burst + a small per-slice shimmer; peaks ~0.6, dies out ~0.3.
        float fade = 1.0F - burstTick / (float) ARC_BURST_TICKS;
        float arcAlpha = 0.28F + 0.25F * fade + (hash(player.getId(), slice) & 0xFF) / 255.0F * 0.08F;
        VertexConsumer arcBuffer = bufferSource.getBuffer(ARC_RENDER_TYPES[frame]);
        this.getParentModel().renderToBuffer(poseStack, arcBuffer,
                LightTexture.FULL_BRIGHT, OverlayTexture.NO_OVERLAY,
                FastColor.ARGB32.colorFromFloat(arcAlpha, 1.0F, 1.0F, 1.0F));
    }

    /**
     * Ticks into the current arc burst ({@code 0..ARC_BURST_TICKS-1}), or {@code -1} while
     * idle. Fully deterministic in (entityId, tickCount): the per-entity offset desyncs
     * players, the per-window hash jitters each burst inside its window. Offsets stay
     * below {@code ARC_OFFSET_RANGE_TICKS + ARC_BURST_TICKS < ARC_WINDOW_TICKS}, so a
     * burst can never straddle a window edge.
     */
    private static int arcBurstTick(int entityId, int tickCount) {
        int time = tickCount + Math.floorMod(hash(entityId, 0x0FF5E7), ARC_WINDOW_TICKS);
        int window = time / ARC_WINDOW_TICKS;
        int start = window * ARC_WINDOW_TICKS + Math.floorMod(hash(entityId, window), ARC_OFFSET_RANGE_TICKS);
        int into = time - start;
        return into >= 0 && into < ARC_BURST_TICKS ? into : -1;
    }

    /** Small deterministic mix (skin-generator family) — stable pulse/arc phases per entity. */
    private static int hash(int a, int b) {
        int h = (a * 0x27D4EB2D) ^ (b * 0x9E3779B9) ^ 0x0EC15C1E;
        h ^= h >>> 15;
        h *= 0x2C1B3C6D;
        h ^= h >>> 12;
        return h;
    }
}
