package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * F-075 V2 "Insel-Aura" — {@link PhotonFxRegistry} row registrar for the island-SCALE
 * aura layers ({@link AltarAuraFxRows} reference pattern; own class, the shared
 * registrars and the V1 rows stay untouched). Assets are generated by
 * {@code tools/photon/altar_aura2_fx.py}.
 *
 * <p>Five LOOP rows under the WINDOWED-only law (INTEGRATION.md §4) — the ONLY driver
 * is {@code client/drama/AltarAuraIdle}, whose windows carry min/max stage bounds so
 * each family TIER-SWAPS (exactly one rim and one spiral executor is ever live):</p>
 * <ul>
 *   <li>{@link #CUE_ALTAR_AURA_RIM_LO} — stage 1–2 island-edge ring (r ≈ 15.5):
 *       sparse deep-violet rising motes + rim fog skirt.</li>
 *   <li>{@link #CUE_ALTAR_AURA_RIM_MID} — stage 3–4 rim: denser/taller, gold flecks,
 *       pillar-ring up-streamers.</li>
 *   <li>{@link #CUE_ALTAR_AURA_RIM_HI} — stage 5 rim: full density, gold crests.</li>
 *   <li>{@link #CUE_ALTAR_AURA_SPIRAL_LO} — stage 2–3: two dim spiral streams
 *       converging rim → altar crown.</li>
 *   <li>{@link #CUE_ALTAR_AURA_SPIRAL_HI} — stage 4+: four bright arms, longer
 *       ribbons.</li>
 * </ul>
 *
 * <p>Plus TWO one-shot rows, dispatched client-locally by
 * {@code client/drama/AltarCeremonyFx} through {@code PhotonFxRegistry.dispatch}
 * (no new network payloads: both ride the shipped {@code FX_ALTAR_LEVELUP}
 * ceremony). Channel {@code SEQUENCE} like every ceremony spawn:</p>
 * <ul>
 *   <li>{@link #CUE_ALTAR_AURA_POWERUP} — the stage-up beat (ground ring wave
 *       altar → rim + crown flash + spark rain), fired at the ceremony impact.</li>
 *   <li>{@link #CUE_ALTAR_STAGEUP_SHOCKWAVE} — FX-Wave-13 A7: the monument-origin
 *       shock crest whose ring-whip glints ride the GeckoLib {@code stage_up}
 *       one-shot (2.5 s). Fired at ceremony t=0 — the server triggers the anim and
 *       sends the payload in the same tick, so the asset's per-emitter
 *       {@code startDelay}s (8/10/12/14/26 t) land exactly on the animation's
 *       glow-flash and ring-pop keyframes (generated by
 *       {@code tools/photon/fx_altar.py}, timeline in its docstring).</li>
 * </ul>
 *
 * <p>{@code quasarEmitter} is {@code null} on every row by design (Photon-only garnish
 * is legal for NEW cues — the pre-row baseline was nothing): the shipped Quasar idle
 * stack and the {@code AltarCeremonyFx} composition ARE the photon-less reads and keep
 * running unchanged (Mode.LAYER). Photon absent / reducedFx / budget refusal ⇒ the
 * island looks exactly like it does today.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class AltarAura2FxRows {
    /** Stage 1–2 rim ring ({@code eclipse:altar_aura_rim_lo}). */
    public static final ResourceLocation CUE_ALTAR_AURA_RIM_LO = FxCues.cue("altar_aura_rim_lo");
    /** Stage 3–4 rim ring ({@code eclipse:altar_aura_rim_mid}). */
    public static final ResourceLocation CUE_ALTAR_AURA_RIM_MID = FxCues.cue("altar_aura_rim_mid");
    /** Stage 5 rim ring ({@code eclipse:altar_aura_rim_hi}). */
    public static final ResourceLocation CUE_ALTAR_AURA_RIM_HI = FxCues.cue("altar_aura_rim_hi");
    /** Stage 2–3 converging spiral streams ({@code eclipse:altar_aura_spiral_lo}). */
    public static final ResourceLocation CUE_ALTAR_AURA_SPIRAL_LO = FxCues.cue("altar_aura_spiral_lo");
    /** Stage 4+ converging spiral streams ({@code eclipse:altar_aura_spiral_hi}). */
    public static final ResourceLocation CUE_ALTAR_AURA_SPIRAL_HI = FxCues.cue("altar_aura_spiral_hi");
    /** ONE-SHOT stage-up beat ({@code eclipse:altar_aura_powerup}) — ceremony-fired. */
    public static final ResourceLocation CUE_ALTAR_AURA_POWERUP = FxCues.cue("altar_aura_powerup");
    /** ONE-SHOT anim-synced monument shockwave ({@code eclipse:altar_stageup_shockwave}). */
    public static final ResourceLocation CUE_ALTAR_STAGEUP_SHOCKWAVE = FxCues.cue("altar_stageup_shockwave");

    private AltarAura2FxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        registerLoopRow(CUE_ALTAR_AURA_RIM_LO, "altar_aura_rim_lo");
        registerLoopRow(CUE_ALTAR_AURA_RIM_MID, "altar_aura_rim_mid");
        registerLoopRow(CUE_ALTAR_AURA_RIM_HI, "altar_aura_rim_hi");
        registerLoopRow(CUE_ALTAR_AURA_SPIRAL_LO, "altar_aura_spiral_lo");
        registerLoopRow(CUE_ALTAR_AURA_SPIRAL_HI, "altar_aura_spiral_hi");
        // The stage-up beat: a plain one-shot spawn, charged to the ceremony channel.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_ALTAR_AURA_POWERUP,
                ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, "altar_aura_powerup"),
                null,
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false));
        // A7: the anim-synced monument shockwave — same one-shot shape as the powerup.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_ALTAR_STAGEUP_SHOCKWAVE,
                ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, "altar_stageup_shockwave"),
                null,
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false));
    }

    private static void registerLoopRow(ResourceLocation cue, String fxPath) {
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                cue,
                ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, fxPath),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }
}
