package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * PH-ALTAR's {@link PhotonFxRegistry} row registrar ({@link PhotonFxRows} reference
 * pattern). Assets are generated by {@code tools/photon/fx_altar.py}.
 *
 * <p>One row: {@code CUE_ALTAR_CORONA_IDLE} — the idle L5 corona ribbons
 * (IDEAS-world.md #9), a loop row under the WINDOWED-only law (INTEGRATION.md §4):
 * payload-firing it is a warned no-op; the ONLY driver is the
 * {@code client/drama/AltarCoronaIdle} hysteresis window
 * ({@code ensureLoop}/{@code releaseLoop}). {@code quasarEmitter} is {@code null} by
 * design — the shipped Quasar idle stack ({@code AltarIdleMotes} level-scaled motes +
 * halo patches + helix, {@code SanctumLightfall}, {@code AltarVeilSky}) keeps running
 * unchanged (Mode.LAYER), so photon-less clients keep today's full L5 read.</p>
 *
 * <p>PH-ALTAR's other two effects deliberately have NO row here: {@code altar_levelup}
 * rides the shipped {@code PhotonBridge.enhanceQuasarCue(ALTAR_LEVELUP_RING)} seam and
 * {@code offering_swallow_soul} is spawned client-locally from
 * {@code OfferingSwallowFx.beginFlight} (needs {@code allowMulti=true}, which payload
 * dispatch does not carry) — both are the sanctioned non-registry shapes
 * (INTEGRATION.md §3 rule 4).</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class AltarPhotonFxRows {
    private AltarPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_ALTAR_CORONA_IDLE,
                fx("altar_corona_idle"),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
