package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * F-075 "Stufen-Aura der Altar-Insel" — {@link PhotonFxRegistry} row registrar
 * ({@link AltarPhotonFxRows} reference pattern; own class, the shared registrars stay
 * untouched). Assets are generated by {@code tools/photon/altar_aura_fx.py}.
 *
 * <p>Four LOOP rows under the WINDOWED-only law (INTEGRATION.md §4) — payload-firing
 * any of them is a warned no-op; the ONLY driver is the
 * {@code client/drama/AltarAuraIdle} hysteresis-window controller
 * ({@code ensureLoop}/{@code releaseLoop} off the {@code ALTAR_CENTER} anchor and the
 * synced altar level):</p>
 * <ul>
 *   <li>{@link #CUE_ALTAR_AURA_MOTES} — stage 1+ near-field baseline: rising violet
 *       motes + thin ground-fog ring.</li>
 *   <li>{@link #CUE_ALTAR_AURA_GLYPHS} — stage 2+ near-field: orbiting rune-spark band
 *       + slow ground ring pulse.</li>
 *   <li>{@link #CUE_ALTAR_AURA_PILLAR} — stage 2+ FAR tell (&lt; 200): one soft
 *       pulsing light column over the altar.</li>
 *   <li>{@link #CUE_ALTAR_AURA_BANDS} — stage 4+ near-field: two counter-orbiting
 *       tilted light bands + occasional energy arcs.</li>
 * </ul>
 *
 * <p>{@code quasarEmitter} is {@code null} on every row by design (Photon-only garnish
 * is legal for NEW cues — the pre-row baseline was nothing): the shipped Quasar idle
 * stack ({@code AltarIdleMotes} level-scaled motes + halo patches + helix,
 * {@code SanctumLightfall}, {@code AltarVeilSky}) IS the photon-less read and keeps
 * running unchanged (Mode.LAYER). Photon absent / reducedFx / budget refusal ⇒ the
 * island looks exactly like it does today.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class AltarAuraFxRows {
    /** Stage 1+ baseline: rising motes + ground-fog ring ({@code eclipse:altar_aura_motes}). */
    public static final ResourceLocation CUE_ALTAR_AURA_MOTES = FxCues.cue("altar_aura_motes");
    /** Stage 2+: rune-spark orbit + ground ring pulse ({@code eclipse:altar_aura_glyphs}). */
    public static final ResourceLocation CUE_ALTAR_AURA_GLYPHS = FxCues.cue("altar_aura_glyphs");
    /** Stage 2+ far tell: soft light column ({@code eclipse:altar_aura_pillar}). */
    public static final ResourceLocation CUE_ALTAR_AURA_PILLAR = FxCues.cue("altar_aura_pillar");
    /** Stage 4+: orbit bands + energy arcs ({@code eclipse:altar_aura_bands}). */
    public static final ResourceLocation CUE_ALTAR_AURA_BANDS = FxCues.cue("altar_aura_bands");

    private AltarAuraFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        registerLoopRow(CUE_ALTAR_AURA_MOTES, "altar_aura_motes");
        registerLoopRow(CUE_ALTAR_AURA_GLYPHS, "altar_aura_glyphs");
        registerLoopRow(CUE_ALTAR_AURA_PILLAR, "altar_aura_pillar");
        registerLoopRow(CUE_ALTAR_AURA_BANDS, "altar_aura_bands");
    }

    private static void registerLoopRow(ResourceLocation cue, String fxPath) {
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                cue,
                ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, fxPath),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }
}
