package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * NEWFX-D's {@link PhotonFxRegistry} registrar and the package's shared asset-id table
 * (PLAN-NEWFX §2 D1–D5, "client atmosphere &amp; transit"). Assets are generated by
 * {@code tools/photon/newfx_d.py} (fxlib, the committed source for the five
 * {@code assets/eclipse/fx/*.fx} blobs) with Quasar stand-ins under
 * {@code assets/eclipse/quasar/emitters/}.
 *
 * <p><b>Why only ONE row lives here</b> — the registry's loop lane is a single
 * position-anchored {@code LoopState} per logical id, and its one-shot lane exists for
 * cues that cross the wire. Four of the five D effects legally fit neither and are
 * spawned directly by their controllers through {@link PhotonBridge}/{@link QuasarSpawner}
 * (every guard/budget law still applies — both entry points enforce them internally):</p>
 * <ul>
 *   <li><b>D1</b> {@code border/client/FirstContactSeam}: client-latched one-shot (no
 *       cue crosses the wire — a row would only add a table hop).</li>
 *   <li><b>D2</b> {@code network/breach/DriftCocoon}: entity-attached loop on the LOCAL
 *       player ({@code PhotonBridge.ensureAttachedFx} — rows are position-anchored).</li>
 *   <li><b>D3</b> {@code veilfx/rift/RiftDrawIn}: one loop PER rift anchor, ≤2
 *       concurrent (the {@code storm_crown_halo} per-anchor {@code LoopHandle} law).</li>
 *   <li><b>D4</b> {@code veilfx/TotalityPeakFx}: client-latched one-shot at the sun
 *       bearing (same reasoning as D1).</li>
 * </ul>
 *
 * <p><b>D5</b> {@code stormfx/StormApproachFx} drives the registered row: ONE
 * position-anchored Photon wind-ribbon loop, WINDOWED-only (INTEGRATION.md §4) on the
 * outside-approach hysteresis ({@code approach > 0.5} engage, {@code < 0.3} release,
 * re-anchor = release + re-ensure). The row's Quasar leg is {@code null} BY DESIGN:
 * the photon-less baseline is the controller's own budget-charged outrunner-wisp
 * cadence (STORM channel), which keeps running for everyone — registering it on the
 * row too would double-spawn the baseline whenever Photon is present.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class AtmospherePhotonFxRows {
    // ------------------------------------------------------------------ Photon assets
    /** D1 — floor-to-sky datamosh hairline at the ring bearing (~2 s one-shot). */
    public static final ResourceLocation FX_BORDER_FIRST_CONTACT = fx("border_first_contact");
    /** D2 — glitch-ember cocoon riding the drift faller (entity-attached loop). */
    public static final ResourceLocation FX_BREACH_DRIFT_COCOON = fx("breach_drift_cocoon");
    /** D3 — portal ambient draw-in streamers (per-anchor windowed loop). */
    public static final ResourceLocation FX_PORTAL_DRAW_IN = fx("portal_draw_in");
    /** D4 — totality-peak diamond-ring bead (one-shot at the sun bearing). */
    public static final ResourceLocation FX_TOTALITY_DIAMOND_RING = fx("totality_diamond_ring");
    /** D5 — torn head-height wind ribbon (the registered loop row's Photon leg). */
    public static final ResourceLocation FX_STORM_OUTRUNNERS = fx("storm_outrunners");

    // ------------------------------------------------------------------ Quasar stand-ins
    /** D1 fallback — thin static-mote column + shard pops (LAYER leg, always plays). */
    public static final ResourceLocation QUASAR_FIRST_CONTACT_HAIRLINE =
            quasar("border_first_contact_hairline");
    /** D2 stand-in — orbiting glitch-ember motes attached to the faller (REPLACE). */
    public static final ResourceLocation QUASAR_DRIFT_COCOON_ORBIT =
            quasar("breach_drift_cocoon_orbit");
    /** D3 stand-in — motes pulled INTO the rift plane by a point attractor (REPLACE). */
    public static final ResourceLocation QUASAR_PORTAL_DRAW_IN_MOTES =
            quasar("portal_draw_in_motes");
    /** D4 fallback — one bright glint pop + short streak arc (LAYER leg). */
    public static final ResourceLocation QUASAR_DIAMOND_RING_GLINT =
            quasar("totality_diamond_glint");
    /** D5 baseline — ragged gray rag shedder ridden by StormApproachFx's runner heads. */
    public static final ResourceLocation QUASAR_STORM_OUTRUNNER_WISP =
            quasar("storm_outrunner_wisp");

    private AtmospherePhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // D5 — the package's only registry row (see class javadoc for why D1–D4 bypass).
        // WINDOWED-only: payload-firing is a warned no-op; StormApproachFx owns the window.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_STORM_OUTRUNNERS,
                FX_STORM_OUTRUNNERS,
                null,
                FxBudget.Channel.STORM,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }

    private static ResourceLocation quasar(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
