package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * Asset table + {@link PhotonFxRegistry} row registrar of the day-2 nether-opening show
 * ({@code sequence.NetherOpeningSequence}). Assets are generated by
 * {@code tools/photon/nether_open_fx.py} (fxlib, the committed source for the four
 * {@code assets/eclipse/fx/nether_*.fx} blobs).
 *
 * <p><b>Why only ONE row lives here</b> (the {@link AtmospherePhotonFxRows} precedent): the
 * registry's one-shot lane exists for cues that cross the wire on the shared
 * {@code S2CFxEventPayload}, but this feature ships its own beat payload
 * ({@code S2CNetherOpenPayload}) — the three one-shots are therefore spawned directly by
 * {@code client.nether.NetherOpenClientFx} through {@link PhotonBridge} (every guard and
 * budget law still applies: the bridge enforces them internally). Only the permanent plume
 * is a registry row, because it is a WINDOWED loop and the registry owns loop bookkeeping.</p>
 *
 * <p>The plume row's Quasar leg is {@code null} BY DESIGN (the {@code WorldPhotonFxRows}
 * degradation law): the photon-less baseline over the opened pit is the shipped server
 * ambience ({@code BreachTransferService.ambientTick}'s CAMPFIRE/SOUL_FIRE ring plus the
 * existing {@code BreachAmbience} geyser loops) and it keeps running unchanged for everyone.
 * Registering a NEW Quasar emitter as a fallback would CHANGE photon-less visuals.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class NetherOpenPhotonFxRows {
    /** Phase 1 — ash welling out of the still-closed ground (~240 t one-shot). */
    public static final ResourceLocation FX_NETHER_OMEN_ASH = fx("nether_omen_ash");
    /** Phase 2 — ONE glowing ground crack; the client stamps several, each with its yaw. */
    public static final ResourceLocation FX_NETHER_QUAKE_FISSURE = fx("nether_quake_fissure");
    /** Phase 3 — fire column + colliding shrapnel + smoke pillar + shock ring (~200 t). */
    public static final ResourceLocation FX_NETHER_ERUPTION = fx("nether_eruption");
    /** Phase 4 — the permanent smoke-and-fire cloud over the pit (WINDOWED loop). */
    public static final ResourceLocation FX_NETHER_PIT_PLUME = fx("nether_pit_plume");

    /**
     * Logical cue id of the plume loop row. Minted through {@link FxCues#cue} so it obeys
     * the {@code eclipse:fx/cue/…} namespace law, but deliberately NOT declared in
     * {@code FxCues}: no server code ever references it — the loop is WINDOWED-only
     * (INTEGRATION.md §4) and never crosses the wire.
     */
    public static final ResourceLocation CUE_NETHER_PIT_PLUME = FxCues.cue("nether_pit_plume");

    private NetherOpenPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // WINDOWED-only: payload-firing this row is a warned no-op; the hysteresis window
        // lives in client/nether/NetherPitPlume.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_NETHER_PIT_PLUME,
                FX_NETHER_PIT_PLUME,
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
