package dev.projecteclipse.eclipse.veilfx;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.client.nether.NetherOpenClientFx;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * Asset table + {@link PhotonFxRegistry} row registrar of the day-2 nether-opening show
 * ({@code sequence.NetherOpeningSequence}). Assets are generated by
 * {@code tools/photon/nether_open_fx.py} (fxlib, the committed source for the
 * {@code assets/eclipse/fx/nether_*.fx} blobs).
 *
 * <p><b>Why almost no rows live here</b> (the {@link AtmospherePhotonFxRows} precedent):
 * the registry's one-shot lane exists for cues that cross the wire on the shared
 * {@code S2CFxEventPayload}, but this feature ships its own beat payload
 * ({@code S2CNetherOpenPayload}) — the phase one-shots are therefore spawned directly by
 * {@code client.nether.NetherOpenClientFx} through {@link PhotonBridge} (every guard and
 * budget law still applies: the bridge enforces them internally). The permanent plume and
 * the ash snow are registry rows because they are WINDOWED loops and the registry owns
 * loop bookkeeping; the F-102 tremor-slam beat is a row because it originates in
 * {@code sequence.NetherUpheavalFx} on the SHARED cue lane (the hop-wave slams are
 * pressure-timed server state that the phase payload cannot carry — the B7
 * {@code beat_nether_ember_tear} precedent).</p>
 *
 * <p>The plume row's Quasar leg is {@code null} BY DESIGN (the {@code WorldPhotonFxRows}
 * degradation law): the photon-less baseline over the opened pit is the shipped server
 * ambience ({@code BreachTransferService.ambientTick}'s CAMPFIRE/SOUL_FIRE ring plus the
 * existing {@code BreachAmbience} geyser loops) and it keeps running unchanged for everyone.
 * Registering a NEW Quasar emitter as a fallback would CHANGE photon-less visuals.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class NetherOpenPhotonFxRows {
    /** Phase 1 — ash veil cone over the still-closed ground (~240 t one-shot, F-102). */
    public static final ResourceLocation FX_NETHER_OMEN_ASH = fx("nether_omen_ash");
    /** Phase 2 — ONE glowing ground crack; the client stamps several, each with its yaw. */
    public static final ResourceLocation FX_NETHER_QUAKE_FISSURE = fx("nether_quake_fissure");
    /** Phase 2 — the quake carpet: popping Kiesel + boiling ground dust (360 t, F-102). */
    public static final ResourceLocation FX_NETHER_TREMOR_WAVES = fx("nether_tremor_waves");
    /** Phase 2 — ONE hop-wave-slam beat stamp: dust ring + Kiesel splash (50 t, F-102). */
    public static final ResourceLocation FX_NETHER_TREMOR_RING = fx("nether_tremor_ring");
    /** Phase 3 — ONE radial Riss-Glut-Speiche; the client stamps a star (130 t, F-102). */
    public static final ResourceLocation FX_NETHER_RUPTURE_SPOKE = fx("nether_rupture_spoke");
    /** Phase 3 — fire column + shrapnel + smoke pillar + F-102 mushroom cap (~200 t). */
    public static final ResourceLocation FX_NETHER_ERUPTION = fx("nether_eruption");
    /** Phase 4 — the permanent smoke-and-fire cloud over the pit (WINDOWED loop). */
    public static final ResourceLocation FX_NETHER_PIT_PLUME = fx("nether_pit_plume");
    /** Ambient — dark ash + träge Glutflocken around the pit (WINDOWED loop, W13/N11). */
    public static final ResourceLocation FX_NETHER_ASH_SNOW = fx("nether_ash_snow");

    /**
     * Logical cue id of the plume loop row. Minted through {@link FxCues#cue} so it obeys
     * the {@code eclipse:fx/cue/…} namespace law, but deliberately NOT declared in
     * {@code FxCues}: no server code ever references it — the loop is WINDOWED-only
     * (INTEGRATION.md §4) and never crosses the wire.
     */
    public static final ResourceLocation CUE_NETHER_PIT_PLUME = FxCues.cue("nether_pit_plume");
    /** Cue id of the ash-snow loop row — same WINDOWED-only law as the plume cue. */
    public static final ResourceLocation CUE_NETHER_ASH_SNOW = FxCues.cue("nether_ash_snow");
    /**
     * F-102 quake-beat cue: fired by {@code sequence.NetherUpheavalFx} the tick a hop
     * wave SLAMS back into the ground (rate-limited server-side), {@code a} = the quake
     * pressure 0..1 at that moment, {@code b} unused. Both sides derive the same
     * {@code FxCues.cue("nether_tremor_slam")} id (the CreditsSequence naming-contract
     * precedent — {@code FxCues.java} stays untouched); the wire format is the shipped
     * {@code S2CFxEventPayload}, nothing new.
     */
    public static final ResourceLocation CUE_NETHER_TREMOR_SLAM = FxCues.cue("nether_tremor_slam");

    private NetherOpenPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // WINDOWED-only: payload-firing these rows is a warned no-op; the hysteresis window
        // for BOTH loops lives in client/nether/NetherPitPlume (one probe, one window).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_NETHER_PIT_PLUME,
                FX_NETHER_PIT_PLUME,
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
        // Quasar leg null BY DESIGN, same degradation law as the plume row: the
        // photon-less baseline around the pit stays the shipped server ambience.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_NETHER_ASH_SNOW,
                FX_NETHER_ASH_SNOW,
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
        // F-102 tremor-slam beat: dust ring + Kiesel splash + camera kick, all off ONE
        // cue. Quasar leg null: the photon-less slam read is the server's own thud
        // sound + the hop-wave block displays themselves (they ARE the baseline).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                CUE_NETHER_TREMOR_SLAM,
                FX_NETHER_TREMOR_RING,
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                NetherOpenPhotonFxRows::tremorSlamLeg));
    }

    /**
     * Custom Photon leg of the slam cue: the camera kick fires FIRST and unconditionally
     * (it is not a Photon effect — reducedFx/photon-less clients still get the beat
     * FEEL), then the ring stamp rides the bridge's full guard chain. allowMulti because
     * successive slams land on the same crater anchor well inside the ring asset's ~50-t
     * life — Photon's same-anchor dedup would silently eat every second beat (the B7
     * end-crack precedent).
     */
    private static boolean tremorSlamLeg(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        NetherOpenClientFx.tremorSlamKick(pos, a);
        return PhotonBridge.spawn(photonFx, pos,
                PhotonBridge.SpawnOptions.DEFAULT.withAllowMulti(true));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
