package dev.projecteclipse.eclipse.veilfx;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * NEWFX-A's {@link PhotonFxRegistry} row registrar ({@link PhotonFxRows} reference
 * pattern) — the progression &amp; personal-celebration cues of PLAN-NEWFX §2 A1–A5
 * (quest sigil burst, collection tier halo, skill spark, landmark flare + echo, wizard
 * catalyst handover). Photon assets are generated by {@code tools/photon/newfx_a_fx.py}
 * (fxlib, the committed source for the eight NEWFX-A {@code assets/eclipse/fx/*.fx}
 * blobs); Quasar fallback emitters live in {@code assets/eclipse/quasar/emitters/}.
 *
 * <p>All one-shots are {@code Mode.LAYER}: the Quasar leg is the base composition every
 * client gets (and the photon-less fallback), the Photon leg adds the hero garnish
 * (HDR cores, physics shards, ribbons). Entity-lane rows carry custom {@code PhotonLeg}s
 * for anchor offsets and the payload-parameter choreography:</p>
 * <ul>
 *   <li><b>quest sigil</b> — {@code a} = goalKind ordinal; MAIN (0) plays the large
 *       variant (executor scale) and layers the one-beat {@code quest_sigil_pillar}
 *       (its impact delay is baked into the asset's {@code startDelay}).</li>
 *   <li><b>tier halo</b> — {@code a} = tier number → scale ladder; tier 4 (the first
 *       shard-paying tier) layers the brief {@code collection_tier_gold_rain}; tier ≥ 5
 *       graduates to the full C2 GOLD RUSH composition (V7-SIGCOMP,
 *       {@link SignatureCompositions#goldRush}).</li>
 *   <li><b>skill glint</b> — {@code a} = node cost → subtle glint scale (the Quasar
 *       sparks are the composition; the Photon leg is a near-invisible lens accent).</li>
 *   <li><b>landmark echo</b> — Photon-only garnish ({@code null} Quasar leg): reducedFx
 *       and photon-less clients get no echo per the A4 reduced spec.</li>
 *   <li><b>catalyst handover</b> — the leg owns BOTH halves: Photon on Orin plus a
 *       quality-gated Quasar indraw ({@code FxBudget.qualityTier() >= 2} only), because
 *       the A5 reduced spec is "existing vanilla END_ROD baseline only" — a row-driven
 *       Quasar leg would still play under reducedFx.</li>
 * </ul>
 *
 * <p>ReducedFx ladder (PLAN-NEWFX budget column): the Photon legs all die inside
 * {@code PhotonBridge.available()}; the registry-driven Quasar legs stay up at the
 * halved channel rates (A1/A2/A3/A4 reduced forms) — no code here needs to check tiers
 * except the A5 special case above.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class ProgressionPhotonFxRows {
    /** Eye→chest drop: where the A1 rune ring snaps open. */
    private static final Vec3 CHEST_OFFSET = new Vec3(0.0D, -0.4D, 0.0D);
    /** Eye→boots drop: the A2 halo starts at the boots and rises to the crown. */
    private static final Vec3 FEET_OFFSET = new Vec3(0.0D, -1.55D, 0.0D);
    /** Eye→hand drop: the A3 sparks orbit the spending hand. */
    private static final Vec3 HAND_OFFSET = new Vec3(0.0D, -0.6D, 0.0D);
    /** Eye→overhead rise: the A2 tier ≥ 4 gold rain sheds from just above the crown. */
    private static final Vec3 OVERHEAD_OFFSET = new Vec3(0.0D, 0.7D, 0.0D);
    /** Eye→staff-tip drop on Orin: the A5 fuse point. */
    private static final Vec3 STAFF_OFFSET = new Vec3(0.0D, -0.25D, 0.0D);

    /** MAIN goal variant scale (A1 "large variant"). */
    private static final double QUEST_MAIN_SCALE = 1.25D;
    /** A2 scale ladder: 0.9 + 0.08·tier, capped — tier 5 halos read bigger, never absurd. */
    private static final double HALO_BASE_SCALE = 0.9D;
    private static final double HALO_TIER_SCALE_STEP = 0.08D;
    private static final double HALO_MAX_SCALE = 1.3D;
    /** First tier that adds the gold rain (the FIX-ECON shard-paying tiers). */
    private static final int GOLD_RAIN_MIN_TIER = 4;
    /** V7-SIGCOMP C2: tier that graduates the reward layer to the full GOLD RUSH. */
    private static final int GOLD_RUSH_MIN_TIER = 5;
    /** V7-SIGCOMP C2: collection-context scale ladder (smaller than the podium's 1.15). */
    private static final double GOLD_RUSH_BASE_SCALE = 0.55D;
    private static final double GOLD_RUSH_TIER_SCALE_STEP = 0.07D;
    /** A3 glint scale ladder over node cost 1–3. */
    private static final double GLINT_BASE_SCALE = 0.85D;
    private static final double GLINT_COST_SCALE_STEP = 0.15D;

    private ProgressionPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // A1 — Decree Sigil Burst (entity lane; a = goalKind ordinal, MAIN = 0).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_QUEST_COMPLETE,
                fx("quest_sigil_burst"),
                fx("quest_sigil_ring"),
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                ProgressionPhotonFxRows::playQuestSigil));
        // A2 — Collection Tier Halo (entity lane; a = tier number).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_COLLECTION_TIER,
                fx("collection_tier_halo"),
                fx("collection_tier_halo"),
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                ProgressionPhotonFxRows::playTierHalo));
        // A3 — Skill Spark Column (entity lane; a = node cost; Quasar-first by spec —
        // the Photon leg is only the subtle lens glint).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SKILL_SPEND,
                fx("skill_spend_glint"),
                fx("skill_spend_spark"),
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                ProgressionPhotonFxRows::playSkillGlint));
        // A4 — Landmark Discovery Flare (position lane, default leg; SEQUENCE-grade:
        // rare, landmark-sized moment per the plan's budget column).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_LANDMARK_DISCOVERED,
                fx("landmark_flare"),
                fx("landmark_flare"),
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false));
        // A4 echo — discoverer's personal glint (entity lane, Photon-only garnish:
        // reducedFx/photon-less clients get no echo per the reduced spec).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_LANDMARK_ECHO,
                fx("landmark_echo"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                (photonFx, pos, entity, a, b) -> entity != null
                        ? PhotonBridge.spawnOnEntity(photonFx, entity,
                                PhotonBridge.AUTO_ROTATE_NONE, CHEST_OFFSET)
                        // Untracked target: feet anchor — chest ≈ +1.2.
                        : PhotonBridge.spawn(photonFx, pos,
                                PhotonBridge.SpawnOptions.DEFAULT.withOffset(0.0D, 1.2D, 0.0D))));
        // A5 — Catalyst Handover (entity lane on Orin; leg owns the quality-gated
        // Quasar half, see class javadoc).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_WIZARD_CATALYST,
                fx("wizard_catalyst_handover"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                ProgressionPhotonFxRows::playCatalystHandover));
    }

    /**
     * A1 leg: rune ring + glyph shatter at chest height; MAIN goals ({@code a} = 0) get
     * the {@value #QUEST_MAIN_SCALE}× variant plus the one-beat light pillar (the pillar
     * asset's own {@code startDelay} lands it on the shatter impact frame).
     */
    private static boolean playQuestSigil(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        boolean main = a < 0.5F;
        double scale = main ? QUEST_MAIN_SCALE : 1.0D;
        boolean played;
        if (entity != null) {
            played = PhotonBridge.spawnOnEntity(photonFx, entity, PhotonBridge.AUTO_ROTATE_NONE,
                    PhotonBridge.SpawnOptions.DEFAULT
                            .withOffset(CHEST_OFFSET.x, CHEST_OFFSET.y, CHEST_OFFSET.z)
                            .withScale(scale, scale, scale));
        } else {
            // Untracked target: the payload pos is the feet anchor — chest ≈ +1.2.
            played = PhotonBridge.spawn(photonFx, pos, PhotonBridge.SpawnOptions.DEFAULT
                    .withOffset(0.0D, 1.2D, 0.0D)
                    .withScale(scale, scale, scale));
        }
        if (main) {
            ResourceLocation pillar = fx("quest_sigil_pillar");
            if (entity != null) {
                PhotonBridge.spawnOnEntity(pillar, entity, PhotonBridge.AUTO_ROTATE_NONE, FEET_OFFSET);
            } else {
                PhotonBridge.spawn(pillar, pos);
            }
        }
        return played;
    }

    /**
     * A2 leg: boot→crown halo rise, scale laddered by tier; tier ≥
     * {@value #GOLD_RAIN_MIN_TIER} layers the brief overhead gold rain.
     */
    private static boolean playTierHalo(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        int tier = Math.max(1, Math.round(a));
        double scale = Math.min(HALO_MAX_SCALE, HALO_BASE_SCALE + HALO_TIER_SCALE_STEP * tier);
        boolean played;
        if (entity != null) {
            played = PhotonBridge.spawnOnEntity(photonFx, entity, PhotonBridge.AUTO_ROTATE_NONE,
                    PhotonBridge.SpawnOptions.DEFAULT
                            .withOffset(FEET_OFFSET.x, FEET_OFFSET.y, FEET_OFFSET.z)
                            .withScale(scale, scale, scale));
        } else {
            // Untracked target: the payload pos already IS the feet anchor.
            played = PhotonBridge.spawn(photonFx, pos,
                    PhotonBridge.SpawnOptions.DEFAULT.withScale(scale, scale, scale));
        }
        if (tier >= GOLD_RUSH_MIN_TIER) {
            // V7-SIGCOMP C2: the top collection tiers graduate from the plain gold rain
            // to the full GOLD RUSH composition (glint gather → flash frame → physics
            // star shards + trails), unlock-flavored sting behind the §6.5 window.
            Vec3 anchor = entity != null
                    ? entity.position().add(0.0D, 1.6D, 0.0D) : pos.add(0.0D, 1.6D, 0.0D);
            SignatureCompositions.goldRush(anchor, entity,
                    GOLD_RUSH_BASE_SCALE + GOLD_RUSH_TIER_SCALE_STEP * tier,
                    SignatureCompositions.Sting.UNLOCK);
        } else if (tier >= GOLD_RAIN_MIN_TIER) {
            ResourceLocation rain = fx("collection_tier_gold_rain");
            if (entity != null) {
                PhotonBridge.spawnOnEntity(rain, entity, PhotonBridge.AUTO_ROTATE_NONE, OVERHEAD_OFFSET);
            } else {
                PhotonBridge.spawn(rain, pos.add(0.0D, 2.3D, 0.0D));
            }
        }
        return played;
    }

    /** A3 leg: the near-invisible lens glint over the spending hand, scaled by cost. */
    private static boolean playSkillGlint(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        int cost = Math.min(3, Math.max(1, Math.round(a)));
        double scale = GLINT_BASE_SCALE + GLINT_COST_SCALE_STEP * cost;
        if (entity != null) {
            return PhotonBridge.spawnOnEntity(photonFx, entity, PhotonBridge.AUTO_ROTATE_NONE,
                    PhotonBridge.SpawnOptions.DEFAULT
                            .withOffset(HAND_OFFSET.x, HAND_OFFSET.y, HAND_OFFSET.z)
                            .withScale(scale, scale, scale));
        }
        // Untracked target: feet anchor — hand height ≈ +1.0.
        return PhotonBridge.spawn(photonFx, pos, PhotonBridge.SpawnOptions.DEFAULT
                .withOffset(0.0D, 1.0D, 0.0D)
                .withScale(scale, scale, scale));
    }

    /**
     * A5 leg: Photon handover choreography on Orin, plus the Quasar indraw base — spawned
     * HERE (not via the row) behind a full-quality gate, because the A5 reduced form is
     * "existing vanilla END_ROD baseline only" while a row-driven LAYER Quasar leg would
     * still play (rate-halved) under reducedFx.
     */
    private static boolean playCatalystHandover(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        if (FxBudget.qualityTier() >= 2) {
            // Staff-height anchor for the indraw wisps (the payload pos is Orin's feet).
            QuasarSpawner.spawnOrFallback(fx("wizard_catalyst_indraw"),
                    pos.add(0.0D, 1.2D, 0.0D), FxBudget.Channel.BURST);
        }
        if (entity != null) {
            return PhotonBridge.spawnOnEntity(photonFx, entity, PhotonBridge.AUTO_ROTATE_NONE,
                    STAFF_OFFSET);
        }
        // Untracked wizard: feet anchor — staff tip ≈ +1.4.
        return PhotonBridge.spawn(photonFx, pos,
                PhotonBridge.SpawnOptions.DEFAULT.withOffset(0.0D, 1.4D, 0.0D));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
