package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.S2CQuasarPayload;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * V7-SIGCOMP's {@link PhotonFxRegistry} row registrar ({@link PhotonFxRows} reference
 * pattern) — the FX-STYLE-GUIDE.md §5 signature-composition cues. Photon assets are
 * generated by {@code tools/photon/sig_fx.py} into the new {@code fx/sig/} folder (§4
 * naming law: {@code sig/} mirrors the shipped {@code boss/} precedent); Quasar fallback
 * emitters are the {@code sig_*} rows in {@code assets/eclipse/quasar/emitters/}.
 *
 * <ul>
 *   <li><b>C11 Crown Verdict</b> — REPLACE row (the Photon file IS the choreography; the
 *       Quasar leg is the fallback sketch) with the custom
 *       {@link SignatureCompositions#crownVerdictLeg} leg that claims the S-MAX world
 *       stage and scripts the screen/sound beats. SEQUENCE channel: boss deaths are
 *       scripted contexts (§5 C11 spend).</li>
 *   <li><b>C10 Deep Rumble</b> — WINDOWED-only loop row (never payload-fired), Photon
 *       dust/pebble bed with a Quasar mote stand-in (REPLACE: the stand-in runs only
 *       while the Photon leg is unavailable). AMBIENT channel — tier 0 kills it and the
 *       composition stays legible through sound alone ({@code DeepRumbleFx}).</li>
 * </ul>
 *
 * <p>Stage-class registrations (§6.1): the shipped {@code boss_slam} Quasar cue is
 * S-class so the {@code EclipsePayloads.handleQuasar} soft gate can demote its Photon
 * enhancement layer under a contested frame. {@code CUE_SIG_CROWN_VERDICT} is
 * deliberately NOT registered with the gate — its own leg claims S-MAX directly (a
 * gate claim would hold the token against the leg's claim of the same moment).</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class SignaturePhotonFxRows {
    /** Lease for the shipped boss_slam Quasar cue's S-class gate row (one burst read). */
    private static final int BOSS_SLAM_LEASE_TICKS = 40;

    private SignaturePhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // C11 — Crown Verdict (position lane; a = boss kind ordinal, b = 1 host indraw).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SIG_CROWN_VERDICT,
                fx("sig/crown_verdict"),
                fx("sig_crown_verdict_burst"),
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.REPLACE,
                false,
                SignatureCompositions::crownVerdictLeg));
        // C10 — Deep Rumble bed (WINDOWED-only; driven by client/drama/DeepRumbleFx).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SIG_DEEP_RUMBLE,
                fx("sig/deep_rumble_bed"),
                fx("sig_deep_rumble_motes"),
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.REPLACE,
                true));

        // §6.1 soft-gate classes for existing hero cues on the Quasar payload path.
        WorldStageArbiter.registerCue(S2CQuasarPayload.BOSS_SLAM,
                WorldStageArbiter.StageClass.S, BOSS_SLAM_LEASE_TICKS);
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
