package dev.projecteclipse.eclipse.veilfx;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * F-034/F-033's {@link PhotonFxRegistry} registrar for the storm near-field suite
 * (assets generated by {@code tools/photon/storm_nearfield_fx.py}). Four rows:
 *
 * <ul>
 *   <li><b>Three WINDOWED loop rows</b> (wisps / ground scud / updraft motes) — never
 *       payload-fired (INTEGRATION.md §4); {@code stormfx/StormNearfieldFx} owns the
 *       150–250-block LOD-handover window, drives {@code ensureLoop}/{@code releaseLoop}
 *       on the NEAREST eligible sphere storm and blends the authored emission rates
 *       with camera distance (Channel A). The Quasar legs are {@code null} BY DESIGN:
 *       the photon-less baseline is the existing Veil wall + volumetric handover,
 *       which keeps running for everyone.</li>
 *   <li><b>One one-shot row</b> ({@code storm_burst_shockwave}) with a custom leg:
 *       the asset is authored at the reference radius 24 ({@code StormRegistry
 *       .DEFAULT_RADIUS}), the cue's {@code a} parameter carries the live
 *       {@code radius / 24} which the leg forwards through
 *       {@code SpawnOptions.withScale}. {@code allowMulti} is forced — two storms
 *       may legitimately burst within the dedup window.</li>
 * </ul>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class StormNearfieldFxRows {
    /** F-034 — fast counter-rotating fog streaks racing around the wall at 1.04r. */
    public static final ResourceLocation FX_STORM_NEARFIELD_WISPS = fx("storm_nearfield_wisps");
    /** F-034 — ragged ground shreds + grit skimming the wall foot. */
    public static final ResourceLocation FX_STORM_GROUND_SCUD = fx("storm_ground_scud");
    /** F-034 — three standing updraft mote columns inside the wall (0.55r). */
    public static final ResourceLocation FX_STORM_UPDRAFT_MOTES = fx("storm_updraft_motes");
    /** F-033 stage 2 — the burst shockwave ring (double HDR ring + dust rim + sparks). */
    public static final ResourceLocation FX_STORM_BURST_SHOCKWAVE = fx("storm_burst_shockwave");

    /** Sane clamp for the shockwave's {@code a} scale parameter (radius 6..144 blocks). */
    private static final float SHOCKWAVE_SCALE_MIN = 0.25F;
    private static final float SHOCKWAVE_SCALE_MAX = 6.0F;

    private StormNearfieldFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // WINDOWED-only loop rows: payload-firing is a warned no-op; StormNearfieldFx
        // owns the window (see class javadoc for why the Quasar legs are null).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_STORM_NEARFIELD_WISPS, FX_STORM_NEARFIELD_WISPS,
                null, FxBudget.Channel.STORM, PhotonFxRegistry.Mode.LAYER, true));
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_STORM_GROUND_SCUD, FX_STORM_GROUND_SCUD,
                null, FxBudget.Channel.STORM, PhotonFxRegistry.Mode.LAYER, true));
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_STORM_UPDRAFT_MOTES, FX_STORM_UPDRAFT_MOTES,
                null, FxBudget.Channel.STORM, PhotonFxRegistry.Mode.LAYER, true));
        // One-shot shockwave: a = radius/24 executor scale through the custom leg.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_STORM_BURST_SHOCKWAVE, FX_STORM_BURST_SHOCKWAVE,
                null, FxBudget.Channel.STORM, PhotonFxRegistry.Mode.LAYER, false,
                (photonFx, pos, entity, a, b) -> {
                    double scale = Mth.clamp(a <= 0.0F ? 1.0F : a,
                            SHOCKWAVE_SCALE_MIN, SHOCKWAVE_SCALE_MAX);
                    return PhotonBridge.spawn(photonFx, pos, PhotonBridge.SpawnOptions.DEFAULT
                            .withAllowMulti(true)
                            .withScale(scale, scale, scale));
                }));
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
