package dev.projecteclipse.eclipse.veilfx;

import java.util.LinkedHashMap;
import java.util.Map;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.client.progression.ClientUnlockCache;
import dev.projecteclipse.eclipse.core.config.EclipseClientConfig;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import dev.projecteclipse.eclipse.worldgen.DiscProfile;
import dev.projecteclipse.eclipse.worldgen.FrozenParams;
import dev.projecteclipse.eclipse.worldgen.structure.DungeonDiscovery;
import dev.projecteclipse.eclipse.worldgen.structure.StructurePendingRegistry.PendingSite;
import dev.projecteclipse.eclipse.worldgen.structure.UndergroundSites;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.neoforge.client.event.ClientPlayerNetworkEvent;
import net.neoforged.neoforge.client.event.ClientTickEvent;

/**
 * NEWFX-C's {@link PhotonFxRegistry} row registrar ({@link PhotonFxRows} reference
 * pattern) — the world-event &amp; contest effects of PLAN-NEWFX §2 C1–C5 (summon
 * beacon, contract omen ripple, minigame gate fanfare + race finish ribbon, supply
 * herald, dungeon maw breath). Assets are generated by
 * {@code tools/photon/worldevents_fx.py}; Quasar fallbacks live under
 * {@code assets/eclipse/quasar/emitters/} — NEW emitters are legal fallbacks here
 * because every cue is new (pre-row baseline was nothing, the Row javadoc law).
 *
 * <p>Custom {@code PhotonLeg}s (INTEGRATION §3.5 — grows only when a cue needs it):</p>
 * <ul>
 *   <li><b>summon beacon</b> — picks one of four boss-tinted column assets by the
 *       payload's {@code a} kind ordinal and distance-scales the executor's X/Z so the
 *       hair-thin column stays readable from anywhere on the disc (Y stays 1: the
 *       column is authored mile-high). The row's Quasar pillar is a REAL row leg —
 *       reducedFx/photon-less clients keep the info.</li>
 *   <li><b>omen ripple / supply herald</b> — rows whose reduced spec is "skip
 *       ENTIRELY": the legs own BOTH halves (Quasar via {@code spawnOrFallback},
 *       Photon via the bridge) so a {@code reducedFx} client plays nothing at all —
 *       the row's own {@code quasarEmitter} stays {@code null} by design (a row leg
 *       would still run under LAYER). The herald leg also re-anchors sky-high
 *       (+{@value #HERALD_SKY_OFFSET}) — the cue pos is the secret surface point.</li>
 *   <li><b>gate fanfare</b> — one cue, two moments: {@code b} picks the fanfare or the
 *       collapse asset pair. Quasar half always plays (reducedFx = Quasar-only via the
 *       bridge's own gate).</li>
 *   <li><b>finish ribbon</b> — {@code a} = podium position: 1 gets the gold-burst
 *       variant, later finishers the violet one; under reducedFx only position 1 keeps
 *       its (Quasar) ribbon. {@code allowMulti} forced: two finishers can close laps at
 *       the same ring anchor inside one asset lifetime.</li>
 * </ul>
 *
 * <p>The {@code CUE_DUNGEON_MAW_IDLE} loop row is WINDOWED-only (INTEGRATION.md §4);
 * its hysteresis window controller is {@link DungeonMawIdle} below (materialize
 * ≤ {@value DungeonMawIdle#MATERIALIZE_DIST}, release &gt;
 * {@value DungeonMawIdle#RELEASE_DIST}, released unconditionally under
 * {@code reducedFx}/dimension change/logout).</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class WorldEventPhotonFxRows {
    /** C1: camera distance at which the beacon column starts widening (blocks). */
    private static final double BEACON_NEAR_DIST = 96.0D;
    /** C1: max X/Z width multiplier for far cameras (the disc-wide readability knob). */
    private static final double BEACON_MAX_WIDTH_SCALE = 8.0D;
    /** C4: the herald visual hangs this far above the (secret) surface cue pos. */
    private static final double HERALD_SKY_OFFSET = 70.0D;

    private WorldEventPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // C1 — Summon Beacon: 4 tinted mile-high columns; Quasar thin pillar as the
        // real row fallback (SEQUENCE — reducedFx clients keep it, the plan's ask).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SUMMON_BEACON,
                fx("boss_summon_beacon_0"),
                quasar("summon_beacon_pillar"),
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldEventPhotonFxRows::playSummonBeacon));
        // C2 — Omen Ripple: reducedFx skips BOTH halves (shake/music/text carry it), so
        // the leg owns the Quasar spawn and the row's own quasar leg stays null.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_CONTRACT_OMEN,
                fx("contract_omen_ripple"),
                null,
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldEventPhotonFxRows::playOmenRipple));
        // C3a — Gate Fanfare / collapse (b switches the asset pair; Quasar always).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_MINIGAME_GATE,
                fx("minigame_gate_fanfare"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldEventPhotonFxRows::playGateCue));
        // C3b — Finish Ribbon (a = podium position; reducedFx = position 1 only).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_RACE_FINISH,
                fx("race_finish_ribbon"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldEventPhotonFxRows::playFinishRibbon));
        // C4 — Supply Herald: reducedFx skips the whole pre-beat (beam announces), so
        // the leg owns both halves like the omen; sky-anchored at pos + 70.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SUPPLY_HERALD,
                fx("supply_herald"),
                null,
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldEventPhotonFxRows::playSupplyHerald));
        // C5 one-shot — Dungeon Maw Breath: plain LAYER row, default leg; reducedFx
        // keeps the Quasar dust bank (bridge gate drops the Photon half automatically).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_DUNGEON_FOUND,
                fx("dungeon_maw_breath"),
                quasar("dungeon_maw_dust"),
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false));
        // C5 loop — dungeon maw idle breath: Photon-first REPLACE with a Quasar
        // stand-in, WINDOWED-only (DungeonMawIdle owns the hysteresis window).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_DUNGEON_MAW_IDLE,
                fx("dungeon_maw_idle"),
                quasar("dungeon_maw_idle"),
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.REPLACE,
                true));
    }

    // ------------------------------------------------------------------ custom legs

    /**
     * C1 leg: variant by boss kind ({@code a}, clamped 0–3) + distance-scaled X/Z width
     * — 1× inside {@value #BEACON_NEAR_DIST} blocks, growing linearly to
     * {@value #BEACON_MAX_WIDTH_SCALE}× so the hairline never thins below a pixel from
     * across the disc. Y scale stays 1 (the column is authored mile-high; its cull box
     * keeps it frustum-visible from afar).
     */
    private static boolean playSummonBeacon(ResourceLocation photonFx, Vec3 pos,
            @Nullable net.minecraft.world.entity.Entity entity, float a, float b) {
        int kind = Mth.clamp((int) a, 0, 3);
        double dist = Math.sqrt(Minecraft.getInstance().gameRenderer.getMainCamera()
                .getPosition().distanceToSqr(pos));
        double widthScale = Mth.clamp(dist / BEACON_NEAR_DIST, 1.0D, BEACON_MAX_WIDTH_SCALE);
        return PhotonBridge.spawn(fx("boss_summon_beacon_" + kind), pos,
                PhotonBridge.SpawnOptions.DEFAULT.withScale(widthScale, 1.0D, widthScale));
    }

    /**
     * C2 leg: {@code b} = 0 the dread (crimson ripple) / 1 the release (gray snuff).
     * reducedFx skips the row ENTIRELY (returning {@code true} marks the cue consumed);
     * otherwise the Quasar half always plays (LAYER baseline for photon-less clients)
     * and the Photon half rides the bridge's own guard chain.
     */
    private static boolean playOmenRipple(ResourceLocation photonFx, Vec3 pos,
            @Nullable net.minecraft.world.entity.Entity entity, float a, float b) {
        if (EclipseClientConfig.reducedFx()) {
            return true; // C2 reduced spec: shake + music + banner already carry it
        }
        boolean release = b > 0.5F;
        QuasarSpawner.spawnOrFallback(
                quasar(release ? "contract_omen_snuff" : "contract_omen_ring"),
                pos, FxBudget.Channel.SEQUENCE);
        return PhotonBridge.spawn(
                release ? fx("contract_omen_release") : photonFx, pos);
    }

    /** C3a leg: {@code b} = 0 fanfare / 1 collapse — asset pair switch, Quasar always. */
    private static boolean playGateCue(ResourceLocation photonFx, Vec3 pos,
            @Nullable net.minecraft.world.entity.Entity entity, float a, float b) {
        boolean collapse = b > 0.5F;
        QuasarSpawner.spawnOrFallback(
                quasar(collapse ? "minigame_gate_collapse" : "minigame_gate_ring"),
                pos, FxBudget.Channel.BURST);
        return PhotonBridge.spawn(
                collapse ? fx("minigame_gate_collapse") : photonFx, pos);
    }

    /**
     * C3b leg: {@code a} = podium position. reducedFx keeps the ribbon for position 1
     * only (Quasar-only via the bridge gate); position 1 earns the gold-burst variant.
     * {@code allowMulti} forced: near-simultaneous finishers share the ring anchor.
     */
    private static boolean playFinishRibbon(ResourceLocation photonFx, Vec3 pos,
            @Nullable net.minecraft.world.entity.Entity entity, float a, float b) {
        int position = Math.max(1, (int) a);
        if (EclipseClientConfig.reducedFx() && position != 1) {
            return true; // reduced spec: ribbon only for gold
        }
        QuasarSpawner.spawnOrFallback(quasar("race_finish_ribbon"), pos,
                FxBudget.Channel.BURST);
        return PhotonBridge.spawn(
                position == 1 ? fx("race_finish_ribbon_gold") : photonFx, pos,
                PhotonBridge.SpawnOptions.DEFAULT.withAllowMulti(true));
    }

    /**
     * C4 leg: the cue pos is the SECRET surface point — the visual hangs
     * {@value #HERALD_SKY_OFFSET} blocks above it (the crate spawns at surface+60, so
     * the ember streak falls straight down its future line). reducedFx skips the whole
     * pre-beat: the beam remains the announcement.
     */
    private static boolean playSupplyHerald(ResourceLocation photonFx, Vec3 pos,
            @Nullable net.minecraft.world.entity.Entity entity, float a, float b) {
        if (EclipseClientConfig.reducedFx()) {
            return true;
        }
        Vec3 sky = pos.add(0.0D, HERALD_SKY_OFFSET, 0.0D);
        QuasarSpawner.spawnOrFallback(quasar("supply_herald_tear"), sky,
                FxBudget.Channel.SEQUENCE);
        return PhotonBridge.spawn(photonFx, sky);
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }

    private static ResourceLocation quasar(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }

    // ------------------------------------------------------------------ C5 idle window

    /**
     * NEWFX-C5 WINDOWED-loop controller (the {@code AltarCoronaIdle} pattern): keeps the
     * {@code CUE_DUNGEON_MAW_IDLE} breath alive at the nearest DISCOVERED underground
     * site anchor while the camera sits inside the hysteresis band. The anchor table is
     * recomputed client-side from the deterministic {@link UndergroundSites#sitesFor}
     * rolls (pure function of the frozen map seed — the {@code BreachAmbience}
     * client-computable-geometry precedent) and gated per site on the
     * {@code dungeon:<siteId>} unlock key synced by {@code UnlockSync}; undiscovered
     * holes stay unmarked (anti-spoiler law). Re-anchoring is release + re-ensure (the
     * registry supports one live loop per logical id). Released unconditionally on
     * {@code reducedFx} / dimension change / logout (loop law).
     */
    @EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT)
    public static final class DungeonMawIdle {
        /** Window materializes within this camera distance (blocks)… */
        static final double MATERIALIZE_DIST = 32.0D;
        /** …and releases only beyond this one (hysteresis — no boundary thrash). */
        static final double RELEASE_DIST = 48.0D;
        private static final double MATERIALIZE_DIST_SQ = MATERIALIZE_DIST * MATERIALIZE_DIST;
        private static final double RELEASE_DIST_SQ = RELEASE_DIST * RELEASE_DIST;
        /** Refused-spawn retry cadence (ticks) — the SanctumLightfall cadence. */
        private static final int RETRY_TICKS = 40;

        /** Lazily built {@code siteId → anchor center} table (reset on logout). */
        @Nullable
        private static Map<String, Vec3> anchors;
        /** The site currently holding the window, or {@code null} while closed. */
        @Nullable
        private static String openSiteId;
        private static int retryCountdown;

        private DungeonMawIdle() {}

        @SubscribeEvent
        static void onClientTick(ClientTickEvent.Post event) {
            Minecraft minecraft = Minecraft.getInstance();
            ClientLevel level = minecraft.level;
            if (level == null || level.dimension() != Level.OVERWORLD
                    || EclipseClientConfig.reducedFx()) {
                close(false);
                return;
            }
            Vec3 camera = minecraft.gameRenderer.getMainCamera().getPosition();
            String nearestId = null;
            Vec3 nearestAnchor = null;
            double nearestDistSq = Double.MAX_VALUE;
            for (Map.Entry<String, Vec3> site : anchorTable().entrySet()) {
                if (!ClientUnlockCache.isKeyUnlocked(DungeonDiscovery.KEY_PREFIX + site.getKey())) {
                    continue; // undiscovered holes stay unmarked
                }
                double distSq = camera.distanceToSqr(site.getValue());
                if (distSq < nearestDistSq) {
                    nearestDistSq = distSq;
                    nearestId = site.getKey();
                    nearestAnchor = site.getValue();
                }
            }
            boolean open = openSiteId != null;
            if (nearestId == null
                    || nearestDistSq > (open ? RELEASE_DIST_SQ : MATERIALIZE_DIST_SQ)) {
                close(true); // walked away: graceful fade, not a pop
                return;
            }
            if (minecraft.isPaused()) {
                return; // keep the window, freeze the cadence
            }
            if (open && !nearestId.equals(openSiteId)) {
                close(false); // re-anchor = release + re-ensure (registry law)
            }
            openSiteId = nearestId;
            if (--retryCountdown > 0) {
                return;
            }
            boolean live = PhotonFxRegistry.ensureLoop(FxCues.CUE_DUNGEON_MAW_IDLE, nearestAnchor);
            // Healthy leg: re-ensure every tick (idempotent prune + re-spawn). Refused
            // (photon absent AND Quasar budget refusal): back off RETRY_TICKS.
            retryCountdown = live ? 1 : RETRY_TICKS;
        }

        /** Disconnect reset — the table pins the last save's frozen-seed rolls too. */
        @SubscribeEvent
        static void onLoggingOut(ClientPlayerNetworkEvent.LoggingOut event) {
            close(false);
            anchors = null;
        }

        /**
         * All underground-site anchors of every possible stage (2 … final radius index):
         * committed-stage filtering is unnecessary client-side — an UNcommitted site can
         * never carry a {@code dungeon:} unlock key, so the key gate already excludes it.
         */
        private static Map<String, Vec3> anchorTable() {
            Map<String, Vec3> table = anchors;
            if (table == null) {
                table = new LinkedHashMap<>();
                int finalStage = FrozenParams.stageRadii(DiscProfile.OVERWORLD).length - 1;
                for (int stage = 2; stage <= finalStage; stage++) {
                    for (PendingSite site : UndergroundSites.sitesFor(DiscProfile.OVERWORLD, stage, 0L)) {
                        table.put(site.siteId(), Vec3.atCenterOf(site.anchor()));
                    }
                }
                anchors = table;
                EclipseMod.LOGGER.debug("DungeonMawIdle anchor table built: {} sites", table.size());
            }
            return table;
        }

        private static void close(boolean graceful) {
            if (openSiteId != null) {
                PhotonFxRegistry.releaseLoop(FxCues.CUE_DUNGEON_MAW_IDLE, graceful);
            }
            openSiteId = null;
            retryCountdown = 0;
        }
    }
}
