package dev.projecteclipse.eclipse.veilfx;

import javax.annotation.Nullable;

import dev.projecteclipse.eclipse.EclipseMod;
import dev.projecteclipse.eclipse.network.fx.FxCues;
import dev.projecteclipse.eclipse.veilfx.rift.RiftFx;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

/**
 * PH-WORLD's {@link PhotonFxRegistry} row registrar ({@link PhotonFxRows} reference
 * pattern) — the landmark concepts from {@code docs/plans_v3/plans_v5/photon/
 * IDEAS-world.md} (#5 sky launcher, #6b end void wisps, #7 nether breach). Assets are
 * generated by {@code tools/photon/build_world_fx.py} (fxlib, the committed source for
 * the eight PH-WORLD {@code assets/eclipse/fx/*.fx} blobs).
 *
 * <p>All rows are {@code Mode.LAYER} with a {@code null} Quasar leg BY DESIGN
 * (IDEAS-world.md fallback tables): the photon-less baseline for each cue is the shipped
 * server/vanilla stack, which keeps running unchanged for every client — the sky
 * launcher's END_ROD golden-angle spiral + CLOUD/END_ROD launch bursts
 * ({@code SkyLauncher.tickCharges/launch}), the breach's CAMPFIRE/SOUL_FIRE ambience
 * ({@code BreachTransferService.ambientTick}), and (for the void wisps) deliberately
 * nothing — pure garnish, absence is today's behavior. Registering a NEW Quasar emitter
 * as a fallback would CHANGE photon-less visuals, violating the degradation law
 * (INTEGRATION.md §3 rule 2: every failure renders exactly today's frame).</p>
 *
 * <p>The two sky-launcher rows are SEQUENCE-grade one-shots inside the cue law; the
 * {@code CUE_SKY_LAUNCH} row carries a custom Photon leg because its contrail must ride
 * the launched player: it resolves the nearest player to the cue pos (the
 * {@code FxPayloads.nearestPlayer} glide pattern, {@value #LAUNCH_MATCH_RANGE}-block
 * match) and attaches via {@code PhotonBridge.spawnOnEntity} — entity death auto-cleans
 * mid-flight; an untracked player degrades to the block anchor.</p>
 *
 * <p>The three loop rows are WINDOWED-only (INTEGRATION.md §4): payload-firing them is a
 * warned no-op; the only drivers are the {@code client/breach/BreachAmbience} and
 * {@code client/end/EndVoidWisps} hysteresis windows ({@code ensureLoop}/{@code
 * releaseLoop}). Every loop asset carries a renderer cull box + hard {@code
 * maxParticles}; {@code reducedFx} both refuses new spawns (bridge gate) and makes the
 * windows release live loops outright.</p>
 */
@EventBusSubscriber(modid = EclipseMod.MOD_ID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public final class WorldPhotonFxRows {
    /** How far the launch cue pos may be from a player to attach the contrail to them. */
    private static final double LAUNCH_MATCH_RANGE = 8.0D;

    private WorldPhotonFxRows() {}

    @SubscribeEvent
    static void onClientSetup(FMLClientSetupEvent event) {
        // IDEAS-world #5 — charge helix, block-anchored at the pad center (the cue pos
        // is Vec3.atCenterOf(pad), the same origin the server spiral orbits).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SKY_LAUNCH_CHARGE,
                fx("sky_launch_charge"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false));
        // IDEAS-world #5 — launch contrail, entity-attached to the launched player.
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_SKY_LAUNCH,
                fx("sky_launch_contrail"),
                null,
                FxBudget.Channel.BURST,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldPhotonFxRows::playLaunchContrail));
        // IDEAS-world #7 — breach ash geyser + ember updrafts (BreachAmbience window).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_BREACH_ASH_GEYSER,
                fx("breach_ash_geyser"),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_BREACH_EMBER_UPDRAFT,
                fx("breach_ember_updraft"),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
        // IDEAS-world #6b — end-disc void wisps (EndVoidWisps window).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_END_VOID_WISPS,
                fx("end_void_wisps"),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
        // PH-IMPROVE-2 (IDEAS-world #6a Option B) — dragon-death crack light-bleed:
        // 3 splayed HDR shafts + seam-strip embers per crack-race step. The custom leg
        // exists ONLY to record the played position so RiftFx.openRift can retire its
        // generic EXPANSION_RIFT_GLOW for that tear (REPLACE-by-suppression — photon-less
        // clients keep the full shipped rift stack, including the glow).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_END_CRACK,
                fx("end_crack_bleed"),
                null,
                FxBudget.Channel.SEQUENCE,
                PhotonFxRegistry.Mode.LAYER,
                false,
                WorldPhotonFxRows::playEndCrackBleed));
        // PH-IMPROVE-2 (IDEAS-world #10) — Orin's observatory hearth ambience
        // (client/wizard/ObservatoryAmbience window; chimney anchor).
        PhotonFxRegistry.registerRow(new PhotonFxRegistry.Row(
                FxCues.CUE_WIZARD_HEARTH,
                fx("wizard_hearth"),
                null,
                FxBudget.Channel.AMBIENT,
                PhotonFxRegistry.Mode.LAYER,
                true));
    }

    /**
     * {@code CUE_SKY_LAUNCH} Photon leg: prefer the payload's entity (the launch is sent
     * on the ENTITY lane), degrade to the nearest player like the glide events do, then
     * to the block anchor when the flyer is untracked entirely.
     */
    private static boolean playLaunchContrail(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        Entity rider = entity != null ? entity : nearestPlayer(pos, LAUNCH_MATCH_RANGE);
        if (rider != null) {
            return PhotonBridge.spawnOnEntity(photonFx, rider, PhotonBridge.AUTO_ROTATE_NONE,
                    (Vec3) null);
        }
        return PhotonBridge.spawn(photonFx, pos); // untracked flyer — block-anchor fallback
    }

    /**
     * {@code CUE_END_CRACK} Photon leg (PH-IMPROVE-2, IDEAS-world #6a Option B): plain
     * position spawn — race steps land 4t apart at DIFFERENT BlockPos, so the default
     * dedup can never eat a step. When the leg actually plays, the position is handed to
     * {@link RiftFx#suppressStructureGlow} so the {@code FX_RIFT_OPEN} arriving right
     * behind it retires its generic {@code EXPANSION_RIFT_GLOW} for that tear. A
     * refused/photon-less spawn records nothing: those clients keep the full shipped
     * rift stack, glow included.
     */
    private static boolean playEndCrackBleed(ResourceLocation photonFx, Vec3 pos,
            @Nullable Entity entity, float a, float b) {
        boolean played = PhotonBridge.spawn(photonFx, pos);
        if (played) {
            RiftFx.suppressStructureGlow(pos);
        }
        return played;
    }

    /** Nearest client-level player to a cue position (FxPayloads.nearestPlayer pattern). */
    @Nullable
    private static Player nearestPlayer(Vec3 pos, double maxRange) {
        ClientLevel level = Minecraft.getInstance().level;
        if (level == null) {
            return null;
        }
        Player best = null;
        double bestDistSq = maxRange * maxRange;
        for (Player player : level.players()) {
            double distSq = player.distanceToSqr(pos);
            if (distSq < bestDistSq) {
                bestDistSq = distSq;
                best = player;
            }
        }
        return best;
    }

    private static ResourceLocation fx(String path) {
        return ResourceLocation.fromNamespaceAndPath(EclipseMod.MOD_ID, path);
    }
}
